### ISSUE TITLE
Break from for loop if time exceeds an hour

### ISSUE THREAD

**Issue by schollz** [schollz/croc#10]
Specifically these two for loops: [1](https://github.com/schollz/croc/blob/91f31993ecde9a5c1c56dd92257606d4d2ce9692/relay.go#L117-L126) and [2](https://github.com/schollz/croc/blob/91f31993ecde9a5c1c56dd92257606d4d2ce9692/relay.go#L117-L126) should keep track of time and return if it exceeds some time (maybe an hour).

**Comment by fazekasda** [comment]
May i have this one?

**Comment by schollz** [comment]
Yes go for it! Let me know if you need any help

**Comment by schollz** [comment]
@fazekasda There's been a lot of changes recently, so make sure to sync up!
