### ISSUE TITLE
extra progress file not deleted when transfer finished

### ISSUE THREAD

**Issue by codeskyblue** [schollz/croc#100]
```
-rw-r--r-- 1 pi pi    18 Oct 22 09:48 run-cow.sh
-rw-r--r-- 1 pi pi     2 Oct 22 09:48 run-cow.sh.progress
```

**Comment by schollz** [comment]
@codeskyblue Can you print the version of croc? Also can you do the sender and receiver in debug mode (add `--debug`) and paste the content here? This is not a behavior I've seen before.

**Comment by schollz** [comment]
Closing now, let me know if you have more information

**Comment by codenoid** [comment]
weird bug,

`croc version "v4.1.4-2018-11-06T03:06:41Z"`

*.progress file not deleted on first-try download

**Comment by schollz** [comment]
@codenoid, is this reproducible?

**Comment by schollz** [comment]
This shouldn't be an issue anymore since progress files are no longer used in v6.
