### ISSUE TITLE
Implement a configuration file

### ISSUE THREAD

**Issue by Fastidious** [schollz/croc#102]
It would be helpful to have `croc` create a configuration file upon first run (say, `.crocrc`) with encryption defaults, default relay server (and, potentially, others) which then could be changed, should the user were to run its own.

**Comment by schollz** [comment]
Yeah, I added it! Its just not in the master yet.

https://github.com/schollz/croc/commit/81bc06eabb295417186b33770ae6c1f90bf76909

**Comment by schollz** [comment]
@Fastidious Its now live. 

The configuration file basically just has all the flags that you can set in the CLI. If you change a configuration variable AND you change the CLI flag when you run the program, then the flag takes precedent and overrides the config.

**Comment by Fastidious** [comment]
Awesome. I found a couple of issues.
```
dreadnought:croc_4.1.0_macOS-64bit david$ ./croc config

error: open /Users/david/.config/croc/config.toml: permission denieddreadnought:croc_4.1.0_macOS-64bit david$
```
It seems the directory is created missing the execute bit. The error is also missing some returns, to make it more legible. After adding the execute bit to the `croc` directory I was able to successfully create the `config.toml`:
```
dreadnought:croc david$ croc config
Default config file written at '/Users/david/.config/croc/config.toml'dreadnought:croc david$ nano -w /Users/david/.config/croc/config.toml
```
It is still missing some `\r\n`, as you can see. Running under macOS Mojave.

**Comment by Fastidious** [comment]
Excellent, closing!
