### ISSUE TITLE
Can't access the getcroc.schollz.com

### ISSUE THREAD

**Issue by greyireland** [schollz/croc#107]
## Actual Behavior
ping getcroc.schollz.com
PING getcroc.schollz.com (198.199.67.130): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

Can't access this site in China.
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version (`croc -version` or let me know latest commit in git log if using dev):
  - Platform:
  - Subsystem:

**Comment by schollz** [comment]
@greyireland Can you do 

```bash
cat https://raw.githubusercontent.com/schollz/croc/master/.github/default.txt | bash
```
