### ISSUE TITLE
Better defined behavior when recipient tries receiving before sender sends

### ISSUE THREAD

**Issue by michal037** [schollz/croc#109]
## Expected Behavior
The program should return to its initial state when it does not receive a response for several minutes.

## Actual Behavior
No timeout function.

## Steps to Reproduce the Problem
  1. Launch Croc
  2. Click 'Receive'
  3. Select any directory
  4. Type any random password
  5. Here: The program is not responding!

## Specifications
  - Version: croc_4.1.1_Windows-64bit_GUI.zip
  - Platform: Windows 10

**Comment by schollz** [comment]
@michal037 Not sure if this is a bug.

The normal operation is that sender sends and then receiver types in the sender's code phrase to receive. The receiver should not be trying to receive before getting the code phrase from a sender (unless its an attacker).

**Comment by michal037** [comment]
@schollz 

It is true, it is pointless to enter the wrong password. However, it would be useful to be able to undo the "mistake", for example to create a "back" button.

Look at this scenario:

Someone wants to send a file, received a password and sent it to the recipient. The sender had a problem, he lost his connection to the internet, he stopped the program, whatever. At that time, the recipient entered the password and his program blocked.

This is the reason why I thought it was worth creating this issue.

**Comment by schollz** [comment]
@michal037 Okay, yeah that is very reasonable. 

This could be done pretty easily through the relay - as the sender should always be connecting to a room first.

**Comment by schollz** [comment]
@michal037 Okay I pushed a fix where the recipient waits 3 seconds before quitting if the sender is not there.

**Comment by michal037** [comment]
@schollz Thank you for the fix!

---

How exactly is the connection between the sender and the recipient set up each time?

1. Method 1
a. The recipient enters the password.
b. The recipient connects to the **server**.
c. The recipient connects to the **sender**, or when the sender is not there, waiting for him for 3 seconds.

2. Method 2
a. The recipient enters the password.
b. The recipient **tries to connect** to the server **for 3 seconds** to get a connection with the sender.

I want to be aware of whether I understand the connection method. Because during the second method, the time of 3 seconds may be too short when the computer network is overloaded.

---
After the following message appears: 'You are trying to receive a file with no sender.', the program opens the directory indicated earlier by the user. I am not sure if opening this directory is needed.

**Comment by schollz** [comment]
Thanks, yeah the directory opening is another problem which should be fixed soon.

The recipient doesn't wait for a sender, ever. If the sender is not there, it needs to exit. The 3 seconds is just time enough to connect to the server to see if the sender is there.

**Comment by michal037** [comment]
You're right. Thank you for the explanation.
