### ISSUE TITLE
Issue when Go Get the app

### ISSUE THREAD

**Issue by ledongthuc** [schollz/croc#110]
## Expected Behavior
 Get the app

## Actual Behavior
return errors:
```
package github.com/schollz/progressbar/v2: cannot find package "github.com/schollz/progressbar/v2" in any of:
	/Users/thucle/.gvm/gos/go1.9/src/github.com/schollz/progressbar/v2 (from $GOROOT)
	/Users/thucle/.gvm/pkgsets/go1.9/global/src/github.com/schollz/progressbar/v2 (from $GOPATH)
```

## Steps to Reproduce the Problem

  1. Open command line, run `go get github.com/schollz/croc`

## Specifications

  - Version: 818e590d924795321ee06d1143552ff465250d16
  - Platform: MacOS 10.13.6
  - Go Version: 1.9

**Comment by nilayparikh** [comment]
Hi I am on higher version but still having similar issue,

D:\organisations\xxxx\xxxxx\source\go> go get -u github.com/schollz/progressbar/v2
package github.com/schollz/progressbar/v2: cannot find package "github.com/schollz/progressbar/v2" in any of:
        C:\Go\src\github.com\schollz\progressbar\v2 (from $GOROOT)
        D:\organisations\xxxx\xxxx\source\go\src\github.com\schollz\progressbar\v2 (from $GOPATH)
D:\organisations\xxxx\xxxx\source\go> go version
go version go1.12.1 windows/amd64

**Comment by schollz** [comment]
Use `$env:GO111MODULE="on"`
