### ISSUE TITLE
Bash installation on MacOS Fails with checksum error

### ISSUE THREAD

**Issue by viam-invenient** [schollz/croc#111]
## Expected Behavior
Successful Installation

## Actual Behavior
curl https://getcroc.schollz.com | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5205  100  5205    0     0  11095      0 --:--:-- --:--:-- --:--:-- 11098
Downloading croc v4.1.1 (macOS 64bit)...
Verifying checksum...
bash: line 146: sha256sum: command not found
Aborted, error 127 in command: checksum="$(sha256sum ${dl}) $croc_file"

## Steps to Reproduce the Problem

  1. attempt curl https://getcroc.schollz.com | bash
  1. wget command works too
  1.

## Specifications

  - Version (`croc -version` or let me know latest commit in git log if using dev): croc version "v4.1.1-2018-10-24T13:52:40Z"
  - Platform: macOS Mojave 10.14 18A391 x86_64
  - Subsystem:

**Comment by schollz** [comment]
Oooh didn't realize that sha256sum is not on Mac. Can you do a `brew install sha256sum` or something? I don't have a Mac so I"m not sure I can assist

**Comment by Fastidious** [comment]
@schollz on macOS is `shasum`.

**Comment by schollz** [comment]
Which Sha does it use?

**Comment by Fastidious** [comment]
@schollz a snippet from the man page:
```
        Usage: shasum [OPTION]... [FILE]...
        Print or check SHA checksums.
        With no FILE, or when FILE is -, read standard input.

          -a, --algorithm   1 (default), 224, 256, 384, 512, 512224, 512256
          -b, --binary      read in binary mode
          -c, --check       read SHA sums from the FILEs and check them
          -t, --text        read in text mode (default)
          -p, --portable    read in portable mode
                                produces same digest on Windows/Unix/Mac
          -0, --01          read in BITS mode
                                ASCII '0' interpreted as 0-bit,
                                ASCII '1' interpreted as 1-bit,
                                all other characters ignored

        The following two options are useful only when verifying checksums:
          -s, --status      don't output anything, status code shows success
          -w, --warn        warn about improperly formatted checksum lines

          -h, --help        display this help and exit
          -v, --version     output version information and exit

        When verifying SHA-512/224 or SHA-512/256 checksums, indicate the
        algorithm explicitly using the -a option, e.g.

          shasum -a 512224 -c checksumfile
```

**Comment by schollz** [comment]
@Fastidious Thanks, try now

**Comment by viam-invenient** [comment]
@Fastidious and @schollz Thank you guys so much!

**Comment by schollz** [comment]
@viam-invenient Does it work?

**Comment by Fastidious** [comment]
@schollz yes, it works.
