### ISSUE TITLE
Detect possible send intention for file/folder instead of code

### ISSUE THREAD

**Issue by dorxy** [schollz/croc#112]
## Current behavior
When I try to send a file but forget 'send' in my command, there is no feedback that I might be doing something wrong. The tool outputs 'performing PAKE' and nothing else seems to happen.

## Improved behavior
When the first argument of the command is a detectable file or folder location, prompt the user with a message if they meant to send this file instead of directly interpret the argument as a code.
Perhaps for automated scripts this prompt can be bypassed with a --non-interactive flag.

**Comment by schollz** [comment]
Can you give me an example of the exchange in the UI?

Something like:

```
$ croc file.txt
Did you mean to send `file.txt`? (y/n)
... do sending if yes ...
```
