### ISSUE TITLE
Minimal, missing \r\n

### ISSUE THREAD

**Issue by Fastidious** [schollz/croc#113]
When **croc** is run, and no code is entered (just hit return), the following happens:
```
dreadnought:~ david$ croc
Enter receive code:

error: codephrase is too shortdreadnought:~ david$
```
Same happens when the code entered is wrong:

```
dreadnought:~ david$ croc
Enter receive code: sdfsdff

You are trying to receive a file with no sender.dreadnought:~ david$
```

**Comment by schollz** [comment]
Thanks @Fastidious , https://github.com/schollz/croc/commit/cf2363fd4e0ae4f6ee98bfc4275f533bfbd2c282 should fix it!
