### ISSUE TITLE
my propositions for improving the GUI - cosmetic changes

### ISSUE THREAD

**Issue by michal037** [schollz/croc#114]
## First

_Run Croc > Click Send > Select any file and apply it_

At this point, 'Code phrase' is shown. The sender still sees two buttons: `Send` and `Receive`. They do not have large functionalities. I propose you replace them with one `Cancel`. This will allow you to change the file if you make a mistake without restarting the program (Before sending the code phrase to the recipient.). Both buttons should not be visible.

## Second

_Run Croc > Click Send > **HERE** > Select any file and apply it_

Message `Click 'Send' or 'Receive' to start` does not disappear.
Message `please wait...` did not appear.

## Third

_Run Croc > Click Receive > Do not select any directory and do not click apply, just close this window._

At this point the message `please wait...` is displayed all the time. I propose you to clear this message, because the user canceled receiving the file. When I click cancel it should return to the initial messages.

## Fourth

_Run Croc > Click Receive > Select any directory and click apply > Do not enter 'Code phrase', just close this window._

At this point the message `Invalid codephrase: ''` is displayed all the time. I propose you to clear this message, because the user canceled receiving the file. Then change `Invalid codephrase: ''` to `Invalid code phrase: ''` - with a space between words.

## Fifth

_Run Croc_

You see the inscription 'secure data transfer', I propose you write the first character of each word with a capital letter. `secure data transfer` -> `Secure Data Transfer`. In my opinion, it looks better then.

---

Tested on: croc_v4.1.2_Windows-64bit_GUI.zip (latest release)

**Comment by schollz** [comment]
Thanks, those are good changes, I'll incorporate them into the next release
