### ISSUE TITLE
croc relay option

### ISSUE THREAD

**Issue by zedstar** [schollz/croc#117]
## Expected Behavior

croc with relay option doesnt work as expected - quote from wiki - 

"You can send files using your relay by entering -relay to change the relay that you are using if you want to custom host your own.

$ croc -relay "ws://myrelay.example.com" send [filename]"

## Actual Behavior

$ croc -relay
Incorrect Usage. flag provided but not defined: -relay

## Steps to Reproduce the Problem

  1. run -> croc -relay
  1.
  1.

## Specifications

  - Version (`croc -version` or let me know latest commit in git log if using dev): v4.1.5-2019-01-02T00:02:02Z
  - Platform: OSX, ARM
  - Subsystem:

**Comment by schollz** [comment]
Thanks, the flag should be `-addr`, updated in readme
