### ISSUE TITLE
Question: maybe possible with mobile also

### ISSUE THREAD

**Issue by ghost** [schollz/croc#118]
I use golang on mobiles. It's pretty easy. 
So it's possible to get this project working between desktop and mobiles.
The trick however will be knowing the system calls for IOS and Android ( and maybe chrome  OS since android apps work on chrome OS these days )

I can get croc working with a GUI, but not sure of the API calls.

Anyone interested in this and helping investigate the API calls ?

**Comment by quite** [comment]
This is interesting. Though I have not yet even tried building a mobile app in *any* language. To start with, I would be interested learning to build something for android with as much go as possible (and flutter?). Do you have any pointers? Sorry for hijacking this issue!

**Comment by gedw99** [comment]
Gomobile compiles to iOS and Android.
Then you make a flutter plugin to wrap it.

Best to use JSON to make life easy initially.
Can upgrade to grpc once things working.

**Comment by gedw99** [comment]
If your interested we can work on this together. Do you have flutter experience ?

**Comment by dospunk** [comment]
Would love to see this

**Comment by rpush-01** [comment]
The Gomobile framework, although not optimized or widely used, is good enough for now, if you want to use Go for developing on mobile its one of the main options. If it became popular we would probably convert to Native, I know Swift for that, maybe someone knows Kotlin. If you don't care about the language, Flutter(Dart), and React Native(JS, TS) are pretty good. If you know JS apparently Dart isn't too difficult to learn, although I don't know it. 

https://dev.to/_tink3r/introduction-to-gomobile-19af

**Comment by nsr-py** [comment]
I would love to work on this but, just like @quite , I don't have any experience developing mobile apps. I do have some web development skills; mainly javascript and react (not react native). 
I am ready to learn basic app development (if required). If someone could point out some good resources it would be much appreciated.

**Comment by bartekpacia** [comment]
I thought about croc on mobile now and just saw this issue. It'd be an awesome idea. Is there any work taking place (maybe some GH repo)?

**Comment by clach04** [comment]
Cross reference to https://github.com/schollz/croc/issues/247 (which links to an Android implementation)
