### ISSUE TITLE
Croc is currently broken?

### ISSUE THREAD

**Issue by toonn** [schollz/croc#121]
## Expected Behavior
```
sender> croc send file
  Code: spaghetti-is-delicious
receiver> croc spaghetti-is-delicious
  file transfer 100% done
```

## Actual Behavior
```
sender> croc send file
  Code: spaghetti-is-delicious
receiver> croc spaghetti-is-delicious
  You are trying to receive a file with no sender.
```

## Specifications

  - Version: 4.1.5
  - Platform: sender linux/receiver windows, sender mac/receiver same mac

**Comment by schollz** [comment]
Can you print the actual full output from both sides?

**Comment by toonn** [comment]
I can't seem to reproduce it today. Maybe the PAKE server was down or something? The sender just got stuck on the "On the other computer run: croc code-here" message though and the receiver side was the actual full output modulo a newline.

**Comment by schollz** [comment]
I'm not sure, I'll close this until it is reproducible
