### ISSUE TITLE
UX issue around continued transfers

### ISSUE THREAD

**Issue by toonn** [schollz/croc#122]
When continuing an interrupted transfer the already transferred bits are included in the transfer speed calculation. This results in silly speeds à la `7423874 MB/s` in the beginning and while this does settle somewhat while the transfer continues the estimate is too optimistic and makes the estimated completion time inaccurate if not useless.

Thanks for croc! It's great software and the focus on ease of use makes it a really valuable entry among similar softwares. ❤️

**Comment by schollz** [comment]
should be fixed with newest progressbar
