### ISSUE TITLE
Bad handshake?

### ISSUE THREAD

**Issue by toonn** [schollz/croc#123]
After stopping a stalled transfer with `^C` I've been getting this error:
```
2019-03-31 21:39:06 [ERROR] sending.go sendReceive:160 websocket: bad handshake 

websocket: bad handshake
```

This is on a mac. I have no idea what it's about or how to fix it?
Same result on a linux machine. Maybe the relay is refusing a connection to my IP?

**Comment by schollz** [comment]
Does it send properly without canceling?

I think you may have to update to the newest version.

**Comment by toonn** [comment]
Hmm, never mind. Turns out this was because of some data gating from my ISP. Somehow hit croc before it hit normal web browsing.
