### ISSUE TITLE
Croc default server not reachable.

### ISSUE THREAD

**Issue by Bluefire-610** [schollz/croc#135]
The default Croc server (croc4.schollz.com) doesn't seem to be reachable, trying to send a file returns the following error message:

`2019-07-07 19:00:49 [31m[ERROR][0m sending.go sendReceive:160 dial tcp: lookup croc4.schollz.com: no such host`

I could replicate this on multiple windows devices in multiple - unrelated - networks within Europe.

**Comment by schollz** [comment]
Could you upgrade to the newest version?
