### ISSUE TITLE
Pipe-to-bash should not be suggested for a project with emphasis on security

### ISSUE THREAD

**Issue by icefoxen** [schollz/croc#136]
The first option for installation the docs state is: `curl https://getcroc.schollz.com | bash`.  I appreciate the desire for convenience, but this really isn't anything other than a gun looking for a foot to shoot, and I feel like we shouldn't be encouraging it.

I would also argue that "does not require a server" while using a relay server is getting *uncomfortably close* to false advertising, albeit obviously not on purpose since you talk about the relay server openly.  Perhaps "does not transfer files through a server", or "does not store files on a server" would be more accurate?

Thank you, this is a neat project though!  Feels a bit like Dat, but is simpler and smaller.

**Comment by schollz** [comment]
@icefoxen 

There are other options for installing listed.

If you don't want to pipe-to-bash then I would suggest building from source as described in the readme.

**Comment by icefoxen** [comment]
Yeah, sorry if I came off as grumpy.  I'm just of the camp that "pipe to bash" should never be an option, let alone the first option advertised.  You might as well store passwords in plaintext.  Though I do appreciate that there's no *easier* option*.  :man_shrugging:
