### ISSUE TITLE
machineid: exec: "kenv": executable file not found in $PATH

### ISSUE THREAD

**Issue by jungle-boogie** [schollz/croc#137]
Hi,

Thanks for writing croc - you've found a good problem to solve. 
If you're interested, I first found out about it here:
https://lobste.rs/s/j0butq/easily_securely_send_things_from_one

Unfortunately, I haven't been able to test it out on OpenBSD -current amd64, because of this message:

```
$ croc send runbsd.png 
[error] 2019/07/14 16:32:00 croc.go:221: machineid: exec: "kenv": executable file not found in $PATH
```
Is there some other binary I need to install on OpenBSD?
I built croc from src and used your binary, but both are generating the same message.

```
$ croc --version
croc version v6.0.11-6d9105a
```
It doesn't look like I have any problems receiving files from Ubuntu Linux amd64:

```
$ croc tulip-
Accept 'minicom.log' (35 B)? (y/n) y

Receiving (<-192.168.0.16:9009)
minicom.log 100% |████████████████████| (1.4 kB/s) [0s:0s] ✔️
```

**Comment by schollz** [comment]
Hm, I don't know OpenBSD, but it looks like `kenv` is used in this package to get the machine ID: https://github.com/denisbrodbeck/machineid#snippets

If its a problem I can probably just get rid of that dependency. I don't use it for anything, its a holdover from a previous version.

**Comment by schollz** [comment]
@jungle-boogie Btw, thanks for that link. That site is invite-only - would you be able to invite me? I'd like to shed light on some of the design decisions that are being discussed in that thread, it looks like a good place to get feedback.

**Comment by jungle-boogie** [comment]
Hi @schollz,

I also don't have an account and don't know of anyone to ask for an account. I think there's an irc channel you can join and perhaps request an account.

**Comment by jungle-boogie** [comment]
It looks like you are importing the machineID library:
https://github.com/schollz/croc/blob/master/src/croc/croc.go#L20

And it looks like it was cloned on my system:
`/home/jungleboogie/gopath/src/github.com/denisbrodbeck/machineid`

`BSD uses /etc/hostid and smbios.system.uuid as a fallback`

My system doesn't have that file. I'll see if I can find where a machineID would be stored for OpenBSD.

**Comment by schollz** [comment]
@jungle-boogie Great! You should make an issue/PR for @denisbrodbeck, I bet he would appreciate it!

**Comment by jungle-boogie** [comment]
If you don't use `kenv`, would you consider removing that dependency? Issue opened with Denis for `kenv`

**Comment by schollz** [comment]
Cool.

Yeah, machineid is now gone! https://github.com/schollz/croc/releases/tag/v6.0.12

**Comment by jungle-boogie** [comment]
Verified fixed in
```
$ croc --version                                  
croc version v6.0.12-fbbdd1b
```

Thank you!

**Comment by justinmerrell** [comment]
> Cool.
> 
> Yeah, machineid is now gone! https://github.com/schollz/croc/releases/tag/v6.0.12

I see that machineid has returned. 
Compiling with GOOS=js GOARCH=wasm and it does not like that package. Tested on v6.0.12 and compiled without issue. 

Just curious about this change.
