### ISSUE TITLE
Config file for sticky parameters

### ISSUE THREAD

**Issue by gufertum** [schollz/croc#140]
Is it possible to add some kind of config to make the relay information sticky?

**Comment by Fastidious** [comment]
This commit (https://github.com/schollz/croc/commit/562925b5e5211e351734a3dc5d5bf179cd1ff134) implemented a config and used to work. I really wonder why it was dropped. @schollz?

**Comment by schollz** [comment]
@Fastidious During the rewrite I didn't implement. I think it would be nice to have too, lets keep this issue open for it.

**Comment by schollz** [comment]
Okay, I've added `--remember` which will save the current settings for sender/receiver and which will be reloaded next time (unless overridden).

**Comment by schollz** [comment]
https://github.com/schollz/croc/commit/bd7ab1a9be95eb5a615661caba0fd3427f687291

**Comment by gufertum** [comment]
👍
