### ISSUE TITLE
No checking for live relay on sending

### ISSUE THREAD

**Issue by CompuRoot** [schollz/croc#141]
### Use case:

1. Shutdown relay (emulate occurrence of network or server down)
2. Send some files with `--relay` option as `croc --relay "8.8.8.8:12345" ./someFile`
3. Start relay
4. On receiving side try to receive file with password generated on originator.

**Result:** receiver stack on "connecting..."

**Suggestion:** check for live relay on sending in the same way as it's done on receiving and abort sending in case of inability to connect to relay

Thank for a little, portable and nice `croc` !

**Comment by schollz** [comment]
@CompuRoot 

I don't understand the sender's role here? You are saying that a receiver connecting without a sender will hang? This is actually defined behavior. If the receiver connects to the relay first (like it does in your example), then it will wait for the sender to connect.

**Comment by CompuRoot** [comment]
No, Im saying, that if you start sender and in this moment there wouldn't be listening relay, then sender just waiting as usually and don't show any error message but in fact there no relay.
If you after that you would start relay and will try to receive file from that sender(that started when relay was down) then receiver (as well sender) will wait forever for each other

**Comment by schollz** [comment]
Yeah, this is defined behavior.

The sender actually connects to *two* relays. It connects to the public one (which you disabled in your example) but it won't complain because it also connects to a local one. The local one is used for LAN file transfer. Since it doesn't known whether the transfer will occur via LAN or public for either, it will wait for either. You can disable local though with `-no-local`.

**Comment by CompuRoot** [comment]
@schollz 

I running relay outside on LAN, on dedicated server with dedicated static IP address and assuming if I using `--relay` option on sender && receiver then communication would happen over this particular relay **only** (Please confirm, if it is).   BTW, I didn't saw anywhere in documentation, that  "sender actually connects to two relays". Does it means that sender always starting local relay ?
Anyway, I tried your suggested option `-no-local` and the latest release 6.0.12 refuse to start with error: "`flag provided but not defined: -no-local`"

**Comment by schollz** [comment]
Here's the relevant code: https://github.com/schollz/croc/blob/master/src/croc/croc.go#L225-L321

The sender will open a local relay as well as connecting to the relay specified.  

The flag is `--no-local`:

```
$ croc send --help
NAME:
   croc send - send a file

USAGE:
   croc send [command options] [filename]

DESCRIPTION:
   send a file over the relay

OPTIONS:
   --code value, -c value  codephrase used to connect to relay
   --no-local              disable local relay when sending
   --ports value           ports of the local relay (optional) (default: "9009,9010,9011,9012,9013")
```

**Comment by CompuRoot** [comment]
@schollz  

I'm really sorry to annoy you, but `--no-local` doesn't help.
Step-by-step issue reproduction:

1. Stop your own relay if it working  
(relay that runs outside of LAN, somewhere on dedicated server on internet)
2. Issue on the sender's side:   
`croc --relay "IP.OF.OWN.RELAY:12345" send --no-local /path/2/file/2/send`
3. Start your own (not a local) relay (that one that have been stopped in step `#1`):   
 `croc relay --ports "12345,12346,12347"`
4. Issue on receiver's side: `croc --relay "IP.OF.OWN.RELAY:12345"` 
5. Provide on receiver's side a password that was generated in step `#2`
6. Receiver will stuck with `connecting...` message as well the sender would still awaiting for receiver.

All three communicating parties are working in this case without actual file transfer.

**Comment by schollz** [comment]
Yes, so the bug I see here is with your step 2. 

In that case, the local relay is not being used and then the connection is refused but  it still hangs.

I can confirm this happens:

```
$ croc --debug --relay localhost:9008 send --no-local now.json
[debug] 12:52:46 croc.go:131: options: {IsSender:true SharedSecret:iron-slow-mike Debug:true RelayAddress:localhost:9008 RelayPorts:[9009 9010 9011 9012 9013] Stdout:false NoPrompt:false DisableLocal:true}
[debug] 12:52:46 croc.go:213: file 0 info: {Name:now.json FolderRemote:. FolderSource:/home/zns/go/src/github.com/schollz/recipeingredients-server/ Hash:[203 1 58 108 197 82 196 26 15 104 82 163 165 44 242 39] Size:203 ModTime:2019-07-17 10:50:08.577601663 -0600 MDT IsCompressed:false IsEncrypted:false}
Sending 'now.json' (203 B)
Code is: iron-slow-mike
On the other computer run

croc iron-slow-mike
[debug] 12:52:46 croc.go:294: establishing connection to localhost:9008
[debug] 12:52:46 croc.go:297: banner:
[debug] 12:52:46 croc.go:300: could not connect to localhost:9008: dial tcp 127.0.0.1:9008: connect: connection refused
...hangs...
```

I think what should happen in that case is that the sender should give up, prompting the user to try again.

Steps 3 and 6 are fine. The receiver will get the file once the sender reconnects.

**Comment by schollz** [comment]
@CompuRoot I just pushed a commit that should fix it.

**Comment by CompuRoot** [comment]
@schollz 

Yes, that what I meant originally, - sender should be make sure if relay (non local ) is working and in case if sender can't communicate to relay then fail gracefully with some error message or **better yet** wait some specified timeout period for relay and then fail or run depending on relay availability.

<hr>

BTW, wouldn't be it more logical to generate correct message on sender's side when own relay is used, so instead of:  
```
    Sending 'someFile.zip' (3.0 MB)
    Code is: some-generated-password
    On the other computer run

    croc some-generated-password
```

IMHO it would be more correct:  
```
    Sending 'someFile.zip' (3.0 MB)
    Code is: some-generated-password
    On the other computer run  

    croc --relay "provided.on.start.relaysIP:port" some-generated-password
```

otherwise if users would follow instruction, they won't be able to find each other in this case.

**Comment by schollz** [comment]
@CompuRoot That's a great idea. Can you make a new issue with that?

**Comment by CompuRoot** [comment]
Yes, sure, will do now
