### ISSUE TITLE
crock chokes on empty files

### ISSUE THREAD

**Issue by pdobsan** [schollz/croc#145]
Using croc 6.1.0 and running my own relay on a VPS I encountered a strange problem. Whenever croc transfers an empty file, for example a zero size lock file, it gets stuck forever and cannot continue with further files. The empty file has been transfered however.

I compiled croc from sources, and the three machines involved were running archlinux.

**Comment by schollz** [comment]
Thanks, I've seen this bug before. I will work on it.

**Comment by schollz** [comment]
Should work now: https://github.com/schollz/croc/releases/tag/v6.1.1
