### ISSUE TITLE
Snap [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [schollz/croc#147]
I was wondering if you might have an interest in [snap](https://snapcraft.io/). Snap also supports and works with Goreleaser too. https://goreleaser.com/snapcraft/

**Comment by schollz** [comment]
This snap has been requested (it requires classic confinement): https://forum.snapcraft.io/t/request-for-classic-confinement-of-croc/14284

**Comment by schollz** [comment]
https://snapcraft.io/croc

**Comment by PauloGDPeixoto** [comment]
Sorry for commenting on a closed issue, but what happened to the snap?

**Comment by schollz** [comment]
@PauloGDPeixoto snap does not support access to all files ([dot files are restricted](https://forum.snapcraft.io/t/croc-needs-permission-for-dotfiles-in-home/17424/10)). It doesn't make sense for me to develop workarounds for something like that - better just not to use snap.
