### ISSUE TITLE
Install Script FreeBSD Support and Checksum Checks

### ISSUE THREAD

**Issue by TheQueasle** [schollz/croc#149]
I was attempting to install this on my FreeNAS box (FreeBSD) and encountered an issue when the install script gets to the checksum part.

The command `sha256sum` does not appear to be available on FreeBSD.  At least I could not find it.

While I was working on the script to fix this issue, I also noticed that it seems like the logic that does the checksum verification may not be working (lines 145-158).

```
  echo "Verifying checksum..."
  if [[ $unameu == *DARWIN* ]]; then
    checksum="$(shasum -a 256 ${dl}) $croc_file"
  else
    checksum="$(sha256sum ${dl}) $croc_file"
  fi
  checksum_check="$(cat ${dl_checksum} | grep $croc_file) $croc_file"

  if [[ "$s1" != "$s2" ]]; then
    echo "${checksum}"
    echo "${checksum_check}"
    echo "checksums are not valid, exiting"
    return 7
  fi
```

The variables `$s1` and `$s2` don't seem to be assigned anywhere.  So when the script is ran, the check `f [[ "$s1" != "$s2" ]]` will always be true.

Example run with debug output on a linux host:
```
Verifying checksum...
+ [[ LINUX == *DARWIN* ]]
++ sha256sum croc_6.1.1_Linux-64bit.tar.gz
+ checksum='87057e1a7db3dc9c91f2fb4839ab8bebaa7ad6cc31b38e84850db72dcd4b1a4d  croc_6.1.1_Linux-64bit.tar.gz croc_6.1.1_Linux-64bit.tar.gz'
++ cat croc_6.1.1_Linux-64bit.tar.gz.checksum
++ grep croc_6.1.1_Linux-64bit.tar.gz
+ checksum_check='87057e1a7db3dc9c91f2fb4839ab8bebaa7ad6cc31b38e84850db72dcd4b1a4d  croc_6.1.1_Linux-64bit.tar.gz croc_6.1.1_Linux-64bit.tar.gz'
+ [[ '' != '' ]]
+ echo Extracting...
```

A PR will follow shortly.

**Comment by schollz** [comment]
This was merged! https://github.com/schollz/croc/pull/150
