### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by EdisonJwa** [schollz/croc#160]
connecting...could not connect to 142.93.177.120:9009: dial tcp 142.93.177.120:9009: connect: connection refused

**Comment by schollz** [comment]
Server was down, I put it up as soon as I saw this message, thanks!

**Comment by adamclark64** [comment]
just got the same response
```
connecting...could not connect to 142.93.177.120:9009: comm.NewConnection failed: dial tcp 142.93.177.120:9009: connect: connection refused
```

**Comment by schollz** [comment]
Is reproducible? Different machines, same problem? What version of croc?

**Comment by adamclark64** [comment]
```➜ croc -v
croc version v8.3.1-9d5302b
```
from my machine i run `croc send <file>` and get a a code phrase

on my machine and another when i run `croc <code phrase>` the response is 
```
connecting...could not connect to 142.93.177.120:9009: comm.NewConnection failed: dial tcp 142.93.177.120:9009: connect: connection refused
```

**Comment by NilsIrl** [comment]
Got this error just now. `croc send` works but it fails when it comes to downloading the files itself. Nothing in my setup changed since last time I used croc.

**Comment by schollz** [comment]
> 
> 
> Got this error just now. `croc send` works but it fails when it comes to downloading the files itself. Nothing in my setup changed since last time I used croc.

Public relay is down, see https://github.com/schollz/croc/issues/366
