### ISSUE TITLE
Error as user "tcp/hi: unknown port"

### ISSUE THREAD

**Issue by vesche** [schollz/croc#162]
Hey there, first off just want to say thanks I use this tool daily and I love it. First time I've seen this error "unknown port"? I decided to yolo run it as root and it worked. Just wanted to report it.

```
$ croc my-code-thing
connecting...could not connect to 192.168.1.2:hi: dial tcp: address tcp/hi: unknown port
$ sudo my-code-thing
Accept 'foo.tar.gz' (25.6 MB)? (y/n) y
Receiving (<-ip:60043)
```

I'm on Arch Linux, I'm using croc_6.2.0_Linux-64bit.tar.gz
```
$ uname -a
Linux hostname 4.19.80-1-lts #1 SMP Fri Oct 18 05:03:40 UTC 2019 x86_64 GNU/Linux
```

**Comment by schollz** [comment]
@vesche This is a weird error. 

I can think of two things. Are you using the `--remember` flag to save config? Do you have the `RelayPort` option set to `hi`?

The other possibility it that you had something else on the peer discovery channel which was broadcasting `hi` as its payload and not the port. Is this error reproducible?

**Comment by vesche** [comment]
Yes, I just re-ran everything (both sides of the transfer) and am getting that same error. I'm on a shared wifi connection working at the moment, so I have no idea what could be going down on this network. I am not using this `--remember` option and have no RelayPort option.

So, I just connected to a VPN, and everything works fine now. Someone maybe is doing something weird on this net? Time to go get a coffee somewhere else... I'll close this. Thanks for the fast reply.

**Comment by vesche** [comment]
Thanks :+1:
