### ISSUE TITLE
croc starts eating a lot of CPU if noone retrieves file.

### ISSUE THREAD

**Issue by kazie** [schollz/croc#168]
```
> croc --version
croc version v6.2.0-ffddd3e
```

So today I set up a file to send, but my friend said he was going to do the download later (several hours). So I left croc on with `send` and left it at that.

Many hours later, I was checking `htop` on the same computer and saw that said croc session had started to chew a lot of CPU on two threads.

![2019-11-11-184128_655x38_scrot](https://user-images.githubusercontent.com/1390887/68609008-8c23c400-04b4-11ea-8437-cbf6107b895b.png)

--- 

When trying to reproduce the issue, I see that initially croc takes a thread for a little while (probably doing some pre-work?) before going dormant. (reason for different PID's is probably that I took screenshot of different times, due to behaviour)
Doing some work: 
![2019-11-11-184427_649x46_scrot](https://user-images.githubusercontent.com/1390887/68609162-e3299900-04b4-11ea-87f3-7803c13f00a5.png)
Going dormant:
![2019-11-11-184733_657x23_scrot](https://user-images.githubusercontent.com/1390887/68609176-ea50a700-04b4-11ea-9088-c3e040ffe9f3.png)

---

So thus far have not reproduced the bug again - but I assume and suspect it is something to do with if the process is running for a long while it will chew more and more CPU.

---

I don't know if it is `croc`, some library or `go`. But will report back if I can see the issue again.
Either it is a 'one off thing' or just simply a bug once the process has been running for a while. 

---

And while typing, didn't take too long (a few minutes?) and it started to take 100% CPU.

![2019-11-11-190101_658x25_scrot](https://user-images.githubusercontent.com/1390887/68609549-d6597500-04b5-11ea-967c-21437e8f1829.png)

Hope this bug report helps you find out the issue!

**Comment by schollz** [comment]
Thanks! Looking into it

**Comment by schollz** [comment]
I think I found the problem. While waiting for connections (sometimes) the relay server will send back EOFs...not sure why. But since this is in a forever loop it will constantly be processing those bytes. I just put a throttle on it so that should curb the problem (not entirely fix) if it happens again.

I only reproduced this a few times. Otherwise croc seems to use 0% cpu while waiting to send.

**Comment by kazie** [comment]
The time when it comes to the state where it reads `EOF` forever, to me it seems like that the file will never be able to be sent.
And thus woudn't it be better to crash/exit, than having a eternal for-loop sleeping for 100ms each iteration?

**Comment by schollz** [comment]
What exactly are you doing to get this error?

**Comment by kazie** [comment]
Sending a file, and having bad luck while no-one is going to receive it?

I mean, does the mitigation that was patched actually do anything other than eating lower CPU due to the sleep mitigation. Can the data actually be recieved?

When I tried (still same version as before) I was able to fetch the file when not bugged, and client is stuck on `connecting...` when the bug has arrived.

---

Now trying to reproduce to show. Where in I have no _doing anything in particlar_ other than no incoming connection.

---

One way I could reproduce this issue manually is to have one trying to fetch the file, and telling `no`. Then the thread spins and program never exists as noone can connect 

----

User comes in and presses `n`
![2019-11-18-192221_1362x749_scrot](https://user-images.githubusercontent.com/1390887/69078868-15994000-0a39-11ea-8c24-bcddd9e6e5d6.png)

No new connections can be done, croc send is running CPU.
![2019-11-18-192250_1364x744_scrot](https://user-images.githubusercontent.com/1390887/69078881-1a5df400-0a39-11ea-954f-fd5146572427.png)

---

This behaviour seems to be the same as when random-junk data or what you described it as comes - putting it in the same state. And as I see it, it doesn't look like it will never be able to continue the program coming to a exit state from here. (Thus adding the sleeps as mitigation really doesn't solve the problem?).

**Comment by schollz** [comment]
What version of croc is this?

**Comment by kazie** [comment]
`croc version v6.2.0-ffddd3e`

**Comment by schollz** [comment]
Can you try running the latest version? And then try using the `--debug` flag to see what is happening?

**Comment by kazie** [comment]
Ok, I have updated to:
```
croc version v6.3.0-497ffb8
```

Will now wait for a while (as I've done before) to test. running with `--debug`` will report back in a while!

(mini test without waiting looking good so far!)

**Comment by kazie** [comment]
So, I waited a while, then connected accidently hit `Ctrl+C` in shock instead of answering `n` . But as soon as it connected is sprayed out *A LOT* of the same message.
And now it became stuck in that forever loop again.

![2019-11-18-210310_1365x373_scrot](https://user-images.githubusercontent.com/1390887/69087626-133de280-0a47-11ea-9d64-ee99974023a9.png)

**Comment by kazie** [comment]
I tried to send again, and it instantly got into the same loop:
```log
croc --debug send -c some-password-here bios.img
[debug]	21:05:22 cli.go:123: debug mode on
[debug]	21:05:22 croc.go:148: options: {IsSender:true SharedSecret:some-password-here Debug:true RelayAddress:142.93.177.120:9009 RelayPorts:[9009 9010 9011 9012 9013] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
[debug]	21:05:22 croc.go:226: file 0 info: {Name:bios.img FolderRemote:. FolderSource:/home/kazie/tmp/ Hash:[128 128 128 16 5 128 27 44 221 68 203 195 86 249 38 110] Size:33554432 ModTime:2019-09-03 22:46:22.438031057 +0200 CEST IsCompressed:false IsEncrypted:false}
[debug]	21:05:22 croc.go:228: longestFilename: 8
Sending 'bios.img' (33.6 MB)
Code is: some-password-here
On the other computer run

croc some-password-here
[debug]	21:05:22 croc.go:330: establishing connection to 142.93.177.120:9009
[debug]	21:05:22 tcp.go:53: starting with password 'pass123'
[debug]	21:05:22 tcp.go:53: starting with password 'pass123'
[debug]	21:05:22 tcp.go:53: starting with password 'pass123'
[info]	2019/11/18 21:05:22 starting TCP server on 9013
[debug]	21:05:22 tcp.go:53: starting with password 'pass123'
[info]	2019/11/18 21:05:22 starting TCP server on 9011
[info]	2019/11/18 21:05:22 starting TCP server on 9010
[info]	2019/11/18 21:05:22 starting TCP server on 9009
[debug]	21:05:22 tcp.go:53: starting with password 'pass123'
[info]	2019/11/18 21:05:22 starting TCP server on 9012
[debug]	21:05:22 tcp.go:281: sending password
[debug]	21:05:22 tcp.go:286: waiting for first ok
[debug]	21:05:22 tcp.go:297: sending room
[debug]	21:05:22 tcp.go:302: waiting for room confirmation
[debug]	21:05:22 tcp.go:311: all set
[debug]	21:05:22 croc.go:333: banner: 9010,9011,9012,9013
[debug]	21:05:22 croc.go:340: connection established: &{connection:0xc000010008}
[debug]	21:05:22 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:22 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
[debug]	21:05:22 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:22 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
[debug]	21:05:23 croc.go:270: establishing connection
[debug]	21:05:23 tcp.go:281: sending password
[debug]	21:05:23 tcp.go:97: client [::1]:50364 connected
[debug]	21:05:23 tcp.go:108: waiting for password
[debug]	21:05:23 tcp.go:286: waiting for first ok
[debug]	21:05:23 tcp.go:124: sending '9010,9011,9012,9013'
[debug]	21:05:23 tcp.go:131: waiting for answer
[debug]	21:05:23 tcp.go:297: sending room
[debug]	21:05:23 tcp.go:302: waiting for room confirmation
[debug]	21:05:23 tcp.go:311: all set
[debug]	21:05:23 croc.go:273: banner: 9010,9011,9012,9013
[debug]	21:05:23 croc.go:280: connection established: &{connection:0xc000010080}
[debug]	21:05:23 tcp.go:153: room some-password-here has 1
[debug]	21:05:23 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:23 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
[debug]	21:05:23 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:23 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
[debug]	21:05:23 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:23 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
[debug]	21:05:23 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:23 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
[debug]	21:05:23 croc.go:344: [&{connection:0xc000010008}] had error: EOF
[debug]	21:05:23 croc.go:364: [&{connection:0xc000010008}] got weird bytes: []
```

**Comment by kazie** [comment]
And like I said, once it started that loop, instead of quitting it continues forever, and cannot connect to it.

![2019-11-18-210747_1357x265_scrot](https://user-images.githubusercontent.com/1390887/69088359-8ba4a380-0a47-11ea-9b79-8afa18e9c853.png)

Probaby when getting that `EOF` one should quit the program instead?

**Comment by schollz** [comment]
Yeah, so this turns out to be a little complicated. I had to introduce "pinging" so that the relay can keep track of connections and close them when they are exiting at the user side. I think the new release should work: https://github.com/schollz/croc/releases/tag/v6.4.0

**Comment by kazie** [comment]
Cool!
I might be able to, but cannot promise to test and verify once I get home for the evening in 14 hours or something. :)

**Comment by kazie** [comment]
![2019-11-19-233904_1365x379_scrot](https://user-images.githubusercontent.com/1390887/69192968-047a2d00-0b26-11ea-835f-b14681e78fe8.png)
![2019-11-19-233837_1365x378_scrot](https://user-images.githubusercontent.com/1390887/69192969-047a2d00-0b26-11ea-8247-45d47f94f230.png)

I might have a bad build, or wrong kind of setup now. But now it doesn't work, maybe do to same IP?
![2019-11-19-234205_1365x379_scrot](https://user-images.githubusercontent.com/1390887/69193066-40ad8d80-0b26-11ea-9359-9caaeb1e304a.png)

**Comment by schollz** [comment]
Are you using a custom relay?

**Comment by schollz** [comment]
Also can you try doing `--no-local` on the sender?

**Comment by kazie** [comment]
I was using default relay.

And if I run it using `--no-local` on the sender, then the client doesn't crash and works as expected.

With `--no-local` (running locally)
![2019-11-20-082051_1365x376_scrot](https://user-images.githubusercontent.com/1390887/69217390-dc62ec00-0b6e-11ea-81f2-9e24bb5eb748.png)

Without `--no-local`.
![2019-11-20-082114_1363x378_scrot](https://user-images.githubusercontent.com/1390887/69217389-dc62ec00-0b6e-11ea-9085-70d9ce778870.png)

**Comment by kazie** [comment]
Anyhow, that is probably a separate issue.
I can try to verify later today, and hopefully close this ticket later in the evening :).

**Comment by kazie** [comment]
Sorry for the delay :pray: 
I did a verification where I tried to send a file, waited for a long while - I see it logging about pings every second expecting everything to work as intended.
But as I connected from the other host it crashed instead.

Server:
```
... only ping logging above for 15 minutes or so ....
[debug]	23:27:19 croc.go:373: got ping
[debug]	23:27:19 croc.go:350: waiting for bytes
[debug]	23:27:19 tcp.go:106: checking connection of room sunday-alfonso-earth for &{connection:0xc000010008}
[debug]	23:27:19 tcp.go:114: room: {first:0xc0001e4020 second:<nil> opened:{wall:13793928465173287504 ext:504241669 loc:0xc02c40} full:false}
[debug]	23:27:19 croc.go:286: got ping
[debug]	23:27:20 croc.go:350: waiting for bytes
[debug]	23:27:20 tcp.go:97: client 192.168.1.123:54692 connected
[debug]	23:27:20 tcp.go:140: waiting for password
[debug]	23:27:20 tcp.go:156: sending '9010,9011,9012,9013'
[debug]	23:27:20 tcp.go:163: waiting for answer
[debug]	23:27:20 tcp.go:198: room sunday-alfonso-earth has 2
[debug]	23:27:20 tcp.go:214: starting pipes
[debug]	23:27:20 croc.go:292: exchanged header message
[debug]	23:27:20 croc.go:513: ready
[debug]	23:27:20 croc.go:605: received pake payload
[debug]	23:27:20 message.go:31: writing pake message (925 bytes)
[debug]	23:27:20 croc.go:353: [&{connection:0xc0001e6018}] had error: EOF
[debug]	23:27:20 croc.go:376: [&{connection:0xc0001e6018}] got weird bytes: []
[debug]	23:27:20 croc.go:390: exchanged header message
[debug]	23:27:20 croc.go:513: ready
[debug]	23:27:20 croc.go:530: got error receiving: EOF
[debug]	23:27:20 croc.go:399: error from errchan: EOF
EOF
```

Client (other machine on my network):
```
securing channel...panic: dial tcp 192.168.1.108:9010: connect: connection refused

goroutine 51 [running]:
github.com/schollz/croc/v6/src/croc.(*Client).procesMesssagePake.func1(0xc0002b5ab0, 0xc00006e780, 0xc0001322d0, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:652 +0x539
created by github.com/schollz/croc/v6/src/croc.(*Client).procesMesssagePake
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:642 +0x272
panic: dial tcp 192.168.1.108:9011: connect: connection refused

goroutine 52 [running]:
github.com/schollz/croc/v6/src/croc.(*Client).procesMesssagePake.func1(0xc0002b5ab0, 0xc00006e780, 0xc0001322d0, 0x1)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:652 +0x539
created by github.com/schollz/croc/v6/src/croc.(*Client).procesMesssagePake
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:642 +0x272
```

Both running:
```
croc version v6.4.5-88c4257
```

**Comment by schollz** [comment]
Thanks. I think I know the origin of this issue. I had it as well.

Does the recipient server have its ports open to the internet? I believe the issue is that the sender can connect to 9009 and then it thinks that that server is a local server and tries to connect via 9010, instead of using the public relay.

**Comment by schollz** [comment]
I believe that a fix is to check whether local addresses are really "local" or not using something like https://golang.org/pkg/net/#ParseCIDR

**Comment by kazie** [comment]
Ok, so it had nothing to do with the wait?
I tried a few times, without waiting, working every time.
![2019-11-21-235834_1365x373_scrot](https://user-images.githubusercontent.com/1390887/69383785-e42fa700-0cba-11ea-9546-718c205cd203.png)

So I actually have no idea what you're exactly asking about. It seems to me, like I have described since the beginning is that if the server is waiting for some time (like last here, 15 minutes or so) then a connection won't be possible?

I  this case, there should be no issue with the connection between them, they're on the same network.

**Comment by schollz** [comment]
Can you try the master version now? I pushed two changes that I think fixed the problem.

**Comment by schollz** [comment]
The connections are a bit tricky, let me try to explain.

Two computers meet on a public relay. At the same time, both computers check to see if they are on a local network. The local network takes precedence if it exists.

If the computers don't find themselves on the local network, it may be because of a local network issue in the multicast. To circumvent this, the computers exchange local IPs in a secure channel on the public relay. The recipient then tries to connect via the local network again. If this fails, it will fallback to the transfering through the public relay.

The problem here is that at the outset I don't know which scenario will occur so both scenarios (public and local) are tried simultaneously. The main connection is then switched once the local one is found, if it is found. At that point, because of the connection switch, the public relay was reading garbage data and that's where we got the CPU usage (I think) and also all the EOF/ zero bytes. Breaking out of that loop was bad though, because that connection was closing after the break. Instead I returned out of it and sent a innocuous error to close the goroutine.

**Comment by schollz** [comment]
Sorry for the complicated explanation. Maybe not even the right explanation. Please try the latest master (let me know if you need a build and I can supply that) and let me know if it works. Else I'll keep digging.

**Comment by kazie** [comment]
Ok, so running:
```
croc version v6.4.6-3c03719
```

I let it run for a while (40+ minutes?),i seeing lots of pinging still going on in the debug logs.
And no one can connect to it, not same host, not someone else on the same network or not even from a completely different network in another country.

Completely other network and country trying to connect:
![2019-11-22-074519_1365x373_scrot](https://user-images.githubusercontent.com/1390887/69404011-655b5e00-0cfc-11ea-9367-d74220596d0d.png)

Same network other computer trying to connect:
![2019-11-22-074347_1365x372_scrot](https://user-images.githubusercontent.com/1390887/69404012-655b5e00-0cfc-11ea-9a2b-ff9e7d66d32f.png)

Same computer trying to connect:
![2019-11-22-074257_1365x375_scrot](https://user-images.githubusercontent.com/1390887/69404013-655b5e00-0cfc-11ea-9e4e-916f2d17fa47.png)

I don't know who this `142.93.177.120` is, but it is refusing connections so I can't execute the test if it works or not. (probably the relay?)
I can probably test again later this weekend maybe, as I will be gone from the computer for a excursion until later this weekend.

**Comment by schollz** [comment]
Your recipient could never establish connection to the public relay. I don't know why. Maybe the relay was down during this time? Can you try again? I can't reproduce this problem.

**Comment by kazie** [comment]
Yeah, I tested it now, and since the server was working this time, I had no problems. 

So I am closing this ticket and considering it all good!

**Comment by eMPee584** [comment]
Uhm yeah getting this on `v10.4.3`, never recovers from 100% CPU usage 🤔
