### ISSUE TITLE
Hangs when didn't accept receive on the first try

### ISSUE THREAD

**Issue by maximbaz** [schollz/croc#171]
Person A sends a file using `croc send file.txt`

Person B runs `$ croc my-secret-key`, but when asked "Accept file (y/n)?" accidentally presses `Enter` without pressing `y`. This results in "refused files" (OK).

Person B runs `$ croc my-secret-key` a second time, but this time connection is never established, the process hangs on `connecting...`. 

Aborting with `Ctrl+C` and running `$ croc my-secret-key` again will result in `securing channel...EOF`, after which no files are received. Running `$ croc my-secret-key` once more hangs again with `connecting...`.

**Comment by schollz** [comment]
Thanks. This is an issue with it hanging on and waiting for the local channel (if there is one, since it doesn't ever know). In this case though person B is actually refusing the files so that should be transmitted back. I have a fix

**Comment by schollz** [comment]
@maximbaz Try that if you get a chance!

**Comment by maximbaz** [comment]
Fix confirmed, thank you 👍
