### ISSUE TITLE
install fails on macOS fresh install

### ISSUE THREAD

**Issue by ferebee** [schollz/croc#182]
Automated install fails on fresh macOS install (10.14.6) because the directory /usr/local/bin is not created by default during macOS installation.

```
Mac:~ root# curl https://getcroc.schollz.com | bash
[…]
install: /usr/local/bin/: No such file or directory
\e[0;31m== Install attempt returned an unexpected value of 71\e[0m
```

**Comment by schollz** [comment]
I can't help because I don't have a mac

**Comment by Fastidious** [comment]
@ferebee I checked the install, and `/usr/localbin/` must exist for a successful install. Simply create the directory and try again.

**Comment by Fastidious** [comment]
@schollz checking if the directory exists and, if not, creating it would solve this. It does exists on Linux as default, but not on macOS.

**Comment by schollz** [comment]
@Fastidious But, is `/usr/local/bin` a default PATH for macOS? If not, it might be better to use a different directory (that may already exist) which is part of the default PATH.

**Comment by Fastidious** [comment]
@schollz yes, it is a default path.

**Comment by schollz** [comment]
@TheQueasle what do you think of changing the [install script](https://github.com/schollz/croc/blob/master/src/install/default.txt) so that it will make the install directory, if it doesn't exist? I don't mean to assign to you. But I would welcome any thoughts (or PR if you're so inclined) that you have, if you can spare the time!

**Comment by TheQueasle** [comment]
@schollz I have no strong feelings against it.

I should be able to get a PR in within the next day or so (or sooner).

Oh, and feel free to ~throw me under the bus~ assign/include me in issues with the installer.  I don't mind putting my time into it :smile:

**Comment by schollz** [comment]
@TheQueasle haha okay. I'd love if you can send a PR. That script is a beautiful well-thought out piece of a code and I don't want to trip it out with my hacks.

**Comment by ferebee** [comment]
Everybody is exactly right about this! Sadly my skills don’t extend beyond pointing out the issue. Thanks, all.

**Comment by TheQueasle** [comment]
Hit this sooner than I thought I could :tada: 

(It gave me a reason to procrastinate on doing my budget... :rofl: )

**Comment by schollz** [comment]
Thanks @TheQueasle. Glad to serve you a break from your budgeting :)

@ferebee can you try it now? You can use the PR version this way:

```
curl https://github.com/schollz/croc/blob/247a6987575ad8ed27f25a3a904b2c15b69603a2/src/install/default.txt | bash
```

**Comment by ferebee** [comment]
I can confirm that this works correctly on macOS 10.14.6 with or without an existing `/usr/local/bin` directory. Thanks, guys, amazing turnaround. Glad I bought that $100K support contract.

@schollz BTW thanks for the pointer, I was wondering about that, but it turns out you need to do

```
curl https://raw.githubusercontent.com/schollz/croc/247a6987575ad8ed27f25a3a904b2c15b69603a2/src/install/default.txt | bash
```

to get the raw .txt.

**Comment by schollz** [comment]
👍 Thanks :)
