### ISSUE TITLE
Allow for the install script to handle 'userspace' installs (no `root` level permissions needed)

### ISSUE THREAD

**Issue by TheQueasle** [schollz/croc#184]
### Problem
An end user of `croc` should not need `sudo` to install croc into paths they have write access to (ie: userspace)

### Possible Solution
Allow the script to determine if the current user has the needed permissions to the requested install prefix to allow installation. 

### Alternatives
Documentation on how to do it without the need to write script logic.  For example: Download a release -> extract -> Add extraction path to PATH 

### Related Info
https://github.com/schollz/croc/pull/183

**Comment by TheQueasle** [comment]
I'm thinking I can forgo the permissions check if a user specifies `--user` during install and just attempt the install without any elevated permissions into the default prefix OR user specified prefix for a 'user' install.

I'm doing some research currently about what a 'standard' location may be for this type of install and, as I think we found before, it's really all over the place for installs like this.

Current feeling is based on `man hier` on my current system and do one of the two following possibilities for the default:
- `${HOME}/opt/croc/bin`
- `${HOME}/usr/local/bin`

@schollz Thoughts?
(also - sorry it has taken me this long to get back to this...)

**Comment by schollz** [comment]
@TheQueasle I think that sounds like a good solution. I like `${HOME}/usr/local/bin` because its more natural cousing to the `/usr/local/bin`.

**Comment by piyush-kgp** [comment]
hey @schollz I want to submit a PR on this if it is alright. I suppose the task at hand is to:

**Comment by piyush-kgp** [comment]
hey @schollz I want to submit a PR on this if it is alright. I suppose the task at hand is to:
1. add an optional `--user` flag
2. If `--user` flag is present, expect an argument for installation path [which defaults to `${HOME}/usr/local/bin` if argument is absent]

**Comment by stellarpower** [comment]
> @TheQueasle I think that sounds like a good solution. I like `${HOME}/usr/local/bin` because its more natural cousin to the `/usr/local/bin`.

At least on linux, I think ~/bin or ~/.local/bin are more conventional. ~/.local is the XDG-approved equivalent of /usr/local AFAIK, although I have mostly seen the ~/.local/bin folder used by python packages.

Prompting might be a good way, I think that is what micrommaba does now, as the curl one-liner from the croc readme is very useful for installation and always how I do it.
