### ISSUE TITLE
Question: Sending files with ZeroTier

### ISSUE THREAD

**Issue by Fastidious** [schollz/croc#187]
I have several machines connected through [ZeroTier](https://www.zerotier.com). How does croc handles this? Will transfers still go through the external—default—relay or, as ZeroTier machines can see each other as if they were in a local network, will they go machine to machine?

**Comment by KoEnix** [comment]
When inspecting croc in the ressourcemanager in windows, it seems to use the default relay as connection point to transfer data, even with two local machines in the same network sending and receiving.

For handling secure file transfer via croc in your virtual ZeroTier network, it would be best to host your own croc relay server. More infos on how to do this you can read in the Readme of croc

**Comment by Fastidious** [comment]
@KoEnix it seems I have found a bug then. It is my understanding that machines within the same network shouldn't be using the external (default) relay. What say you, @schollz?

**Comment by Fastidious** [comment]
@KoEnix I ran a croc relay for a long time. Just not using croc that often to merit having one running. Thanks, though!
