### ISSUE TITLE
--yes option doesn't skip 'did you mean to send' prompt

### ISSUE THREAD

**Issue by sammoth** [schollz/croc#189]
I would expect when sending something with croc, using the --yes option would skip the 'did you mean to send? prompt, but it doesn't seem to. As far as I can see there is no way to skip that prompt unless I'm missing something.

**Comment by schollz** [comment]
What command did you use to send?

**Comment by sammoth** [comment]
Ahh I was using just `croc file.xxx` not `croc send file.xxx`. I am stupid; apologies!

**Comment by yihuiluo235** [comment]
croc --yes send  this can work
