### ISSUE TITLE
Want: fallback to relay if connection fails on LAN

### ISSUE THREAD

**Issue by ferebee** [schollz/croc#192]
I haven’t looked at the code, I hope I’m not misdiagnosing.

Setup: I’m working on a client’s machine, which is connected to my LAN over Wi-Fi with a guest SSID that is firewalled from other LAN devices. I want to send a file with croc from one of my own machines to the machine on the guest Wi-Fi.

Observed behavior: receive fails with
`connecting...could not connect to 192.168.XX.YYY:9009 dial tcp 192.168.XX.YYY:9009: i/o timeout`

I presume the sending and receiving sides determine that they are on the same LAN and therefore attempt a direct connection, but the actual connection is blocked by the firewall in the Wi-Fi access point. (Perhaps not all traffic is firewalled? Internal SSID and guest SSID are being run through the same access point.)

Desired behavior: If a direct LAN connection fails to connect, fallback to a connection through an external relay.

**Comment by schollz** [comment]
Could you run both using `--debug` and share the output? I think this should be happening, but I've not tested this exact case.

**Comment by lpar** [comment]
I've seen this behavior too, when my Linux machine's firewalld blocks incoming connections. If I tell firewalld to open ports from 9009-9013 the transfer works.
