### ISSUE TITLE
When recipent types a spaces instead of hyphens, understand it.

### ISSUE THREAD

**Issue by jtagcat** [schollz/croc#193]
**Describe the solution you'd like**
For example if I type `croc social stock canada`, it should be interpreted as `croc social-stock-canada`

**Describe alternatives you've considered**
Write all words without any separator. Maybe even accept dots, underscores and other common separators.
**Additional context**

**Comment by schollz** [comment]
This is very easy to implement. I would happily accept a PR for this

**Comment by rkuprov** [comment]
Not sure if I understand the goal of this change. It seems a bit restrictive; too smart.

If I have a folder named `social stock canada`, I'd rather just use `TAB` to fill in the escaped characters.
If my folder uses underscores for names, `social_stock_canada`, then do we want `social stock canada` to be understood as `social_stock_canada` as well?

Finally, sending multiple files goes like this `croc file1.txt file2.pdf`. I'm afraid that the unintended consequence of this change would be combining the two files into `file1.txt-file2.pdf`. Am I missing something?

**Comment by jtagcat** [comment]
> Not sure if I understand the goal of this change. It seems a bit restrictive; too smart.
> 
> If I have a folder named `social stock canada`, I'd rather just use `TAB` to fill in the escaped characters.
> If my folder uses underscores for names, `social_stock_canada`, then do we want `social stock canada` to be understood as `social_stock_canada` as well?
> 
> Finally, sending multiple files goes like this `croc file1.txt file2.pdf`. I'm afraid that the unintended consequence of this change would be combining the two files into `file1.txt-file2.pdf`. Am I missing something?

If you want to send files you use `croc send file1.txt`, not `croc file1.txt`, thus it doesn't restrict your tab behavior.

Additionally, as a new issue, tab-completion for receiving should be possible (have all possible words and match against them), though implementation would be hard - a) have every possible combination and word as a command b) have those shell autocomplete things what you have to install manually and half the time don't work and each shell (bash, zsh, etc) wants their own completion file and if you don't know exactly what you are doing, you don't want to make and maintain it.

**Comment by rkuprov** [comment]
Resolved by: https://github.com/schollz/croc/pull/198
