### ISSUE TITLE
After a large transfer, croc freezes.

### ISSUE THREAD

**Issue by jtagcat** [schollz/croc#194]
**Describe the bug**
After file transfer, a checkmark gets displayed next to the item (if multiple files, then all files get a checkmark).
A newline gets spit out and then everything just freezes. Debug log says 'closing file'. Is it checksumming or something?

**Version**
Sender: `croc version v6.4.10-073569f` Proxmox 6.1-3
Recipient: `croc version v6.4.10-073569f` Windows Server 2019 Standard 1809

**Debug logs**
[croc-reipent.log](https://github.com/schollz/croc/files/4087202/croc-reipent.log)
[croc-sender.log](https://github.com/schollz/croc/files/4087203/croc-sender.log)

**Comment by schollz** [comment]
Does this happen every time?

**Comment by jtagcat** [comment]
With multiple different files, tried over 5 times yesterday.

**Comment by jtagcat** [comment]
@schollz was it solved somewhere or..?
