### ISSUE TITLE
Croc fails if either machine lacks an IPv4 address

### ISSUE THREAD

**Issue by lpar** [schollz/croc#196]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**
I just tried croc between two machines on the same local network, both of which have routable public IPv6 addresses, but one of which has no IPv4 connection.

Initiating a transfer from the IPv6-only machine, the receiver fails with "unexpected end of JSON input":

```
[debug] 13:25:44 cli.go:123: debug mode on
[debug] 13:25:44 croc.go:149: options: {IsSender:false SharedSecret:winter-eternal-lagoon Debug:true RelayAddress:142.93.177.120:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]    13:25:44 croc.go:418: attempt to discover peers
[debug] 13:25:44 croc.go:442: discoveries: []
[debug] 13:25:44 croc.go:443: establishing connection
[debug] 13:25:44 croc.go:449: establishing receiver connection to 142.93.177.120:9009
[debug] 13:25:44 tcp.go:313: sending password
[debug] 13:25:44 tcp.go:318: waiting for first ok
[debug] 13:25:44 tcp.go:329: sending room
[debug] 13:25:44 tcp.go:334: waiting for room confirmation
[debug] 13:25:44 tcp.go:343: all set
[debug] 13:25:44 croc.go:452: banner: 9010,9011,9012,9013
[debug] 13:25:44 croc.go:457: receiver connection established: &{connection:0xc000010010}
[debug] 13:25:44 croc.go:462: sending ips?
[debug] 13:25:44 croc.go:469: ips data: 
[debug] 13:25:44 croc.go:518: exchanged header message
securing channel...[debug]      13:25:44 croc.go:530: ready
[debug] 13:25:44 message.go:31: writing pake message (727 bytes)
[debug] 13:25:45 croc.go:552: got error processing: unexpected end of JSON input
unexpected end of JSON input
```

Initiating from the dual-stack system, croc tries to connect to IPv4, and fails:

```
[debug] 13:27:09 cli.go:123: debug mode on
[debug] 13:27:09 croc.go:149: options: {IsSender:false SharedSecret:jessica-pump-total Debug:true RelayAddress:142.93.177.120:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]    13:27:09 croc.go:418: attempt to discover peers
[debug] 13:27:10 croc.go:442: discoveries: []
[debug] 13:27:10 croc.go:443: establishing connection
[debug] 13:27:10 croc.go:449: establishing receiver connection to 142.93.177.120:9009
[debug] 13:27:10 croc.go:452: banner: 
could not connect to 142.93.177.120:9009: dial tcp 142.93.177.120:9009: connect: network is unreachable
```

I also tried running my own explicit relay, but got `connecting...could not connect to 2605:a601:ab68:2f00:8af:f435:49ee:8012: dial tcp: address 2605:a601:ab68:2f00:8af:f435:49ee:8012: too many colons in address`.

**Comment by unixfox** [comment]
I've the same exact issue.

**Comment by schollz** [comment]
@unixfox @lpar  Thanks for this issue. I would love to fix it, but I don't know how to make a test environment to play around with sending with ipv6 addresses. Any ideas?

**Comment by unixfox** [comment]
## If you want to have an IPv6 only environment

If you have IPv6 connectivity at home ([IPv6 test](https://ipv6-test.com/)) you can spin up a Debian VM with a bridge connection in VirtualBox so that the VM gets an IPv6 address. Then disable IPv4 completely: https://serverfault.com/a/269611 (a reboot is probably required). 
If you don't have IPv6 connectivity at home then search for a VPS provider that supports IPv6. For example DigitalOcean supports IPv6 (you need to check the IPv6 box before launching the VM). Then use the same technique to disable IPv4 completely: https://serverfault.com/a/269611 (a reboot is probably required).

## If you want to experiment with IPv6 while keeping IPv4 but you don't have IPv6 at home
[Tunnelbroker](https://www.tunnelbroker.net/) is a free service which provides IPv6 connectivity for people that only have IPv4. It works on Windows, Linux and MacOS. After creating [a regular tunnel](https://www.tunnelbroker.net/new_tunnel.php) head over the "Example configurations" tab then select your OS to have the commands needed to create the tunnel on your computer/VM.

**Comment by schollz** [comment]
@unixfox That's a nice tutorial, thanks!

Is there any way of doing it within Docker? I'd rather not re-configure any of my working systems and it would be easiest since anyone can spin up the Docker and test.

**Comment by unixfox** [comment]
Sure that's possible. I would be able to make a custom docker image for you.
Do you have IPv6 at home? Test it on [ipv6-test.com](https://ipv6-test.com/).
Which type of environment do you want? An IPv6 only environment (where you don't have IPv4 connectivity) (an environment similar to what I've and @lpar has) or an IPv6 + IPv4 environment?

**Comment by schollz** [comment]
It would be awesome if it was extensible from the `golang` image. E.g.:

```docker
FROM golang

WORKDIR /croc
COPY . .
RUN go build

CMD ["/croc/croc","send","--code","something","somefile"]
```

And another to receive:

```docker
FROM golang

WORKDIR /croc
COPY . .
RUN go build

CMD ["/croc/croc","--yes","--code","something"]
```

Ideally both would have IPV6 configurations so I can see if they will work or not within those environments.

**Comment by unixfox** [comment]
Ok I'll look into that this weekend. By the way is [ipv6-test.com](https://ipv6-test.com/) telling you that you have IPv6 connectivity on your computer?

**Comment by lpar** [comment]
On the Mac I just turned off IPv4 in the System Preferences to test. Network > Advanced > TCP/IP tab -> Configure IPv4: Off. No need to reboot, and you can switch it back on just as easily.

**Comment by unixfox** [comment]
Sorry for the long waiting time @schollz. I'm not able to make a Dockerfile for testing in a IPv6 only environment because it's too complicated for me due to the fact that Docker wasn't designed with IPv6 in mind (the IPv6 support on Docker came later on).

But if you would like to replicate an IPv6 only environment, like @lpar said you just have to disable IPv4 in your system preferences. This method works on Windows, Mac, Linux and Unix as long as you have an IPv6 connectivity at home. If you don't you can still have it by using a tunnel from https://www.tunnelbroker.net

I would really appreciate having croc working in IPv6 only environment because it's such a useful tool.

**Comment by schollz** [comment]
@unixfox Same! I don't have IPv6 at home/work but I just realized I could spin a DigitalOcean droplet to do it...  Do you know how to force IPv6 on Linux?

**Comment by unixfox** [comment]
There is a tutorial about disabling IPv4 on a Digitalocean droplet: https://www.digitalocean.com/docs/networking/ipv6/how-to/disable-ipv4/. But by doing this you will lose SSH connectivity to the droplet.
A way to workaround is to use the console or launching another droplet that will be used a bridge to the droplet with only an IPv6 connectivity.

**Comment by lpar** [comment]
If you have two machines on the same network at home, setting up IPv6 on your home network is probably the easiest option. It should just require turning it on in preferences, stateless autoconfig will do the rest.

You might also find that you have IPv6 (can ping 192.88.99.1) and your ISP just hasn't told you how to set it up. (That was the case for me [back in 2009](http://lpar.ath0.com/2009/01/20/getting-ipv6-enabled/).)

**Comment by lpar** [comment]
Just found [an article on setting up two IPv6 containers in Docker](https://collabnix.com/enabling-ipv6-functionality-for-docker-and-docker-compose/) and ping6ing between them.

**Comment by makeworld-the-better-one** [comment]
Is there any fix for this yet? Most of Go should work with well IPv6 by default.

**Comment by lpar** [comment]
Turns out you can reproduce the problem without needing an IPv6-only network or Docker.

Make sure `/etc/hosts` has an entry for `localhost6` pointing at `::1`, then

```
croc --relay localhost6:9009 send somefile.mp4
```

and in another terminal window,

```
croc --relay localhost6:9009 receive code-phrase-here
```

**Comment by schollz** [comment]
pinging this issue to let you know that a possibly compatible ipv6 release is out: https://github.com/schollz/croc/releases/tag/v8.1.0

@unixfox if you want, try it out and let me know if you run into problems

**Comment by unixfox** [comment]
@schollz thank you for trying to solve the IPv6 issue, I really appreciate.

I tested out of the box the new version (v8.1.0) and as expected it doesn't work because there are no know IPv6 relay:
```
connecting...could not connect to 142.93.177.120:9009: dial tcp 142.93.177.120:9009: connect: network is unreachable
```

But I tried with an IPv6 private relay and sometimes it gets stuck on "Connecting..." indefinitely:

```
root@croc-sender:~# croc --debug --relay [2a03:b0c0:2:d0::9a1:2001]:9009 send hello 
[debug]	12:17:26 cli.go:123: debug mode on
[debug]	12:17:26 croc.go:149: options: {IsSender:true SharedSecret:alamo-sardine-fuel Debug:true RelayAddress:[2a03:b0c0:2:d0::9a1:2001]:9009 RelayPorts:[9009 9010 9011 9012 9013] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
[debug]	12:17:26 croc.go:232: file 0 info: {Name:hello FolderRemote:. FolderSource:/root/ Hash:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Size:0 ModTime:2020-08-27 11:51:19.876 +0000 UTC IsCompressed:false IsEncrypted:false}
[debug]	12:17:26 croc.go:234: longestFilename: 5
Sending 'hello' (0 B)
Code is: alamo-sardine-fuel
On the other computer run

croc --relay [2a03:b0c0:2:d0::9a1:2001]:9009 alamo-sardine-fuel
[debug]	12:17:26 croc.go:355: establishing connection to [2a03:b0c0:2:d0::9a1:2001]:9009
[debug]	12:17:26 tcp.go:55: starting with password 'pass123'
[info]	2020/08/27 12:17:26 starting TCP server on 9009
[debug]	12:17:26 tcp.go:55: starting with password 'pass123'
[info]	2020/08/27 12:17:26 starting TCP server on 9010
[debug]	12:17:26 tcp.go:55: starting with password 'pass123'
[info]	2020/08/27 12:17:26 starting TCP server on 9011
[debug]	12:17:26 tcp.go:55: starting with password 'pass123'
[info]	2020/08/27 12:17:26 starting TCP server on 9012
[debug]	12:17:26 tcp.go:55: starting with password 'pass123'
[info]	2020/08/27 12:17:26 starting TCP server on 9013
[debug]	12:17:26 croc.go:358: banner: 
[debug]	12:17:26 croc.go:361: could not connect to [2a03:b0c0:2:d0::9a1:2001]:9009: dial tcp [2a03:b0c0:2:d0::9a1:2001]:9009: connect: connection refused
[debug]	12:17:26 croc.go:418: error from errchan: could not connect to [2a03:b0c0:2:d0::9a1:2001]:9009: dial tcp [2a03:b0c0:2:d0::9a1:2001]:9009: connect: connection refused
[debug]	12:17:27 croc.go:281: establishing connection
[debug]	12:17:27 tcp.go:99: client 127.0.0.1:56486 connected
[debug]	12:17:27 tcp.go:412: strong key: aacfcf67a8fbde264e70f34a79912d7e76a74445bfe57e48c0c8bebff2473a67
[debug]	12:17:27 tcp.go:421: sending password
[debug]	12:17:27 tcp.go:430: waiting for first ok
[debug]	12:17:27 tcp.go:170: strongkey: aacfcf67a8fbde264e70f34a79912d7e76a74445bfe57e48c0c8bebff2473a67
[debug]	12:17:27 tcp.go:179: waiting for password
[debug]	12:17:27 tcp.go:202: sending '9010,9011,9012,9013'
[debug]	12:17:27 tcp.go:213: waiting for answer
[debug]	12:17:27 tcp.go:445: sending room
[debug]	12:17:27 tcp.go:454: waiting for room confirmation
[debug]	12:17:27 tcp.go:244: room ala has 1
[debug]	12:17:27 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:27 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:27 tcp.go:467: all set
[debug]	12:17:27 croc.go:284: banner: 9010,9011,9012,9013
[debug]	12:17:27 croc.go:291: local connection established: &{connection:0xc00000e050}
[debug]	12:17:27 croc.go:297: got ping
[debug]	12:17:28 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:28 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:28 croc.go:297: got ping
[debug]	12:17:29 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:29 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:29 croc.go:297: got ping
[debug]	12:17:30 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:30 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:30 croc.go:297: got ping
[debug]	12:17:31 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:31 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:31 croc.go:297: got ping
[debug]	12:17:32 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:32 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:32 croc.go:297: got ping
[debug]	12:17:33 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:33 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:33 croc.go:297: got ping
[debug]	12:17:34 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:34 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:34 croc.go:297: got ping
[debug]	12:17:35 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:35 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:35 croc.go:297: got ping
[debug]	12:17:36 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:36 tcp.go:116: room: {first:0xc00015a810 second:<nil> opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:false}
[debug]	12:17:36 croc.go:297: got ping
[debug]	12:17:37 tcp.go:99: client [2a03:b0c0:2:d0::9ce:1001]:40632 connected
[debug]	12:17:37 tcp.go:170: strongkey: 5fa9666f445fb2906221218e7be5516f1fa5eec86082ce5ad780a3e81bf10fd1
[debug]	12:17:37 tcp.go:179: waiting for password
[debug]	12:17:37 tcp.go:202: sending '9010,9011,9012,9013'
[debug]	12:17:37 tcp.go:213: waiting for answer
[debug]	12:17:37 tcp.go:261: room ala has 2
[debug]	12:17:37 tcp.go:277: starting pipes
[debug]	12:17:37 croc.go:299: instead of handshake got: ips?
[debug]	12:17:37 tcp.go:108: checking connection of room ala for &{connection:0xc00000e118}
[debug]	12:17:37 tcp.go:116: room: {first:0xc00015a810 second:0xc00015b260 opened:{wall:13819866059458726364 ext:521534193 loc:0x9935e0} full:true}
[debug]	12:17:37 tcp.go:118: rooms ready
```

```
root@croc-receiver:~# croc --debug --relay [2a03:b0c0:2:d0::9a1:2001]:9009 alamo-sardine-fuel
[debug]	12:17:36 cli.go:123: debug mode on
[debug]	12:17:36 croc.go:149: options: {IsSender:false SharedSecret:alamo-sardine-fuel Debug:true RelayAddress:[2a03:b0c0:2:d0::9a1:2001]:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]	12:17:36 croc.go:436: attempt to discover peers
[debug]	12:17:37 croc.go:476: discovery 0 has payload: address: 0.0.0.0, payload: ok
[debug]	12:17:37 croc.go:478: skipping discovery
[debug]	12:17:37 croc.go:492: discoveries: [address: 0.0.0.0, payload: ok]
[debug]	12:17:37 croc.go:493: establishing connection
[debug]	12:17:37 croc.go:505: establishing receiver connection to [2a03:b0c0:2:d0::9a1:2001]:9009
[debug]	12:17:37 tcp.go:412: strong key: 5fa9666f445fb2906221218e7be5516f1fa5eec86082ce5ad780a3e81bf10fd1
[debug]	12:17:37 tcp.go:421: sending password
[debug]	12:17:37 tcp.go:430: waiting for first ok
[debug]	12:17:37 tcp.go:445: sending room
[debug]	12:17:37 tcp.go:454: waiting for room confirmation
[debug]	12:17:37 tcp.go:467: all set
[debug]	12:17:37 croc.go:508: banner: 9010,9011,9012,9013
[debug]	12:17:37 croc.go:514: receiver connection established: &{connection:0xc00000e0d0}
[debug]	12:17:37 croc.go:519: sending ips?
```

And some other times I get the same exact error as the initial post on this issue:
```
root@croc-receiver:~# croc --debug --relay [2a03:b0c0:2:d0::9a1:2001]:9009 partner-fluid-bridge
[debug]	12:15:59 cli.go:123: debug mode on
[debug]	12:15:59 croc.go:149: options: {IsSender:false SharedSecret:partner-fluid-bridge Debug:true RelayAddress:[2a03:b0c0:2:d0::9a1:2001]:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]	12:15:59 croc.go:436: attempt to discover peers
[debug]	12:15:59 croc.go:476: discovery 0 has payload: address: 0.0.0.0, payload: ok
[debug]	12:15:59 croc.go:478: skipping discovery
[debug]	12:15:59 croc.go:492: discoveries: [address: 0.0.0.0, payload: ok]
[debug]	12:15:59 croc.go:493: establishing connection
[debug]	12:15:59 croc.go:505: establishing receiver connection to [2a03:b0c0:2:d0::9a1:2001]:9009
[debug]	12:15:59 tcp.go:412: strong key: fd0d92b2e65bfefd3bb6c89c10092b8c255a7856f643c7633e05e297e0bfd22c
[debug]	12:15:59 tcp.go:421: sending password
[debug]	12:15:59 tcp.go:430: waiting for first ok
[debug]	12:15:59 tcp.go:445: sending room
[debug]	12:15:59 tcp.go:454: waiting for room confirmation
[debug]	12:15:59 tcp.go:467: all set
[debug]	12:15:59 croc.go:508: banner: 9010,9011,9012,9013
[debug]	12:15:59 croc.go:514: receiver connection established: &{connection:0xc00000e0d0}
[debug]	12:15:59 croc.go:519: sending ips?
[debug]	12:15:59 croc.go:528: ips data: 
[error]	2020/08/27 12:15:59 croc.go:531: ips unmarshal error: invalid character '\x01' looking for beginning of value
[debug]	12:15:59 croc.go:581: exchanged header message
securing channel...[debug]	12:15:59 croc.go:593: ready
[debug]	12:15:59 message.go:46: writing pake message
[error]	2020/08/27 12:16:00 compress.go:46: error copying data: unexpected EOF
[debug]	12:16:00 croc.go:816: problem with decoding: unexpected end of JSON input
[debug]	12:16:00 croc.go:618: got error processing: problem with decoding: unexpected end of JSON input
problem with decoding: unexpected end of JSON input
```

I can replicate the same exact errors when trying the commands given by @lpar on this comment: https://github.com/schollz/croc/issues/196#issuecomment-632166611

**Comment by schollz** [comment]
Right, I have an ipv6 address for the public relay so you can try that:

```
> croc --debug --relay "[2604:a880:800:c1::14c:1]:9009" send --no-local SOMEFILE 
```
The example using local ipv6 you linked also doesn't work for me, but it does work for me if I start a local relay and then transfer with:

```
> croc --relay "[::1]:9009" send --no-local croc
```

I just tried creating two ipv6 droplets and was able to transfer files with them using the public relay (the former example):

```
croc --relay [2604:a880:800:c1::14c:1]:9009 miami-plasma-china
Accept 'test.txt' (23 B)? (y/n) y

Receiving (<-[2604:a880:400:d0::1bdf:3001]:38738)
test.txt 100% |████████████████████| (23/23 B, 5.780 kB/s) [0s:0s]
```

If someone else can confirm it works (or doesn't) I can work on adding in the public relay ipv6 address into croc.

**Comment by unixfox** [comment]
> Right, I have an ipv6 address for the public relay so you can try that:
> 
> ```
> > croc --debug --relay "[2604:a880:800:c1::14c:1]:9009" send --no-local SOMEFILE 
> ```

It seems to work for me. Is the relay using the last version of croc?

**Comment by schollz** [comment]
@unixfox Yes, it is the latest: croc version v8.1.0-588e650

That's great. I'll think about how to add connections with ipv6. It could be a special flag, or have it try ipv4 and then ipv6 if ipv4 fails

**Comment by lpar** [comment]
It's probably worth looking at the "[happy eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs)" algorithm, [RFC8305](https://tools.ietf.org/html/rfc8305), that web browsers use to decide whether to use IPv6 or IPv4 on dual-stack systems. In general, IPv6 will be a better bet than IPv4 if you have both, because you won't have to deal with NAT traversal. (Also, latency will be lower.)

**Comment by schollz** [comment]
@Ipar @unixfox can you try the latest master (50bf003022c3b296f6beb18087877ec392342b54) for your ipv6 systems? If you need a build let me know and I can provide.

Public gateway now works in my tests for ipv4 <-> ipv4, ipv6 <-> ipv4, and ipv6 <->ipv6.

It opts for ipv6 first (connection refusal is fast if it doesn't exist) and then goes to ipv4. 

You can still override the relay address with `--relay` with a ipv6 or ipv4 address and it will try to use that address and only that address.

**Comment by lpar** [comment]
Works for me.

**Comment by unixfox** [comment]
It works for me between two DO droplets but not from a my computer to a DO droplet. It get this kind of error on the receiving server:
```
[debug]	19:58:12 cli.go:124: debug mode on
[debug]	19:58:12 croc.go:150: options: {IsSender:false SharedSecret:vodka-chamber-quality Debug:true RelayAddress:142.93.177.120:9009 RelayAddress6:[2604:a880:800:c1::14c:1]:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]	19:58:12 croc.go:453: attempt to discover peers
[debug]	19:58:12 croc.go:493: discovery 0 has payload: address: 0.0.0.0, payload: ok
[debug]	19:58:12 croc.go:495: skipping discovery
[debug]	19:58:12 croc.go:511: discoveries: [address: 0.0.0.0, payload: ok]
[debug]	19:58:12 croc.go:512: establishing connection
[debug]	19:58:12 croc.go:529: got host '2604:a880:800:c1::14c:1' and port '9009'
[debug]	19:58:12 croc.go:531: trying connection to [2604:a880:800:c1::14c:1]:9009
[debug]	19:58:12 comm.go:32: connected to '[2604:a880:800:c1::14c:1]:9009'
[debug]	19:58:12 tcp.go:412: strong key: 1bf3bd4306e2e614cb9f18cdc6d119ec8439032b42e3a6c12deb699edfbe3fad
[debug]	19:58:12 tcp.go:421: sending password
[debug]	19:58:12 tcp.go:430: waiting for first ok
[debug]	19:58:12 tcp.go:445: sending room
[debug]	19:58:12 tcp.go:454: waiting for room confirmation
[debug]	19:58:12 tcp.go:467: all set
[debug]	19:58:12 croc.go:540: banner: 9010,9011,9012,9013
[debug]	19:58:12 croc.go:546: receiver connection established: &{connection:0xc00000e0d8}
[debug]	19:58:12 croc.go:551: sending ips?
[debug]	19:58:12 croc.go:560: ips data: 
[error]	2020/08/27 19:58:12 croc.go:563: ips unmarshal error: invalid character '\x01' looking for beginning of value
[debug]	19:58:12 croc.go:613: exchanged header message
securing channel...[debug]	19:58:12 croc.go:625: ready
[debug]	19:58:12 message.go:46: writing pake message
[error]	2020/08/27 19:58:13 compress.go:46: error copying data: unexpected EOF
[debug]	19:58:13 croc.go:848: problem with decoding: unexpected end of JSON input
[debug]	19:58:13 croc.go:650: got error processing: problem with decoding: unexpected end of JSON input
problem with decoding: unexpected end of JSON input
```

I tested with croc version v8.1.2-2345148.

**Comment by schollz** [comment]
@unixfox are you sure you have the latest version now (v8.1.2)? I can't replicate an error like this. I tried between DO and a work computer and also DO and a home computer and both worked fine (DO always used ipv6, others did ipv4).

**Comment by unixfox** [comment]
I think it's probably a firewall issue because I have another computer directly connected to the Internet with a public IPv6 address and it works.

The thing is that I don't really understand how to fix this issue. My firewall doesn't filter outgoing connections, only inbound.

**Comment by schollz** [comment]
@unixfox that is weird. Does it work with ipv4?

**Comment by unixfox** [comment]
> @unixfox that is weird. Does it work with ipv4?

Yes it is working fine with IPv4.

I can replace the IPv6 issue on two home internet connections (in my student room and my parents's house).

These two connections have a firewall on the internet box which disallow the ability to reach any port that would be opened on the IPv6 address.
