### ISSUE TITLE
Can't get socat/Tor connection working with croc on the receiving side

### ISSUE THREAD

**Issue by sac001** [schollz/croc#199]
While using a socat/Tor set-up described at torproject.org on a Linux machine, to receive a small file, croc erros out.

I am using the authors public relay for the test.

croc version v6.4.11-bc0841d

socat TCP4-LISTEN:5870,bind=127.0.0.1,fork SOCKS4A:localhost:142.93.XXX.XXX:9009,socksport=9050

croc --debug --relay localhost:5870 abcdef
[debug] 18:44:49 cli.go:123: debug mode on
[debug] 18:44:49 croc.go:149: options: {IsSender:false SharedSecret:abcdef Debug:true RelayAddress:localhost:5870 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]    18:44:49 croc.go:418: attempt to discover peers
[debug] 18:44:50 croc.go:442: discoveries: []
[debug] 18:44:50 croc.go:443: establishing connection
[debug] 18:44:50 croc.go:449: establishing receiver connection to localhost:5870
[debug] 18:44:50 tcp.go:313: sending password
[debug] 18:44:50 tcp.go:318: waiting for first ok
[debug] 18:44:50 tcp.go:329: sending room
[debug] 18:44:50 tcp.go:334: waiting for room confirmation
[debug] 18:44:51 tcp.go:343: all set
[debug] 18:44:51 croc.go:452: banner: 9010,9011,9012,9013
[debug] 18:44:51 croc.go:457: receiver connection established: &{connection:0xc0004b0008}
[debug] 18:44:51 croc.go:462: sending ips?
[debug] 18:44:51 croc.go:469: ips data: ["9009","169.254.48.208","169.254.68.99","192.168.178.26","169.254.85.220","169.254.222.90"]
[debug] 18:44:51 croc.go:477: ipv4Add4: 169.254.48.208, ipv4Net: 169.254.48.0/24, err: <nil>
[debug] 18:44:51 croc.go:488: 169.254.48.208 is not a local IP, skipping
[debug] 18:44:51 croc.go:477: ipv4Add4: 169.254.68.99, ipv4Net: 169.254.68.0/24, err: <nil>
[debug] 18:44:51 croc.go:488: 169.254.68.99 is not a local IP, skipping
[debug] 18:44:51 croc.go:477: ipv4Add4: 192.168.178.26, ipv4Net: 192.168.178.0/24, err: <nil>
[debug] 18:44:51 tcp.go:313: sending password
[debug] 18:44:51 tcp.go:318: waiting for first ok
[debug] 18:44:51 tcp.go:329: sending room
[debug] 18:44:51 tcp.go:334: waiting for room confirmation
[debug] 18:44:51 tcp.go:343: all set
[debug] 18:44:51 croc.go:498: local connection established to 192.168.178.26:9009
[debug] 18:44:51 croc.go:499: banner: 9010,9011,9012,9013
[debug] 18:44:51 croc.go:518: exchanged header message
securing channel...[debug]      18:44:51 croc.go:530: ready
[debug] 18:44:51 message.go:31: writing pake message (729 bytes)
[debug] 18:44:51 croc.go:552: got error processing: unexpected end of JSON input
unexpected end of JSON input

**Comment by schollz** [comment]
Can you try with the latest version?

**Comment by sac001** [comment]
Appologies, I currently have no spare VPS to install croc again. I may do however soon a test with your public server and report back here, once time permits.
