### ISSUE TITLE
`croc --version` reports wrong version when compiled from `_src.tar.gz`

### ISSUE THREAD

**Issue by maximbaz** [schollz/croc#202]
FYI, I'm building `croc` from `_src.tar.gz` for Arch Linux users, and I noticed that `croc --version` reports wrong version.

`8.0.1` archive reports `croc version v8.0.0-0c305fe`
`8.0.2` archive reports `croc version v8.0.1-2d6206b`

I think it happens because you tagged commits before the version bump:

![image](https://user-images.githubusercontent.com/1177900/76141678-d97d0000-6066-11ea-9e5b-79828ae0b216.png)

No need to immediately make a new release, just know that in the current release `croc --version` is unreliable.

**Comment by maximbaz** [comment]
Seems like this hasn't been an issue in the past few releases, do you want to close this, or do you want to use this as an opportunity to try to rethink how to handle versioning differently? One idea can be that a version is never committed by you manually, but your CI generates it, e.g. in code you have version string set as `development`, but CI would `sed` it to an actual value. Let me know if you want to discuss / brainstorm more!

**Comment by schollz** [comment]
@maximbaz I love the idea of the CI generating it, I can leave this open for figuring that out.

For the record, this is what I'm doing now to create a release. Pushing after tagging seems to fix this particular issue.

```
git clone https://github.com/schollz/croc && cd croc
VERSION=8.X.Y go generate
git push # push before the release!
goreleaser release
VERSION=8.X.Y ./src/install/prepare-sources-tarball.sh
./src/install/upload-src-tarball.sh
```

I think `goreleaser` now accepts any uploads for Github so when I have time one day I'll look into automating that. I be there's a way to make Travis.CI toggle goreleaser, but I haven't figured that out yet.

As always, totally open to suggestions/PRs.

**Comment by equirosa** [comment]
> Seems like this hasn't been an issue in the past few releases[...]

Hi! Came here to report that version 8.2.0 (latest as of 2020/9/2) also mistakenly reports the version being `v8.1.3-2096751`.  This isn't a particularly heavy issue, but I thought it might be worth reporting its prevalence.

I'll look into a way to fix it as soon as I get some free time. :smile: 

Context: I was updating the package definition for croc in [nixpkgs](https://github.com/NixOS/nixpkgs) and this came up as I was testing the newer options.

**Comment by schollz** [comment]
This should be fixed now
