### ISSUE TITLE
Croc does freezes near the end of the transfer

### ISSUE THREAD

**Issue by lhcamilo** [schollz/croc#203]
**Describe the bug**

The transfer freezes near the end. At about 80-98%

**To Reproduce**
Send a file. In this case I am sending a 50MB log file across my local lan

**Expected behavior**

I would expect it to finish the transfer

**Version**

 v8.0.1-074a869

**Additional context**

Additionally, the "curl https://getcroc.schollz.com | bash" command, (that I use to update croc), does not seem to be working

**Comment by schollz** [comment]
Thanks. DO restarted my droplet so the `https://getcroc.schollz.com` should be back up.

Can you try with the latest version?

If it is reproducible, can you add `--debug` and share the output?

**Comment by lhcamilo** [comment]
The curl command seems to work now. I have updated croc to the latest version.

It seems that the update has solved whatever issue was there.
