### ISSUE TITLE
Unexpected end of JSON Input

### ISSUE THREAD

**Issue by changwuf31** [schollz/croc#206]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**
Unable to receive file if the client is not using the same version as server

**To Reproduce**
1. Use croc v8.0.1 and send a file
2. Use croc v8.0.4 and recevie the file
3. Got error

**Expected behavior**
Able to receive the file with different croc version

**Version**
8.0.1 on the server
8.0.4 on the client

**Additional context**
the server does not have any error
the client, the error is
```
[debug] 03:05:42 cli.go:123: debug mode on
[debug] 03:05:42 croc.go:149: options: {IsSender:false SharedSecret:xxx-yyy-zzz Debug:true RelayAddress:142.93.177.120:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]    03:05:42 croc.go:422: attempt to discover peers
[debug] 03:05:42 croc.go:446: discoveries: []
[debug] 03:05:42 croc.go:447: establishing connection
[debug] 03:05:42 croc.go:453: establishing receiver connection to 142.93.177.120:9009
[debug] 03:05:42 tcp.go:404: strong key: 1a4cecfea1c3983e5e084f5bb3498b9d3628d44ffd28904cbb0c5ea4e7967b4a
[debug] 03:05:42 tcp.go:413: sending password
[debug] 03:05:42 tcp.go:422: waiting for first ok
[debug] 03:05:43 tcp.go:437: sending room
[debug] 03:05:43 tcp.go:446: waiting for room confirmation
[debug] 03:05:43 tcp.go:459: all set
[debug] 03:05:43 croc.go:456: banner: 9010,9011,9012,9013
[debug] 03:05:43 croc.go:461: receiver connection established: &{connection:0xc00000e008}
[debug] 03:05:43 croc.go:466: sending ips?
[debug] 03:05:43 croc.go:473: ips data:
[debug] 03:05:43 croc.go:522: exchanged header message
securing channel...[debug]      03:05:43 croc.go:534: ready
[debug] 03:05:43 message.go:46: writing pake message
[debug] 03:05:44 croc.go:559: got error processing: problem with decoding: unexpected end of JSON input
problem with decoding: unexpected end of JSON input
```

**Comment by schollz** [comment]
The authentication is improved now in https://github.com/schollz/croc/releases/tag/v8.0.2, so your server needs to be at least 8.0.2.

**Comment by changwuf31** [comment]
Great, issue solved by upgrading to 8.0.2
Thank you for the great tool 

    Pada Jumat, 27 Maret 2020 21.13.17 GMT+7, Zack <notifications@github.com> menulis:  
 
 


The authentication is improved now in https://github.com/schollz/croc/releases/tag/v8.0.2, so your server needs to be at least 8.0.2.

**Comment by RoseTheFlower** [comment]
Using 8.0.4 on both ends, I'm getting the same issue on the client side on Windows.

**Comment by tomamplius** [comment]
Same issue in v8.0.7-e56e652 in the both side server / client
