### ISSUE TITLE
add --code in croc help

### ISSUE THREAD

**Issue by bcag2** [schollz/croc#207]
If I run `croc help`, there is nothing about `--code` option you explain at https://github.com/schollz/croc#custom-code-phrase

**Version**
with croc version v8.0.4-7a605dd (fresh snap install under ubuntu)

**Comment by schollz** [comment]
Since the argument is only for `send` it appears under send: `croc send --help`.

I realize this is confusing because of the subcommand, maybe all the argumnets should be under the main command, and no sub commands?

**Comment by bcag2** [comment]
ok, the first tool which could work like that: git  
_git help_ return sub-command and _git sub-command --help_ return sub-command help
thank for this nice tool
