### ISSUE TITLE
Add an option to send multiple times the same files

### ISSUE THREAD

**Issue by lord-re** [schollz/croc#208]
Sometimes i want to share a file to everybody (yes even you), so i'd like **being able to launch "croc send /the/file" and having the file being shared multiple times**
That way it could act as a small file server.

**Add an option to croc send to put croc in a server mode to serve multiple times the file.**

**I use a while loop to approach this behavior except it can't share the file more than once at a time**
It's a poorman's solution actually but it works.

It could eventually be completed with an option to daemonize it.

**Comment by schollz** [comment]
The poorman's solution should serve you well. Unfortunately to add this into croc it would require some re-write because only two parties are able to exchange at a time. I'll leave it open though if I get an idea of how to do it.
