### ISSUE TITLE
Default behavior: disconnect unless sender is available

### ISSUE THREAD

**Issue by schollz** [schollz/croc#21]
But this behavior could be changed to sitting until someone connects (what it is now) with `-wait`

**Comment by lummie** [comment]
I'll have a look

**Comment by schollz** [comment]
Awesome. Basically the idea is that if you type the wrong code phrase, and you expect someone to send you a file then it will disconnect (after a time delay to make it harder for attackers to just spam the relay server).

**Comment by lummie** [comment]
oh so server side, rather than a client side -wait flag?

**Comment by lummie** [comment]
So how about we adapt the potentialReceivers map to store the connection and time it connected.
Then every 30 seconds iterate this map and throw away anything that's been there longer than 1 minute?

Or other time interval that you'd like...

**Comment by Lunsford94** [comment]
I had meant to take this up, but wanted to actually have everything before claiming it.

I've just made a pull request with the changes, but they're lacking any 'time delay'; I can add that as well, assuming they're good.

**Comment by lummie** [comment]
@Lunsford94 go ahead and finish of :+1:

**Comment by schollz** [comment]
Yeah @Lunsford94 yours looks perfect. I would just add a time.Sleep. I made a note in the code review.
