### ISSUE TITLE
Sending a whole directory results in EOF error

### ISSUE THREAD

**Issue by afontenot** [schollz/croc#212]
**Describe the bug**
When trying to send a folder between two computers on the same subnet, I get 2-3 different errors, seemingly at random. Here are two:

This one hangs up before the download even starts:

    [debug]	20:06:12 croc.go:551: got error receiving: EOF
    could not secure channel

On the sender end, my terminal gets spammed with hundreds of thousands of the following line until I ctrl-c (likely, anything useful is lost somewhere in the buffer):

    [debug] 20:06:24 croc.go:294: instead of handshake got:

This one successfully starts downloading, but gets an EOF after (or while?) the first file is downloaded, and dies. The rest of the files do not download:

    IMG_7253.dng    25% |█████               | (17.693 MB/s) [0s:0s][debug]	20:06:45 croc.go:551: got error receiving: EOF
    EOF

I also once or twice got a error about invalid JSON, but that might have been when I was using an old version of croc on the receiver end. Haven't been able to replicate it recently.

**Expected behavior**
I expect all the files to be sent correctly.

**Version**
Sender and receiver: croc version v8.0.7-e56e652

**Additional context**
Sender is Arch Linux with latest distribution package. Receiver is macOS with croc from Homebrew.

Sending the same folder with magic-wormhole between the same two computers works fine, it's just very slow because Wormhole zips up the files before sending them. (I would also like to avoid using it if possible because it's not in the Arch Linux repositories, and has some quirks / flaws I've run into.)

I disabled the firewall on the Arch Linux system for this test specifically to rule out that as a cause. The macOS system is running with whatever the default options are, which are presumably expected to work. Both systems have working IPv4 and IPv6 connections to the Internet.

**Logs**

[croc1.log](https://github.com/schollz/croc/files/4513644/croc1.log)
[croc2.log](https://github.com/schollz/croc/files/4513645/croc2.log)

**Comment by schollz** [comment]
This is strange. Thanks for the logs, I don't see any red flags. I wish I could replicate your system. Would you be interested in bisecting between the latest master and v8.0.0 to see if it's a new issue? There have been a few more reports of issues than usual lately and I'm not personally seeing any problems (I use croc several times a day, everyday). Bisecting might reveal somethinf

**Comment by afontenot** [comment]
I bisected it as far as the individual releases, just downloading the binaries. Looks like it starts with 8.0.6, so most likely https://github.com/schollz/croc/commit/9c0bc3efc334a439ff2c4a913849683dfab53ead is responsible. Probably that 10 second read deadline is getting triggered unexpectedly.

My impression is that how far I get into the download depends on how fast I can type the code on the other computer. If I'm very fast I can download all of the first file and part of the second one before I get EOF. From repeated testing it looks like the sender is the one hanging up on the connection. 

Note that with older releases I frequently get the following two errors:

    securing channel...could not secure channel

and 

    securing channel...problem with decoding: unexpected end of JSON input

The latter seems to occur if the receiver dies but the sender doesn't, and I try again with the same passcode. I get to the EOF point pretty consistently when I'm on the latest version.

**Comment by schollz** [comment]
Okay I just pushed this: https://github.com/schollz/croc/commit/cb522f2f06ce1901f3d8392f96af649c2057fc84 which adds debugging statements to the comm. They should fire if it is a timeout problem. Could you try running with this version for everything?

**Comment by afontenot** [comment]
Sure, I'll just need to figure out how to set up an environment on the macOS system. It's not my normal OS, and Go isn't my normal language, but I'll give it a try.

**Comment by afontenot** [comment]
Okay, so this is weird. Latest git works fine. Maybe you fixed it in https://github.com/schollz/croc/commit/3ed036b51db13c00f90cdef1f2f74e3c02359dc2? 

If that doesn't make clear what the problem is to you and you still want to know, I can apply your debugging changes on top of 8.0.7 and try again.

**Comment by schollz** [comment]
THanks. Yeah someone else had a very similar problem to you and https://github.com/schollz/croc/commit/3ed036b51db13c00f90cdef1f2f74e3c02359dc2 fixed it too. I don't get why only a subset of people get this, but I'll push a new version with that so you don't need to install a Go ecosystem lol. Try it out, let me know if anything goes wrong

**Comment by afontenot** [comment]
I think you'll find this interesting: that change actually *does not* fix the problem. I cherry picked every change except https://github.com/schollz/croc/commit/97f7f28f6e5fcfa26fbcabc8af4ffd500c3cd2bd and *that* is the one that solves it for me.

Here's the resulting log on the sender side, which is always the one to hang up:

```
[debug] 19:57:59 tcp.go:99: client 10.0.1.108:62419 connected
[debug] 19:57:59 tcp.go:170: strongkey: 8b8af44c4b5574c0f450b7190ddd1182d91fa23fb24e9892daf60bf8bb1f7952
[debug] 19:57:59 tcp.go:179: waiting for password
[debug] 19:57:59 tcp.go:200: sending '9010,9011,9012,9013'
[debug] 19:57:59 tcp.go:211: waiting for answer
[debug] 19:57:59 tcp.go:259: room gri has 2
[debug] 19:57:59 tcp.go:275: starting pipes
[debug] 19:57:59 tcp.go:333: read tcp [::1]:9009->[::1]:49972: i/o timeout
[debug] 19:57:59 tcp.go:338: exiting
[debug] 19:57:59 tcp.go:278: done piping
[debug] 19:57:59 tcp.go:304: deleting room: gri
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 tcp.go:108: checking connection of room gri for &{connection:0xc000010030}
[debug] 19:57:59 tcp.go:112: room is gone
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 tcp.go:333: read tcp 10.0.1.109:9009->10.0.1.108:62419: use of closed network connection
[debug] 19:57:59 tcp.go:338: exiting
[debug] 19:57:59 comm.go:86: initial read error: EOF
[debug] 19:57:59 comm.go:86: initial read error: EOF
```

**Comment by schollz** [comment]
Lol wow. That is weird.

Perhaps it was a change in the golang.org/x/sys, maybe this: https://github.com/golang/sys/commit/1957bb5e6d1f523308b49060df02171d06ddfc77 which fixed it for you? This is getting pretty deep

**Comment by afontenot** [comment]
I'm going to try a few more things, it's possible I made a mistake...

**Comment by schollz** [comment]
I really don't know...the default timeout maybe is different for different operating systems? Its very strange.

I pushed a new version, let me know if everything is working again or not
