### ISSUE TITLE
Error: unexpected end of JSON

### ISSUE THREAD

**Issue by dasnolojy** [schollz/croc#213]
Trying to transfer file on a LAN. Both wondows 10 machines with 8.0.7 version launched. File about 300 Mb.

>croc --debug split-spray-mambo

[debug] 17:35:58 cli.go:123: debug mode on
[debug] 17:35:58 croc.go:149: options: {IsSender:false SharedSecret:split-spray-mambo Debug:true RelayAddress:142.93.177.120:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false}
connecting...[debug]    17:35:58 croc.go:422: attempt to discover peers
[debug] 17:35:58 croc.go:446: discoveries: []
[debug] 17:35:58 croc.go:447: establishing connection
[debug] 17:35:58 croc.go:453: establishing receiver connection to 142.93.177.120:9009
[debug] 17:35:58 tcp.go:404: strong key: 8512617e7a17d4da979a2d338a859ac72f816d4cdfbedebf3383269dfbec41c5
[debug] 17:35:58 tcp.go:413: sending password
[debug] 17:35:58 tcp.go:422: waiting for first ok
[debug] 17:35:59 tcp.go:437: sending room
[debug] 17:35:59 tcp.go:446: waiting for room confirmation
[debug] 17:35:59 tcp.go:459: all set
[debug] 17:35:59 croc.go:456: banner: 9010,9011,9012,9013
[debug] 17:35:59 croc.go:461: receiver connection established: &{connection:0x1377a058}
[debug] 17:35:59 croc.go:466: sending ips?
[debug] 17:35:59 croc.go:473: ips data: ☺
[debug] 17:35:59 croc.go:522: exchanged header message
securing channel...[debug]      17:35:59 croc.go:534: ready
[debug] 17:35:59 message.go:46: writing pake message
[debug] 17:36:00 croc.go:559: got error processing: problem with decoding: unexpected end of JSON input
problem with decoding: unexpected end of JSON input

**Comment by schollz** [comment]
Can you try the latest version? I just pushed one with some fixes for others

**Comment by dasnolojy** [comment]
Thank you for the fastest fix in my life ,)
