### ISSUE TITLE
Did you mean to send ... ?(y/n) - "No" is not handled correctly 

### ISSUE THREAD

**Issue by dnlbrg** [schollz/croc#214]
croc still tries to establish a connection.
an os.Exit(1) before the return on line 100 cli.go does the job for me.

**Comment by schollz** [comment]
Can you detail the scenario that this is problematic?

My reasoning for the current logic is this: You send a file with `croc send somefile`. Sometimes people forget to write "send" and they write `croc somefile`. Those people would answer "y". Sometimes, also, people use a custom codephrase with the name of the file like, `croc send --code somefile somefile`. In this case the recipient might also write `croc somefile` and might have `somefile` on their disk, in which case they can answer "No" and still receive the file.

**Comment by dnlbrg** [comment]
Ah okay, I see. I forgot it too.  My fault 🙈 so you can close the "issue".
Sorry!

Great job btw

Zack <notifications@github.com> schrieb am Do., 30. Apr. 2020, 18:35:

**Comment by schollz** [comment]
Thanks, please don't hesitate to let me know if you find any other issues or have questions.

**Comment by dnlbrg** [comment]
My intention was to end the program and not to continue receiving. But your
explanation makes sense.

Zack <notifications@github.com> schrieb am Do., 30. Apr. 2020, 18:35:
