### ISSUE TITLE
Incorrect status of recevied file

### ISSUE THREAD

**Issue by maxtar** [schollz/croc#215]
**Describe the bug**
On received side status 99%.

**To Reproduce**
1. Run command `croc send <file_name>`. File size 70 Mb.
2. Start receives file on other side.
3. Wait while file received.
4. After done see the following status:
![изображение](https://user-images.githubusercontent.com/10290098/81286213-5decfe80-9069-11ea-9f37-1b6229c35c21.png)

**Expected behavior**
Status show 100% progress, and message about `File(s) received successfully`.

**Version**
v8.0.10-6dc44ec

**Comment by schollz** [comment]
@maxtar That's strange..is it reproducible with other files?

**Comment by maxtar** [comment]
@schollz I will try.

**Comment by maxtar** [comment]
Hm, I've tried one more time. And it not reproduced. But First time was another server side with slow connection. I think may close now. I will reopen if repeated.
