### ISSUE TITLE
Issues sending data over custom relay using a custom port

### ISSUE THREAD

**Issue by ElMostafaIdrassi** [schollz/croc#216]
**Describe the bug**
I have a croc relay setup on a random port, let's say 8000, on a machine running Ubuntu 18.04 Server.
I cannot send files via the relay from a client running on Window 10 to another client running on Ubuntu 18.04.

**To Reproduce**
1. Run the server using `croc --debug --pass "YOURPASSWORD" relay --ports 8000`
2. Send file from client 1 using `croc --debug --pass "YOURPASSWORD" --relay "DOMAIN:8000" send <file>`
3. Receive the file on client 2 using `croc --debug --pass "YOURPASSWORD" --relay DOMAIN:8000 <code>`

**Expected behavior**
File is received properly from client 1 to client 2.

**Version**
croc version v8.0.10-6dc44ec

**Additional context**
[Server logs](https://gist.github.com/ElMostafaIdrassi/0909ec6b2b20d6051f3be7d36d35e574)
[Client 1 logs](https://gist.github.com/ElMostafaIdrassi/30dcb8e0c45d7627d4bd50ceb01db008)
[Client 2 logs](https://gist.github.com/ElMostafaIdrassi/cd4be38c17a76fab5a24413b79f626e1)

**Comment by schollz** [comment]
Thanks! This isn't documented well. You will actually need at least **2** ports for your relay to function.

Try this:

Relay:

```
croc --debug --pass "YOURPASSWORD" relay --ports 8000,8001
```

Sender:

```
croc --debug --pass "YOURPASSWORD" --relay "DOMAIN:8000" send <file>
```

Receiver:

```
croc --debug --pass "YOURPASSWORD" --relay DOMAIN:8000 <code>
```


The first port (`8000`) handles connections of clients. The subsequent ports (`8001`) handles the data transfer. For *slightly* faster data transfer you can also include a few more subsequent ports. For instance `--ports 8000,8001,8002,8003,8004` will multiplex the data transfer between ports 8001 and 8004.

**Comment by makeworld-the-better-one** [comment]
Could you add this to the README?

**Comment by schollz** [comment]
@makeworld-the-better-one will do

**Comment by schollz** [comment]
Done! https://github.com/schollz/croc/commit/91468709aa8aab7ba3f970b58331ab634e5d8503

**Comment by ElMostafaIdrassi** [comment]
Thanks for the info and for updating the README. Closing the issue.
