### ISSUE TITLE
Able to send files via private relay without using --pass flag 

### ISSUE THREAD

**Issue by nbgibson** [schollz/croc#219]
**Describe the bug**
The --pass flag is not required to send files via private relay.

**To Reproduce**
1. Set up relay on remote server using the schollz/croc container
2. Start container with a given password assigned to CROC_PASS
3. Send file via croc using the --relay flag and no --pass flag
4. Target client executes the receive command and transfer begins

**Expected behavior**
Error to be passed to the sender due to lack of/incorrect password supplied for the target relay. It appears that --pass puts the onus on the person receiving the file and more or less functions as a second pass phrase.

**Version**
croc version v8.0.11-78b6437

**Additional context**
I don't know if it's a client or a docker container thing, but my understanding was that the person doing the sending would need the appropriate pass to be able to leverage a given relay. It's possible that the instances using the relay with the pass are failing over to a public relay, but if that's happening it's not being surfaced.

**Comment by schollz** [comment]
I followed your instructions and ran docker:

```
> docker run -p 9009:9009 -p 9010:9010 -p 9011:9011 -p 9012:9012 -p 9013:9013 -e CROC_PASS='yoyo' schollz/croc
```

and then connected with:

```
> ./croc --relay localhost send --no-local croc
Sending 'croc' (8.3 MB)
Code is: XXX
On the other computer run

croc --relay localhost zack
could not connect to localhost: incorrect passphrase
```

and it works as expected.

Did you test your case on a local network? if so, it probably used the local connection as the backup connection. It should never use the public relay as a backup connection.

**Comment by nbgibson** [comment]
Whoops, I totally forgot about this. It's a bit moot now, but to answer your question this was on a VPS outside of my LAN. I'll have to try it again sometime on a more recent version to see if it's still acting weird.
