### ISSUE TITLE
Quit the program if the file specified already exists

### ISSUE THREAD

**Issue by schollz** [schollz/croc#22]
When the receiver gets the filename (here: https://github.com/schollz/croc/blob/master/connect.go#L208-L215), have it exit the program and print "Will not overwrite file!" if a file with that name already exists.

**Comment by techtide** [comment]
Alright, I can do this!

**Comment by schollz** [comment]
Great, thanks @techtide ! I think its better just to exit and have the recipient backup their own files however they wish.

**Comment by techtide** [comment]
Okay; what I've implemented was basically just a slice with all accepted file names, and if a file is being pushed again that has already been accepted with a file name, then triggering the exit and the error message.
