### ISSUE TITLE
getcroc.schollz.com seems to be down

### ISSUE THREAD

**Issue by lhcamilo** [schollz/croc#220]
curl times out when  doing:

    curl https://getcroc.schollz.com | bash

Maybe the server needs to be restarted

**Comment by schollz** [comment]
@lhcamilo thanks should be up now!

**Comment by lhcamilo** [comment]
Hmmm, weird, curl still times out... 
Maybe something may be wrong with openSSL?

**Comment by schollz** [comment]
Sorry about that. That website is run along with dozens of other websites on one droplet. Right now its getting a ton of traffic for another website and seems to be pulling down everything else with it sometimes...I fixed it again (I think) but it should go back to normal soon

**Comment by lhcamilo** [comment]
No worries, it seems to work now. :D
