### ISSUE TITLE
PAKE panic with IPv6 hosts

### ISSUE THREAD

**Issue by jpds** [schollz/croc#224]
**Describe the bug**

I have a private relay, which is listening on IPv6, and two clients connected to this relay via a private VPN.

**To Reproduce**

1. I run:

`./croc --relay [2a01:XXXX:YYYY:ZZZZ::6]:9009 send test`
`./croc --relay [2a01:XXXX:YYYY:ZZZZ::6]:9009 <code>`

2. Receive:

```
securing channel...panic: dial tcp: address [2a01:9013: missing ']' in address

goroutine 24 [running]:
github.com/schollz/croc/v8/src/croc.(*Client).procesMesssagePake.func1(0xc000015570, 0xc0000aa780, 0xc000082b00, 0x3)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:675 +0x533
created by github.com/schollz/croc/v8/src/croc.(*Client).procesMesssagePake
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:665 +0x272
```

Important to note that the `9013` reported in the address is NOT what's set in the `XXXX` part of the address.

**Version**

```
croc version v8.0.11-78b6437
```

**Comment by schollz** [comment]
@jpds croc doesn't work with ipv6 (https://github.com/schollz/croc/issues/196)

I can't develop croc for ipv6 because I don't have any ipv6 machines. If someone can assist with a PR I'll happily accept.

**Comment by jpds** [comment]
Hi @schollz, I had seen that bug but this one is slightly different.

I know of three options you can use if you don't have a native IPv6 connection:

1) [Yggdrasil](https://yggdrasil-network.github.io/) - you download the go binary, configure a [public peer](https://github.com/yggdrasil-network/public-peers), run it and every machine you add to the network is assigned a unique IPv6 address

2) Amazon EC2, you can [enable IPv6 on a VPC](https://docs.aws.amazon.com/vpc/latest/userguide/get-started-ipv6.html) and spin up three small EC2 instances in that VPC

3) Use the link-local addresses on your private network, if you do `ip -6 a` in a terminal, you'll see addresses like:

`inet6 fe80::e3f9:5572:XXX:YYY/64 scope link noprefixroute`

These are also valid IPv6 addresses.

**Comment by maximbaz** [comment]
As yet another alternative, connect to Cloudflare's Warp network via Wireguard and they will assign an internet-visible ipv6 address for you; should be as simple as generating `.conf` file using [this tool](https://github.com/ViRb3/wgcf) and then connecting using `wg-quick`.

**Comment by schollz** [comment]
pinging this issue to let you know that a possibly compatible ipv6 release is out: https://github.com/schollz/croc/releases/tag/v8.1.0

@jpds  if you want, try it out and let me know if you run into problems
