### ISSUE TITLE
OpenPGP / gpg signed git tags for source code

### ISSUE THREAD

**Issue by adrelanos** [schollz/croc#225]
Can you please OpenPGP sign your future git tags? It's also useful in case github [gets hacked](http://www.extremetech.com/computing/120981-github-hacked-millions-of-projects-at-risk-of-being-modified-or-deleted) again in case [SSL CA's](https://en.wikipedia.org/wiki/DigiNotar) get [hacked](http://www.scmagazine.com/two-more-comodo-resellers-owned-in-ssl-hack/article/199620/) again.

With git it requires minimal effort.

In my ~/.gitconfig I use.

```
[user]
         name = adrelanos
         email = adrelanos at riseup dot net
         signingkey = 713AAEEF
```

After setting that up you can just use.

```
git tag -s 1.9
```

Users who wish can verify it with.

```
git tag -v 1.9
```

I am using it all the time. If there are any questions about this git feature / feature request, I am happy to answer.

**Comment by maximbaz** [comment]
If you start doing this, a PGP signature for `_src.tar.gz` would be highly appreciated too, for the purpose of secure distro packaging 🙂 I can help with that if needed.

**Comment by adrelanos** [comment]
> @[schollz](https://github.com/schollz) schollz closed this as [completed](https://github.com/schollz/croc/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [5 days ago](https://github.com/schollz/croc/issues/225#event-12362958616)

This is misleading.

```
git tag -v v9.6.9      
error: v9.6.9: cannot verify a non-tag object of type commit.
```
