### ISSUE TITLE
Add a way to provide the password to croc relay through a file

### ISSUE THREAD

**Issue by ju1m** [schollz/croc#226]
**Is your feature request related to a problem? Please describe.**
Unless the OS is hardened, all users can see the arguments of other users' commands.
Hence using `--pass $password` is not wise from a security point of view.

**Describe the solution you'd like**
`croc relay` could read a `relay.json`.

**Describe alternatives you've considered**
`croc` does not seem to read `receive.json` nor `send.json` in relay mode.

**Additional context**
Feature requested on NixOS' `services.croc`: https://github.com/NixOS/nixpkgs/pull/93629#discussion_r459048662

Thanks for `croc`.

**Comment by schollz** [comment]
when including `--pass YOURPASSWORD` you can instead pass a file with the password, e.g. `--pass FILEWITHPASSWORD`.
