### ISSUE TITLE
too many bytes: 1765281

### ISSUE THREAD

**Issue by piegamesde** [schollz/croc#231]
**Describe the bug**
I tried to send a huge folder (`Sending 6122 files (11.3 GB)`) and receiving it fails

**To Reproduce**
1. croc send MyHugeFolder
2. croc password

**Expected behavior**
The files transfer correctly

**Version**
croc version v8.1.1-e250eee

**Additional context**
I'm using the Arch Linux package. Relevant log lines:

```
[debug]	11:42:52 message.go:43: writing externalip message (encrypted)
[debug]	11:42:52 comm.go:117: too many bytes: 1765281
[debug]	11:42:52 croc.go:642: got error receiving: too many bytes: 1765281
too many bytes: 1765281
```

**Comment by schollz** [comment]
@piegamesde Thanks. This is an easy fix. Right now I have a limit on the max bytes in the comm just in case someone wants to send some garbage into the relay server. The relay server interprets the header and if its garbage it will see a crazy huge number there. However in your case the number is real. I'll bump it up to 4000000 and it should be okay.

**Comment by whytheheckme** [comment]
Hello, I'm running into this issue today trying to transfer a 2TB folder.

**Comment by schollz** [comment]
@whytheheckme what version are you using? and can you estimate the largest file in your 2TB folder? the byte level may need to be upped again. folder size itself shouldn't matter though, only the biggest file

**Comment by whytheheckme** [comment]
Wow, thanks for the fast reply! The largest file I noticed on inspection was 80GB, but there could be larger. I'm attempting to move raw video files between a field shoot location and a datacenter easily. Thanks for all you do!

**Comment by schollz** [comment]
Did you get that error the first time you tried transferring? Or on a subsequent try? I'm thinking that maybe it came up because of trying to sync the blocks (which is sent in one packet...which is almost always enough....except when you transfer 80gb maybe).

**Comment by piegamesde** [comment]
@schollz How about fixing this issue in a more sustainable way? "Is this number reasonably small?" is not a good sanity check to tell if a client is legit or sending random bullshit. How about removing that MAX_BYTES limit altogether and instead add some other sanity checks? (Magic bytes, checksums, etc.)

Besides, the length of the transfer is some metadata the server should not care (or even know) about.

**Comment by schollz** [comment]
@piegamesde You're right. I think its time to use magic bytes.

**Comment by IceCodeNew** [comment]
```
Sending 80506 files (24.7 GB)
```

```
securing channel...too many bytes: 15089399
```
