### ISSUE TITLE
problem with decoding: unexpected end of JSON input

### ISSUE THREAD

**Issue by piegamesde** [schollz/croc#232]
**Describe the bug**
I get `problem with decoding: unexpected end of JSON input` when trying to send files.

**To Reproduce**
1. Get a shell with `croc` in PATH (see below)
2. Send and receive a file or folder, preferably on the machine itself

**Expected behavior**
It just works

**Version**
croc version v8.1.1-e250eee

Get a shell with that version installed using: `NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/c4364cdddc421dfdb4a60fda38ed955abce1603a.tar.gz nix-shell -p 'with (import<nixpkgs>{});buildGoModule rec {pname = "croc";version = "8.1.2";src = fetchFromGitHub {owner = "schollz";repo = pname;rev = "v${version}";sha256 = "0m7kgfmdbmz0r0dydz7j9cllp77076qgdcmkw3jnrsj169f5acfa";};vendorSha256 = "1fjv4y7pkwd4wsq3y66r75gr0makhjcdf0i3cpxgv03x5ahkf16b";doCheck = false;subPackages = [ "." ];}'`

**Additional context**

```
[debug]	21:18:34 tcp.go:421: sending password
[debug]	21:18:34 tcp.go:430: waiting for first ok
[debug]	21:18:34 tcp.go:445: sending room
[debug]	21:18:34 tcp.go:454: waiting for room confirmation
[debug]	21:18:35 tcp.go:467: all set
[debug]	21:18:35 croc.go:540: banner: 9010,9011,9012,9013
[debug]	21:18:35 croc.go:546: receiver connection established: &{connection:0xc0003b4010}
[debug]	21:18:35 croc.go:551: sending ips?
[debug]	21:18:35 croc.go:560: ips data: 
[error]	2020/08/31 21:18:35 croc.go:563: ips unmarshal error: invalid character '\x01' looking for beginning of value
[debug]	21:18:35 croc.go:613: exchanged header message
securing channel...[debug]	21:18:35 croc.go:625: ready
[debug]	21:18:35 message.go:46: writing pake message
[error]	2020/08/31 21:18:36 compress.go:46: error copying data: unexpected EOF
[debug]	21:18:36 croc.go:848: problem with decoding: unexpected end of JSON input
[debug]	21:18:36 croc.go:650: got error processing: problem with decoding: unexpected end of JSON input
problem with decoding: unexpected end of JSON input
```

**Comment by schollz** [comment]
@piegamesde Can you try with the latest version? Also, are you getting this error consistently?

**Comment by piegamesde** [comment]
Yes, I can reproduce on latest.

```
NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/c4364cdddc421dfdb4a60fda38ed955abce1603a.tar.gz nix-shell -p 'with (import<nixpkgs>{});buildGoModule rec {pname = "croc";version = "8.1.3";src = fetchFromGitHub {owner = "schollz";repo = pname;rev = "v${version}";sha256 = "0pyn9vgjarqk5hpbfmq7p5n6jk17nzkg9qwpwpa0a07da9igdgzn";};vendorSha256 = "0hf4ifvxj85yrxiczgxglpa16y8rpmiizl03sbdcyp3an7nhdy9v";doCheck = false;subPackages = [ "." ];}'
```

Send log:

```
[debug]	19:40:49 tcp.go:99: client $IP:49674 connected
[debug]	19:40:49 tcp.go:170: strongkey: d37464cfa49cef7d791d58873f4cd0134390bc4f1e1d112dfe062c46d423f98d
[debug]	19:40:49 tcp.go:179: waiting for password
[debug]	19:40:49 tcp.go:202: sending '9010,9011,9012,9013'
[debug]	19:40:49 tcp.go:213: waiting for answer
[debug]	19:40:49 tcp.go:244: room tri has 1
[debug]	19:40:49 tcp.go:108: checking connection of room tri for &{connection:0xc0000b4018}
[debug]	19:40:49 tcp.go:116: room: {first:0xc000098760 second:<nil> opened:{wall:13820350749192750393 ext:17038048237 loc:0x9a48a0} full:false}
[debug]	19:40:49 comm.go:97: initial read error: EOF
[debug]	19:40:49 croc.go:387: [&{connection:0xc00021c018}] had error: EOF
[debug]	19:40:49 croc.go:412: [&{connection:0xc00021c018}] got weird bytes: []
[debug]	19:40:49 croc.go:435: error from errchan: gracefully refusing using the public relay
[debug]	19:40:50 tcp.go:108: checking connection of room tri for &{connection:0xc0000b4018}
[debug]	19:40:50 tcp.go:116: room: {first:0xc000098760 second:<nil> opened:{wall:13820350749192750393 ext:17038048237 loc:0x9a48a0} full:false}
[debug]	19:40:51 tcp.go:108: checking connection of room tri for &{connection:0xc0000b4018}
[debug]	19:40:51 tcp.go:116: room: {first:0xc000098760 second:<nil> opened:{wall:13820350749192750393 ext:17038048237 loc:0x9a48a0} full:false}
[debug]	19:40:51 tcp.go:125: wanted to write 1 but wrote 0: write tcp $IP:9009->$IP:49674: write: broken pipe
[debug]	19:40:51 tcp.go:306: deleting room: tri
```

Receive log:

```
[debug]	19:40:49 tcp.go:412: strong key: d37464cfa49cef7d791d58873f4cd0134390bc4f1e1d112dfe062c46d423f98d
[debug]	19:40:49 tcp.go:421: sending password
[debug]	19:40:49 tcp.go:430: waiting for first ok
[debug]	19:40:49 tcp.go:445: sending room
[debug]	19:40:49 tcp.go:454: waiting for room confirmation
[debug]	19:40:49 tcp.go:467: all set
[debug]	19:40:49 croc.go:591: local connection established to $IP
[debug]	19:40:49 croc.go:592: banner: 9010,9011,9012,9013
[debug]	19:40:49 croc.go:613: exchanged header message
securing channel...[debug]	19:40:49 croc.go:625: ready
[debug]	19:40:49 message.go:46: writing pake message
[error]	2020/09/01 19:40:49 compress.go:46: error copying data: unexpected EOF
[debug]	19:40:49 croc.go:848: problem with decoding: unexpected end of JSON input
[debug]	19:40:49 croc.go:650: got error processing: problem with decoding: unexpected end of JSON input
problem with decoding: unexpected end of JSON input
```

**Comment by schollz** [comment]
Can you try running your own relay and see if it will transmit through that?

**Comment by schollz** [comment]
Oh wait, it looks like it is transmitting locally...are you sure you don't have any firewalls preventing ports 9009-9013?

**Comment by piegamesde** [comment]
Yes, I'm transferring from my machine only for testing purposes. I'm pretty sure having seen it over networked connections as well, I can perhaps try to reproduce this. I don't remember having installed any firewall things, but no guarantee (is there an easy way to check?).

**Comment by schollz** [comment]
If your using linux you should check `ufw status`

**Comment by piegamesde** [comment]
I didn't have `ufw` installed, after installation it says `Status: inactive`.

**Comment by piegamesde** [comment]
Oh wow, out of curiosity I tried sending a file the other way around (otherwise exactly the same setup), now I reproducibly get a segfault:

```
connecting...[debug]	18:07:18 croc.go:453: attempt to discover peers
[debug]	18:07:18 croc.go:493: discovery 0 has payload: address: $IP, payload: croc9009
[debug]	18:07:18 croc.go:498: switching to local
[debug]	18:07:18 croc.go:511: discoveries: [address: $IP, payload: croc9009]
[debug]	18:07:18 croc.go:512: establishing connection
[debug]	18:07:18 croc.go:529: got host '$IP' and port '9009'
[debug]	18:07:18 croc.go:531: trying connection to $IP:9009
[debug]	18:07:23 croc.go:537: could not establish '$IP:9009'
[debug]	18:07:23 croc.go:540: banner: 
[debug]	18:07:23 croc.go:546: receiver connection established: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x609719]

goroutine 1 [running]:
github.com/schollz/croc/v8/src/comm.(*Comm).Write(0x0, 0xc0001592cf, 0x9, 0x9, 0x1, 0x1, 0xc0001592c0)
	/build/source/src/comm/comm.go:71 +0x1b9
github.com/schollz/croc/v8/src/comm.(*Comm).Send(...)
	/build/source/src/comm/comm.go:145
github.com/schollz/croc/v8/src/croc.(*Client).Receive(0xc00009fa00, 0x76346e, 0x8)
	/build/source/src/croc/croc.go:605 +0xb25
github.com/schollz/croc/v8/src/cli.receive(0xc000112420, 0x16, 0x0)
	/build/source/src/cli/cli.go:393 +0x57d
github.com/schollz/croc/v8/src/cli.Run.func4(0xc000112420, 0x0, 0x0)
	/build/source/src/cli/cli.go:101 +0x165
github.com/urfave/cli.HandleAction(0x702d80, 0x77cd80, 0xc000112420, 0x0, 0x0)
	/build/source/vendor/github.com/urfave/cli/app.go:526 +0xfd
github.com/urfave/cli.(*App).Run(0xc000172000, 0xc00009a150, 0x3, 0x3, 0x0, 0x0)
	/build/source/vendor/github.com/urfave/cli/app.go:288 +0x655
github.com/schollz/croc/v8/src/cli.Run(0x964be0, 0xc000000180)
	/build/source/src/cli/cli.go:104 +0xc99
main.main()
	/build/source/main.go:31 +0x26
```

The only difference I can imagine is that it uses p2p transfer only in one direction because it somehow fails to find the other device in the network in the other, defaulting to the relay.

**Comment by schollz** [comment]
I put this line in to catch that error just now: ea781e569b28fa4e5e50131cc11c8a376bd01a86

But that does'nt help your case, for some reason you're getting this:

```
[debug]	18:07:23 croc.go:537: could not establish '$IP:9009'
```

which means it can't connect locally between your computers. I'm not sure why not. This occurred to me when I had a firewall enabled, and I don't know enough about your system to help diagnose that..

**Comment by schollz** [comment]
To me it sounds like multiple things are going on. 

[This](https://github.com/schollz/croc/issues/232#issuecomment-685842311) indicates a firewall issue to me, since connections can't be established.

[This](https://github.com/schollz/croc/issues/232#issuecomment-685027153) indicates some bug I don't understand. Usually this occurs when there is a mismatch of major versions but you indicated that's not it. Do you think it has to do with the files being transferred? Can you replicate these errors on any other pair of computers?

**Comment by piegamesde** [comment]
> This indicates a firewall issue to me, since connections can't be established.

A firewall issue resulting in a segfault? :thinking: 

> This indicates some bug I don't understand. Usually this occurs when there is a mismatch of major versions but you indicated that's not it. Do you think it has to do with the files being transferred? Can you replicate these errors on any other pair of computers?

I did some further testing: The issue seems to be independent from the sent files (I'm usually sending some small dummy text files, whatever lies in the directory). It's not a version mismatch, as I'm using the exact same binary, at least for transfers from my machine to my machine.

However, I found that the croc version packaged in Arch Linux does not suffer from this issue. Therefore, it must be something special to the packaging in Nix.

**Comment by schollz** [comment]
I tried using Nix using [your command](https://github.com/schollz/croc/issues/232#issuecomment-685027153) and still couldn't reproduce this issue - locally or across the public relay.

The segfault you refer to is only a bug from an error that didn't propogate (ea781e5). The error was that it didn't connect. You can try the master version, it will print out the reason it didn't connect in debugging.

**Comment by piegamesde** [comment]
> This indicates some bug I don't understand.

I think I give up on that one. What my tests say:

- Transferring to another machine in my network fails
- Transferring to a remote machine works
- Transferring on my machine works with the Arch version, fails with the Nix packaging
- Interestingly, the Arch package cannot receive files sent from Nix (with pretty much the same error too). But also they have a different patch version, would be a bummer if that made them incompatible.

> Usually this occurs when there is a mismatch of major versions

I suggest building versioning into the protocols in the hope of being able to differentiate the error cause further than a simple "unexpected end of JSON input".

**Comment by schollz** [comment]
Just to be clear - v8 is compatible with v8. I still think there is something else going on. I'll close this, but if can be reproduced on another pair of computers (maybe on a another network) feel free to open and we can figure it out.

**Comment by piegamesde** [comment]
Please reopen:

- I can reproduce it over the internet
    - The error may depend on the sent content (over my local network test setup, it always fails). It works for some files.
    - Again, it works if the application was not packaged for NixOS (except for the too many bytes bug that is still not fixed in the Arch packaging)
- The error log is always pretty much the same, regardless of the situation. I think there are multiple different issues going on nevertheless. More logging/better error handling is needed for further investigation.

**Comment by schollz** [comment]
>  it works if the application was not packaged for NixOS

I do not maintain the packaging for NixOS and is [currently about a month and a half behind](https://search.nixos.org/packages?show=croc&query=croc&from=0&size=30&sort=relevance&channel=unstable#disabled).

> bytes bug that is still not fixed in the Arch packaging

I'm also not the maintainer for Arch and it is [a few days behind](https://www.archlinux.org/packages/community/x86_64/croc/).


I suggest you try to reproduce your problem using the latest master. The latest [release](https://github.com/schollz/croc/release/latest) currently (as of Aug 3, 2020) contains same working code as the master so you don't even need to compile.

**Comment by piegamesde** [comment]
I'm sorry for the confusion. I'm not using the `croc` exactly the way it's packaged in nixpkgs, but with an up to date version. The command I'm using to get a shell with the latest `croc` is:

```
NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/c4364cdddc421dfdb4a60fda38ed955abce1603a.tar.gz nix-shell -p 'with (import<nixpkgs>{});buildGoModule rec {pname = "croc";version = "8.2.0";src = fetchFromGitHub {owner = "schollz";repo = pname;rev = "v${version}";sha256 = "194jn8k9jfrln9skndb4gmhvl8kasyxnd74zhwmji5f9xxlmiaxh";};vendorSha256 = "0qfrc3c4fsg3w2zcpdr93ilknxhshcysvin029va154sq3zmggbn";doCheck = false;subPackages = [ "." ];}'
```

Therefore the tests in my comment above were done on the latest master.

Regarding the Arch package, the usual way to get the latest master would be to have a `croc-git` package in the AUR, which sadly does not exist for some reason.

**Comment by schollz** [comment]
Can you post the entire debug when you run using the latest?

**Comment by schollz** [comment]
Any update?

**Comment by piegamesde** [comment]
On the latest version, everything works fine now. I really can't tell what fixed it, but I won't complain either …

The only thing that is left is a connection failure when sending over the local network (tcp i/o timeout). Instead of failing, a connection over the relay should be tried first. But that's unrelated and something for another issue.
