### ISSUE TITLE
Brew Install on MacOS Big Sur (11.0 Beta)

### ISSUE THREAD

**Issue by dlbone** [schollz/croc#235]
When using brew to install on MacOS Big Sur I get this error:

```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

Brew is fully up to date.

**Comment by schollz** [comment]
How exactly did you get that error?

**Comment by dlbone** [comment]
just doing brew install schollz/tap/croc

![image](https://user-images.githubusercontent.com/8334124/92142310-79bea200-edc8-11ea-8351-3e8d733f0b34.png)

**Comment by schollz** [comment]
perhaps try this? https://github.com/rbenv/ruby-build/issues/1434#issuecomment-612501859

**Comment by schollz** [comment]
Closing because it seems to be a brew/Xcode issue

**Comment by rubenvde** [comment]
Having the same issue, sadly [rbenv/ruby-build#1434 (comment)](https://github.com/rbenv/ruby-build/issues/1434#issuecomment-612501859) isn't working

**Comment by dlbone** [comment]
I tried updating XCode to the latest version and running brew doctor and brew cleanup as mentioned in that other thread. Still getting the same error.

```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

**Comment by rubenvde** [comment]
Got it working by running: `sudo rm -rf /Library/Developer/CommandLineTools` and maybe doing this: `sudo xcode-select --install`. After that this message should go away: 
```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force
```

try installing ruby again and it should work.
