### ISSUE TITLE
No longer possible to specify relay without port

### ISSUE THREAD

**Issue by maximbaz** [schollz/croc#236]
This is really a minor issue, just want to leave it for you to make things consistent at some point.

Previously it was possible to specify relay as address only (IP address or `relay.example.com`), and if no port was specified it would default to `9009`.

Now it fails with an error "bad relay address" if you don't specify the port, so the fallback to `9009` no longer works.

I leave it up to you to decide what is better, require port (and remove fallback) or allow specifying relay address without port.

https://github.com/schollz/croc/blob/81ad30c633c9bc7e988af33291772b86d1403990/src/croc/croc.go#L355-L363

**Comment by schollz** [comment]
@maximbaz good catch! I'd rather keep the previous behavior, I'll push a fix for that
