### ISSUE TITLE
Better UX for wrong password

### ISSUE THREAD

**Issue by piegamesde** [schollz/croc#237]
**Is your feature request related to a problem? Please describe.**

When anything goes wrong in this application, the common error message one gets is:

```
connecting...[error]	2020/09/03 21:17:41 croc.go:565: ips unmarshal error: invalid character '\x01' looking for beginning of value
securing channel...[error]	2020/09/03 21:17:42 compress.go:46: error copying data: unexpected EOF
problem with decoding: unexpected end of JSON input
```

This is bad UX, because it doesn't tell the user that the password simply was wrong.

**Describe the solution you'd like**

A message like "wrong password" or the like would be really good. In general, error handling should communicate what went wrong in a way the user has a chance at distinguishing the cause. Have they made a mistake? Is it some network communication error? Is it a software bug that should be reported?

**Additional context**

While trying to reproduce #232 I sent a lot of test files any I just noticed that the error message there is exactly the same as when I copied the wrong passphrase.

**Comment by schollz** [comment]
Added https://github.com/schollz/croc/commit/bbc0ce4e9c1bf21d7938bf3662b3e06f13467b0b

**Comment by piegamesde** [comment]
Hm, I can still reproduce on 8.3.0.

**Comment by schollz** [comment]
I can't...how are you reproducing?

When the wrong password is used receiver says

```
securing channel...password mismatch
``` 

and sender says:

```
could not secure channel
```

**Comment by piegamesde** [comment]
```
[nix-shell:~]$ croc laser-rent-bucket
connecting...[error]	2020/09/05 02:27:26 croc.go:575: ips unmarshal error: invalid character '\x01' looking for beginning of value
securing channel...[error]	2020/09/05 02:27:27 compress.go:46: error copying data: unexpected EOF
problem with decoding: unexpected end of JSON input
```

I can also get the "correct" error message, but not in all cases:

```
[nix-shell:~]$ croc music-carmen-etesdfg
securing channel...password mismatch
```
