### ISSUE TITLE
Option to disable compression

### ISSUE THREAD

**Issue by jackric** [schollz/croc#239]
**Is your feature request related to a problem? Please describe.**
When sending a file with high entropy (adverse to compression) let me explicitly disable croc's compression to save CPU cycles. Examples: already compressed archive, encrypted volume, compressed video.

**Describe the solution you'd like**
croc send --no-compression file.tar.gz

**Comment by schollz** [comment]
Now added as `croc send --no-compress file`

**Comment by aashwin-rs** [comment]
`croc --no-compress send file` seems to work but `croc send --no-compress file` will print the error `Incorrect Usage: flag provided but not defined: -no-compress`

`no-compress` also isn't in the help section for `croc send`

**Comment by Zefferis** [comment]
This still appears to be an issue on:
croc version v9.4.2-49f50a5

**Comment by nick-robo** [comment]
Flag order is still an issue @schollz

**Comment by schollz** [comment]
New PR is welcome
