### ISSUE TITLE
tcp.go:81: error listening on 9009:

### ISSUE THREAD

**Issue by eddvys** [schollz/croc#241]
Describe the bug
Long story short... Installed on windows 10 with Snoop latest version (8.3.0-87e54ac) and simply said. 

To Reproduce - Tried running as administrator tried powershell, tried re-install.. Not sure if I'm doing something wrong or what, but that's the errors. 

C:\Users\XXxxxXXX>croc send C:\Users\XXxxxXXX\Desktop\dog1.jpg
Sending 'dog1.jpg' (56.6 kB)
Code is: secure-nikita-connect
On the other computer run

croc secure-nikita-connect
[error] 2020/09/04 23:35:52 tcp.go:81: error listening on 9009: listen tcp :9009: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
panic: error listening on 9009: listen tcp :9009: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

goroutine 6 [running]:
github.com/schollz/croc/v8/src/croc.(*Client).setupLocalRelay.func1(0xc00004f860, 0xa0fe6d, 0x4)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:268 +0x165
created by github.com/schollz/croc/v8/src/croc.(*Client).setupLocalRelay
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:261 +0x8c

C:\Users\XXxxxXXX>croc secure-nikita-connect
connecting...[error]    2020/09/04 23:36:42 croc.go:575: ips unmarshal error: invalid character '\x01' looking for beginning of value
securing channel...[error]      2020/09/04 23:36:43 compress.go:46: error copying data: unexpected EOF
problem with decoding: unexpected end of JSON input

C:\Users\XXxxxXXX>

Ed.

**Comment by schollz** [comment]
Is there something else running on 9009? Also, when the permissions notification popped up, did you allow or disallow?

**Comment by AnotherFoxGuy** [comment]
I've run into the same issue today 
This seems to be running on port 9009: https://pastebin.com/nG6t7V2k
It belongs to the Windows 10 system process, but I cannot find any information on why it is using that port

**Comment by eddvys** [comment]
Well, first of all I know what is running on my ports. Secondly I couldn't figure out why 9009 is occupied. But reply above me gives more insight, i guess.

**Comment by schollz** [comment]
I'll close this since its a windows issue. If lots of people have this though I can find a workaround to pick a new port.
