### ISSUE TITLE
unable to send and receive data from stdin in while running in the same directory

### ISSUE THREAD

**Issue by dtrodrigues** [schollz/croc#243]
**Describe the bug**
Trying to receive stdin from the same directory as the server fails.

**To Reproduce**
1. In one terminal, type `croc send --code=mycode --text=mytext`
2. In a second terminal from the same directory, run `croc --yes mycode`

**Expected behavior**
`mytext` to be printed to the screen, instead, the output is
```
 $ croc --yes mycode
Receiving 'croc-stdin-999539044' (6 B)

Receiving (<-[::1]:52601)
[warn]	2020/09/05 16:13:51 error removing croc-stdin-999539044: remove croc-stdin-999539044: no such file or directory

$
```

**Version**
croc version v8.3.0-87e54ac

**Additional context**
Running the second command from a different directory does work.

**Comment by schollz** [comment]
Good :bug: , should be fixed with this: https://github.com/schollz/croc/commit/345ef0567e50c0e74452a03fdc03f4359c225c84

**Comment by dtrodrigues** [comment]
That worked. Thanks for the quick fix.
