### ISSUE TITLE
croc as mobile application

### ISSUE THREAD

**Issue by shadowshan125** [schollz/croc#247]
If this in the mobile platform is android and ios better work like gui 
That's awesome try this

**Comment by rpush-01** [comment]
I do believe it depends on how accessible writing to the file systems works, and if the network firewalls on those devices allow files to be incoming by default. If it is possible I would be happy to work on it!

**Comment by kael-shipman** [comment]
@schollz curious about why this got closed without comment. I'd be very interested in this and since the software is written in Go it seems like there's a somewhat straightforward route to implementation (not by me, since I don't yet have mobile chops, but certainly by someone).

**Comment by schollz** [comment]
Closed prematurely. Happy to have someone try this!

**Comment by Lifeling** [comment]
Just in case someone is looking to get this running on android. It is easy to install using Termux[Termux](https://play.google.com/store/apps/details?id=com.termux)  and works perfectly.

**Comment by kael-shipman** [comment]
That's awesome! Thanks for the pointer.

**Comment by kael-shipman** [comment]
@Lifeling I just installed termux on my android and the installed croc using `pkg install croc`, but I can't figure out how to access my sd card files. Any suggestions?

**Comment by avimar** [comment]
> @Lifeling I just installed termux on my android and the installed croc using `pkg install croc`, but I can't figure out how to access my sd card files. Any suggestions?

You need to run something like `termux-setup-storage`

**Comment by Lifeling** [comment]
@kael-shipman Unfortunately this looks like a limitation of termux due to some android security features. https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by howeyc** [comment]
I made a simple android app.

https://github.com/howeyc/crocgui

**Comment by avimar** [comment]
> I made a simple android app.
> 
> https://github.com/howeyc/crocgui

How does one install this? I've only installed from the Play store ...

**Comment by Marksdo** [comment]
I made a simple iOS croc app iCroc.

https://iCroc.marksdo.com or search iCroc in the app store
