### ISSUE TITLE
croc send --text does not work

### ISSUE THREAD

**Issue by CalvinPaean** [schollz/croc#248]
When I use croc send --text "hello world", it does not work. It reports the following message:

Incorrect Usage: flag provided but not defined: -text

NAME:
   croc send - send a file (see options with croc send -h)

USAGE:
   croc send [command options] [filename]

DESCRIPTION:
   send a file over the relay

OPTIONS:
   --code value, -c value  codephrase used to connect to relay
   --no-local              disable local relay when sending
   --no-multi              disable multiplexing
   --ports value           ports of the local relay (optional) (default: "9009,9010,9011,9012,9013")
   
flag provided but not defined: -text

**Comment by jolheiser** [comment]
What version of croc are you using? `croc --version`

It looks like sending/receiving text was introduced in [v8.2.0](https://github.com/schollz/croc/releases/tag/v8.2.0)
