### ISSUE TITLE
Do not allow new sender/receiver connection with the same code as current sender/recevier

### ISSUE THREAD

**Issue by schollz** [schollz/croc#25]
In the code, when someone connects it adds to a dictionary of current connections. Before adding, it should be checked if they are in the dictinoary and if so, `sendMessage("no")` and return. The code to edit is here: https://github.com/schollz/croc/blob/master/relay.go#L112-L115 and here: https://github.com/schollz/croc/blob/master/relay.go#L144. 

Please let me know if there are any questions.

**Comment by lummie** [comment]
I'll take this :)

**Comment by schollz** [comment]
Great! Don't hesitate to send me a question

**Comment by lummie** [comment]
Is it possible to run it all on one machine for testing ?  
Tried `./croc -relay` in one terminal
`./croc -server localhost -send ~/Pictures/Avatar.png` in another and both just output a cat and croc version...

**Comment by schollz** [comment]
@lummie Yes. Its not clear at the moment, but you had the right idea. You need to run three commands in three different terminals:

1. `./croc -relay` will be the relay
2. `./croc -server localhost -send FILE -code 1-test` will send the file, with code specified
3. `./croc -server localhost -code 1 test` will receive the file without prompting about the code

**Comment by schollz** [comment]
Oh also I just found I deleted those lines that tell you what to do after you start sending, fixed!

**Comment by lummie** [comment]
@schollz Ok have done the rejecting multiple senders with the same key and tested it.
For the multiple receiver connections side, am I right in saying that the receiver is not recorded until here https://github.com/schollz/croc/blob/master/relay.go#L169
which is after the received has given consent, so up until this point multiple receivers could be connected  but only those connected whilst the file was downloading would be rejected.
Are you happy with this?  If not then we need to add a map of potentialReceivers to the connectionMap and use this to reject multiple receivers.

**Comment by schollz** [comment]
@lummie You are correct in that! I didn't think about that. I think having a map of potentialReceivers is a great solution. Would you like to add that too?

**Comment by lummie** [comment]
@schollz will do :)
