### ISSUE TITLE
Show "Enter receive code:" after I open it in Windows 10

### ISSUE THREAD

**Issue by luofe** [schollz/croc#250]
It always display "Enter receive code" when I open it, but actually I want start to send a file, so, how can I use it to send the file?
![Untitled](https://user-images.githubusercontent.com/44823232/92571631-ee587b80-f2b5-11ea-923a-87a70fb437d5.png)

**Comment by jolheiser** [comment]
According to the [README](https://github.com/schollz/croc#usage)

`croc send [file(s)-or-folder]`
