### ISSUE TITLE
Add bash autocomplete

### ISSUE THREAD

**Issue by schollz** [schollz/croc#253]
Bash autocomplete is enabled already, but needs wrapper scripts to function. I think my plan is to bundle [these two autocomplete wrapper scripts](https://github.com/urfave/cli/tree/master/autocomplete) into the archive, which will be installed using the bash installer (`curl https://getcroc.schollz.com | bash`). The bash installer should install the autocomplete scripts as long as the OS is not Windows.

The bash installer can install the `bash_autocomplete` by doing:

```
sudo cp bash_autocomplete /etc/bash_completion.d/croc
```

I'd also like to go for zsh, but it is more complicated. As with bash, an autocomplete file is copied:

```
sudo cp zsh_autocomplete /etc/zsh/zsh_autocomplete_croc
```
and then it needs to check the `~/.zshrc` file and add if its not already added:

```
# croc autocomplete add to ~/.zshrc
PROG=croc
_CLI_ZSH_AUTOCOMPLETE_HACK=1
source /etc/zsh/zsh_autocomplete_croc
```

@TheQueasle would you be interested in helping out with this? Its totally fine if you have other fish to fry, I can certainly give it a shot :)

**Comment by TheQueasle** [comment]
@schollz I'd love to help out! Feel free to assign this issue to me and I'll start working at it in my downtime.

**Comment by schollz** [comment]
@TheQueasle That is so great! I'm so happy you can help - I gave it a shot and was not getting along very well. I get really hacky when it comes to bash. And you've written such wonderful code (seriously, incredible) that I'd be remiss to add my hacks into it. :smile: 

Currently no releases are bundled with `zsh_autocomplete` and `bash_autocomplete` but you can assume that those will be the exact filenames that will be included in future releases for the installer script. I'm working on adding them in the next release (soon).

Let me know if you have any questions, and please don't hesitate to let me know if you'd rather not do this - that's totally fine! I appreciate your collaboration and help in any case.

**Comment by TheQueasle** [comment]
Thanks for the kind words about my bashin' :blush:

Also - no worries!  I'm happy to help and sorry I've not been able to help out sooner.

I've started playing around with things and noticed what looks like a Windows end-line character (^M) in the autocomplete suggestions?

```
thequeasle@darter-pro:~$ croc <tab>
receive^Melay  send   
```

Not sure if this is something on my end or if there or if is a sneaky windows endline char somewhere in the source/logic that makes `croc --generate-bash-completion` spit out an endline where it shouldn't.

I did a quick grep across the entire repo but didn't see anything glaring...but I could have missed it.

Does this happen in your environment?

**Comment by schollz** [comment]
@TheQueasle Yes, absolutely right. I forgot I had overrode the default bash completion. The latest commit (567b95d7536cdd883252f73933bea945967d7af9 in master) gets rid of that so now it looks good. Here's mine in zsh:

```
> croc <tab>
help   h  -- Shows a list of commands or help for one command                          
relay     -- start your own relay (optional)                                           
send      -- send a file (see options with croc send -h) 
```

There is a bit of a problem, which I'll figure out, in that parameters for sub commands show up in bash: 

```
> croc send --<tab>
--ask          --no-compress  --pass         --remember     --yes        
--code         --no-local     --ports        --stdout                    
--debug        --no-multi     --relay        --text                      
--help         --out          --relay6       --version 
```

I'll fix that in the meantime.

**Comment by schollz** [comment]
Turns out the bug that autocompletes with global flags on sub-commands was due to a bug in urfave/cli (https://github.com/urfave/cli/issues/1184). I forked that with a fix: https://github.com/schollz/croc/commit/7b15dcd2dc72323d040910c1138906dfb436f04e so its good now :)

**Comment by TheQueasle** [comment]
Added a branch to my fork with the install logic to include the bash or zsh completions.

https://github.com/TheQueasle/croc/tree/253-autocomplete-install

Current logic installs just the completion file for the current shell.  I still need to make its error handling a little more robust incase the script is ran in an environment with a shell other than bash or zsh.

Also - for the extra steps for zsh users - I opted to just print info on how to get the auto complete working instead of modifying a user's `~/.zshrc` automatically.

I've only tested on Pop!_OS 20.04 at this time.

**Comment by schollz** [comment]
@TheQueasle It looks phenomenal, thank you so much! I tried it and it works well on Ubuntu 20.

**Comment by TheQueasle** [comment]
@schollz Sorry for the delay on my pull request.  I'd left it thinking I had done it already and noticed the issue was still open.

Looks like you may have already added the code though?

**Comment by schollz** [comment]
@TheQueasle yep, I pulled it from your repo! It is really great, nice and simple change you made compared to the ugly and complicated thing I was going to do! I'll close this now.
