### ISSUE TITLE
Question: How are the codes stored and organized?

### ISSUE THREAD

**Issue by rpush-01** [schollz/croc#255]
I am a bit of a new coder, and was wondering how the codes for receiving created, organized, and stored? I was looking to to create a project with a similar way of connecting/authentication, but couldn't figure out how it was done while poking around the project. Great project, its been super useful for me.

**Comment by schollz** [comment]
Codes are created using https://github.com/schollz/mnemonicode (forked from bitbucket.org/dchapes/mnemonicode)

These codes are exchanged using PAKE: https://github.com/schollz/pake

After exchanging, the resulting key established by the two parties is secure.

All encryption is done using the resulting key (NOT the initial code).

This type of encryption occurs between every pair of parties in croc (sender <-> recipient, sender <-> relay server, recipient <-> relay server)

**Comment by rpush-01** [comment]
Thank you!
