### ISSUE TITLE
How to use -rate flag in sender?

### ISSUE THREAD

**Issue by pauldeng** [schollz/croc#256]
Hi all,

Thanks for this great app. I am new to this, applogize if I ask silly question.

I would like to know how to use the -rate option to limit sender's outgoing speed.
It was merged long time ago at https://github.com/schollz/croc/pull/24. However, I cannot find any document, help in app about it.

This is an excellent feature and useful in some low-bandwidth scenarios.

Can you please provide an example on how to use the -rate option?

Thanks heaps.

Cheers,
Paul

**Comment by schollz** [comment]
That flag no longer exists, though it did in a deprecated version, so it cannot be used.

I'd happily take a PR that adds it.
