### ISSUE TITLE
File transfer limit 500MB?

### ISSUE THREAD

**Issue by fyenne** [schollz/croc#257]
How can i transfer a file larger than this

**Comment by schollz** [comment]
There are currently no file transfer limits.

Perhaps you encountered a bug? If so, please show the version and the `--debug` output

**Comment by fyenne** [comment]
Thank you for replying. My original file contains 7 GB photos and so on, I **compressed** the file later, and the problem is solved. 
I checked my documents again, and one of the folders has no name, perhaps it is the bug.
