### ISSUE TITLE
Package https://chocolatey.org/

### ISSUE THREAD

**Issue by pomazanbohdan** [schollz/croc#258]
Thanks for the program.
It would be handy if someone would pack for choco

**Comment by schollz** [comment]
I use goreleaser, and it look's like its not available: https://github.com/goreleaser/goreleaser/issues/131

Totally fine if someone wants to maintain this project on chocolatey

**Comment by bigyank** [comment]
seconded, would love to have it on choco

**Comment by TheChiefMeat** [comment]
I have it pending for review as we speak on Chocolatey.

**Comment by schollz** [comment]
Thank you @TheChiefMeat !

**Comment by TheChiefMeat** [comment]
> Thank you @TheChiefMeat !

You're welcome :)

**Comment by TheChiefMeat** [comment]
Croc is now up on Chocolatey https://chocolatey.org/packages/croc

I've added a pull request to include Chocolatey in the installation instructions as well https://github.com/schollz/croc/pull/265

@pomazanbohdan This issue can be closed now :)
