### ISSUE TITLE
Add/replace brew installation instructions with core tap install

### ISSUE THREAD

**Issue by dtrodrigues** [schollz/croc#262]
**Is your feature request related to a problem? Please describe.**
Now that `croc` is in Homebrew-core - https://formulae.brew.sh/formula/croc - consider adding an additional install command or replacing the existing command with `brew install croc` to give users the option to not need to install an additional tap.

**Describe the solution you'd like**
Addition of `brew install croc` to the README.

**Describe alternatives you've considered**
Continue only describing Homebrew tap installs

**Additional context**

**Comment by schollz** [comment]
Thank you @dtrodrigues !
