### ISSUE TITLE
Only displays the name of the first file

### ISSUE THREAD

**Issue by mig4ng** [schollz/croc#264]
**Describe the bug**
When sending files without the send argument (e.g. drag and drop multiple files into croc) it only shows the first file in the confirmation dialog.

**To Reproduce**
1. Use `croc file1 file2`
2. It shows the dialog with only the file1

or

1. Drag and drop multiple files into the croc executable
2. It shows the dialog with only the file1

**Expected behavior**
Show all the files.

**Version**
v8.3.2

**Additional context**
I found the code in source, unfortunately I do not know Go, therefore I cannot open a PR. With small guidance I would probably be able to open a PR. This is a small issue, no big deal, would actually be a great issue to leave open for Hackoberfest if anyone with Go skills wanted to fix it.
https://github.com/schollz/croc/blob/db388f47a6bf6a62888602d2a00f52e805fbeb56/src/cli/cli.go#L93-L99

This is not a problem if you use `croc send` however for non-tech people which use drag and drop into croc this might be confusing.

P.S. croc is really simple to use, I was amazed.

**Comment by schollz** [comment]
You can't send files without the send argument.

What is happening is that `croc` is trying to figure out what you are doing and assumes you are sending a file. Your syntax `croc X` usually means to receive a file with passcode `X`. However, if `X` is a file, croc will ask you if you mean to *send* `X`. If you want to send multiple files, I suggest just doing `croc send X Y...`

**Comment by mig4ng** [comment]
```
> croc file1 file2
Did you mean to send 'file1'? (y/n) y
Sending 2 files (2.1 MB)
Code is: earth-spend-talent
On the other computer run

croc earth-spend-talent

Sending (->XXX.XXX.XXX.XXX:55352)
file1     100% |████████████████████| (2.0/2.0 MB, 375.743 kB/s) [5s:0s] ✔️
file2     100% |████████████████████| (2.8/2.8 kB, 2.724 MB/s) [0s:0s] ✔️
```
I know this is a very specific edge case, yet because you send the whole `c` (context I think) in `return send(c)` it sends all the files even if you specify multiple files without the send argument. This is just a nice to have, since with the send argument it does not display the question.

It matters (e.g.) for GUI users that can select multiple files in the finder/folder and drag and drop it to croc executable/app, in Windows it tried to run the executable with the files you dragged as arguments.

This is a very small bug, it is not how croc is intended to be used, that is why I suggested it as an Hacktoberfest issue, however I understand that it might be extra unnecessary code. Another way to fix it would be for example to remove the file name from there (e.g. "Did you mean to send the file(s)?").

**Comment by schollz** [comment]
@mig4ng Aw, okay! I actually didn't know that you could do that with croc, what a neat surprise! 

This sounds like a *perfect* first PR or Hacktoberfest issue. 

> Another way to fix it would be for example to remove the file name from there (e.g. "Did you mean to send the file(s)?").

That sounds like a great fix, and an easy one. I'd be happy to help you if you want to try fixing!
