### ISSUE TITLE
error listening on 9012

### ISSUE THREAD

**Issue by huzeyfecoskun** [schollz/croc#269]
on windows croc gives error

[error] 2020/09/20 18:08:41 tcp.go:81: error listening on 9012: listen tcp :9012: bind: Normally only one use is allowed per socket address (protocol / network address / port).
panic: error listening on 9012: listen tcp :9012: bind: Normally only one use is allowed per socket address (protocol / network address / port).

goroutine 22 [running]:
github.com/schollz/croc/v8/src/croc.(*Client).setupLocalRelay.func1(0xc00008f6c0, 0xc7b188, 0x4)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:275 +0x165
created by github.com/schollz/croc/v8/src/croc.(*Client).setupLocalRelay
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:268 +0x8c
PS C:\Users\ninespc\Downloads\croc_8.3.2_Windows-64bit>

**Comment by schollz** [comment]
I think that you have another windows process using that port?

Try running

```
croc send --no-local X
```

**Comment by huzeyfecoskun** [comment]
> I think that you have another windows process using that port?
> 
> Try running
> 
> ```
> croc send --no-local X
> ```

this one works. the other one is not working.

**Comment by schollz** [comment]
Okay great. I just added a fix so it will find the first open ports and not use those exact ports for local relay. Local discovery still works (because it discovers the port). Will be available in 8.3.3, soon

**Comment by huzeyfecoskun** [comment]
thank you for your efforts. this app great.
