### ISSUE TITLE
Croc via HTTP proxy

### ISSUE THREAD

**Issue by skanga** [schollz/croc#270]
Some networks only allow outbound connections via an HTTP proxy server. Can croc find a way through these?

**Comment by schollz** [comment]
Can you be more specific? How is the proxy setup?

**Comment by colindaven** [comment]
I have probably just had the same problem.

I think he means he has an institutional firewall / proxy and the port 9009 is blocked (as is probably happening at my workplace).

From croc -h
   --relay value   address of the relay (default: "142.93.177.120:9009") [$CROC_RELAY]

Can a proxy be specified (i.e. IP in this --relay) or via another method or is this not possible ?

Thanks

**Comment by c-h-u-c-k** [comment]
Actually, maybe you should respect $http_proxy env setting like curl does... see something like
https://tecadmin.net/curl-command-with-proxy/ (some random site)

**Comment by conphi** [comment]
For me, in terminal.
`export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890`
The 'curl' command and other commands has been tested works fine through proxy.
The 'croc' command fails.

**Comment by schollz** [comment]
Looks like this may work: https://stackoverflow.com/questions/40749222/sending-tcp-packets-to-proxy

**Comment by schollz** [comment]
Okay, the master now includes an option to add a SOCKS5 address.

You can do `croc --socks5 "127.0.0.1:9050" ...` to use a proxy.

**Comment by skanga** [comment]
Thank you @schollz

**Comment by skanga** [comment]
I tried --socks5 but it does not work for me.

We ONLY have support for http and https proxies. Any chance of adding that?

**Comment by schollz** [comment]
@skanga yeah I think its possible. Is there a super easy way to setup a personal HTTP proxy for testing? For SOCKS5 testing I just had to do `sudo apt install tor; sudo /etc/init.d/restart tor`.

**Comment by skanga** [comment]
Try `sudo apt install squid; sudo /etc/init.d/restart squid`

**Comment by schollz** [comment]
@skanga I've tried using the Golang libraries for making an HTTP proxy and that works fine for HTTP connections but I can't figure out how to get a TCP connection using the HTTP proxy. Do you know if it is possible to use a HTTP proxy for just sending TCP packets generally?

**Comment by skanga** [comment]
@schollz  I do believe that this is possible. Most proxies (like squid) support a CONNECT method in addition to the usual HTTP methods like GET, POST, PUT, etc.

You have to somehow use that. I know people who run ssh tunnels thru the proxies using this but not sure about the details on how it works.

**Comment by conphi** [comment]
@schollz It works now, but large file with proxy always be interrupted after for a while, have to restart both sides of client and server manually, anything can do to make it automatically catching interruptation and recover.

**Comment by schollz** [comment]
@skanga Do you know of a Go library that handles creating TCP connections through HTTP proxies? I have so little knowledge of it so I wouldn't be good for making my own. I did search for packages but couldn't find ones that worked, but maybe my search/tests weren't good.

@conphi Do you know if your proxy is restarting or anything? Can I try replicating it (e.g. are you sending a large file over tor?)?

**Comment by skanga** [comment]
@schollz - no sorry, don't know anything about Go or libraries for this.

@conphi - can you make it such that both sides can restart and resume where it last left off?

**Comment by conphi** [comment]
@schollz Proxy should be working, I eventually finished my job by aria2c instead. A single file about 9G by a remote http server, sending over [Shadowsocks ](https://github.com/shadowsocks/shadowsocks)which is a popular proxy in China to break the GFW.

@skanga I did make both sides restart and resume, it works, but I have to do this same process again and again because it won't last too long before I repeat it again.

**Comment by quyleanh** [comment]
It's seems that if proxy server block port connection, croc cannot work.

```bash
$croc --debug --socks5 "proxy.address:port"
[debug] 17:21:50 cli.go:141: debug mode on
Enter receive code: field-button-arnold
[debug] 17:21:59 croc.go:156: options: {IsSender:false SharedSecret:field-button-arnold Debug:true RelayAddress:croc.schollz.com RelayAddress6:croc6.schollz.com RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false Ask:false SendingText:false NoCompress:false}
connecting...[debug]    17:21:59 croc.go:486: attempt to discover peers
[debug] 17:22:00 croc.go:544: discoveries: []
[debug] 17:22:00 croc.go:545: establishing connection
[debug] 17:22:00 croc.go:560: got host 'croc6.schollz.com' and port '9009'
[debug] 17:22:00 croc.go:562: trying connection to croc6.schollz.com:9009
```

One more thing, could you please support http proxy with username and password?

**Comment by N0mansky** [comment]
I have implemented this feature to support HTTP proxy. You can fork my version and compile if you want to use an HTTP proxy.
Usage:
1. send: `croc -connect="http://proxy_addr" filename`
2. receive: `croc -connect="http://proxy_addr" code`
