### ISSUE TITLE
Getting permission denied after receiving file

### ISSUE THREAD

**Issue by scotrod** [schollz/croc#275]
**After I send the file from Windows host to Linux VM I get:**
Accept 'db.txt' (0 B)? (y/n) y

Receiving (<-[::1]:1536)
[error] 2020/09/23 14:26:48 croc.go:961: open db.txt: permission denied
open db.txt: permission denied

I can transfer files from Linux box to Windows, but the reverse seems to be a permissions problem, and I don't know where to look.

**Using:**
croc version v8.0.12-7fd8fda
Windows 10 Pro 2004
Ubuntu Server 20.04 VM

**Comment by schollz** [comment]
Are you using a snap?

Can you try upgrading to the latest version?

**Comment by scotrod** [comment]
Hi, I'm not much of a Linux guy: `sudo snap refresh ` is what I did.
Same result after the update.

**Comment by schollz** [comment]
Where is your `db.txt` located? 

It is a known issue that snap can't access dot-files in home directory (https://github.com/schollz/croc/issues/190) and unfortunately the snap folks basically told me there is no way to fix this.

**Comment by schollz** [comment]
I'd be curious if the following works:

```
> cat db.txt | croc send
```

That way the snap isn't "accessing" a file.

**Comment by scotrod** [comment]
`> cat db.txt | croc send` outputs: 
```
cat: db.txt: No such file or directory
open croc-stdin-821505985: permission denied
```
I searched for db.txt file with `find . -name db.txt` but that doesn't display anything. Same with locate db.txt

**Comment by schollz** [comment]
Ok, I'm confused. What is this file you are sending?

```
Accept 'db.txt' (0 B)? (y/n) y
```

That means to me that you are sending an empty file named `db.txt`? Does your file exist?

**Comment by scotrod** [comment]
Hello, of course, It's just an empty .txt file. I tried sending another much bigger .txt file but the result is the same.

**Comment by scotrod** [comment]
Here's a video to make things more clear: [Link](https://imgur.com/MHIJtus)

**Comment by schollz** [comment]
Okay, I think its a snap issue.

Try receiving the file in the `/tmp` directory or in the `/root` directory instead. If that doesn't work, try receiving the file using the pre-built version (install with `curl https://getcroc.schollz.com | bash`) or just download directly.

**Comment by scotrod** [comment]
Yes, that seems to work. Like I said, I'm not a Linux tech savvy so I can't understand why when I type `croc --out /tmp [my-phrase]` it saves the files in `/tmp/snap.croc/tmp` not in `/tmp`

But it works doe!

**Comment by schollz** [comment]
Okay this is all weird snap stuff! I would recommend not using snap. I can't get its behavior to match anything in the normal program

**Comment by Bombastisch** [comment]
Would an package provided via apt solve this kind of problem?
As far as I see though, there is no packages maintained on apt, right?

**Comment by NothingCtrl** [comment]
I see message "Access is denied" between two Windows 11 computer, only happen with PDF file (currently), **the file is receive OK**.

Error:
```
C:\Users\username\Desktop>croc xxx-xxx-xxx-xxx
Accept 'xxxx.pdf' (2.3 MB)? (Y/n)

Receiving (<-server-ip:port)
xxxl.pdf 100% |████████████████████| (2.3/2.3 MB, 1000 kB/s)
[error] 2023/09/06 16:01:45 croc.go:1386: could not create xxx.pdf: open xxx.pdf: Access is denied.
```

**Comment by blsz** [comment]
I'm seeing the same behavior when sending a single file from Ubuntu 23.10 to Ubuntu 22.04 over a local private network.  The file is sent despite the error.  

croc is installed with "sudo apt install ./croc_9.6.6_Linux-64bit.deb" on both ends.

```
$ croc xxxx-xxxx-xxxx-xxxx
Accept 'xxxxxx' (139.6 kB)? (Y/n) Y

Receiving (<-192.168.0.22:9009)
 xxxxxx 100% |████████████████████| (143/143 kB, 3.3 MB/s)
[error] 2023/12/05 17:02:22 croc.go:1487: could not create xxxxxx: open xxxxxx: permission denied
```
