### ISSUE TITLE
The use of a default relay is potentially dangerous and unreliable

### ISSUE THREAD

**Issue by lf94** [schollz/croc#277]
[This file](https://github.com/schollz/croc/blob/master/src/models/constants.go#L7) defines a default relay to use in the situation where one is not specified as an argument.

What guarantee is there for the default relay to be reliable?

What guarantee is there for the default relay to be secure?

The application should instead, at the very least, specify a "--use-default-relay" argument, or remove the default relay entirely. This is safer behavior.

**Comment by schollz** [comment]
See https://github.com/schollz/croc/blob/master/LICENSE re your questions

**Comment by lf94** [comment]
The questions were rhetorical, and yes your response highlights the answer: none.
