### ISSUE TITLE
Why not rust? It’s better (:

### ISSUE THREAD

**Issue by AsafFisher** [schollz/croc#278]
I feel like everything will is better with rust...

**Comment by schollz** [comment]
I don't know rust. But go for it!

**Comment by AsafFisher** [comment]
Actually thought about it! I might just do it :)

**Comment by piegamesde** [comment]
From my experience with Wormhole and its Rust rewrite: As soon as there is more than an implementation, the protocol(s) used should be documented **and put into a separate repository**.
