### ISSUE TITLE
Emit shell completion from a CLI subcommand

### ISSUE THREAD

**Issue by crimeminister** [schollz/croc#282]
Various other CLI tools I have used have adopted the convention of emitting shell completion configuration from a subcommand, e.g.
```
$ kubectl completion bash
$ kubectl completion zsh
``` 
I find that tooling is a little more convenient to use when more self-contained, so it would be great if `croc` adopted something similar.

**Comment by schollz** [comment]
The completion is built-in to https://github.com/urfave/cli so this would require a more substantial fork of it. What benefits does this provide?

**Comment by crimeminister** [comment]
I have grown to appreciate this (and related forms of bundling) as it makes it much simpler to install and use various utilities. Installation scripts are reduced to downloading the appropriate binary and dropping it on your path. Those that want the shell integration source the output and carry on. Admittedly this is a bigger win when you don't already have a selection of distro-specific packages available and would prefer to avoid managing same. Definitely falls into the nice-to-have category rather than anything essential.
