### ISSUE TITLE
Transfer speed fluctuation & crashing

### ISSUE THREAD

**Issue by roydev19** [schollz/croc#285]
There is a huge transfer speed drop towards the end of the file transfer
I suppose there is some kind of a parallelized file transfer protocol working here but I would expect it not too slow down while still around 20-15 % of it is still left.
I had to ask the receiving party to cancel the transfer in expectation of resuming it, would restore the speed.
But did not.

croc version v8.4.0-224c442

Here is the debug log of the cancelled transfer.

Receiving (<-113.21.67.8:56478)
[debug] 17:06:18 croc.go:776: [{Her 2013 (1080p x265 10bit Joy).mkv . /home/tv/Downloads/Her 2013 (1080p x265 10bit Joy)/ [202 209 169 251 3 69 24 240 175 230 210 7 240 212 108 240] 1063938250 2020-10-09 16:54:19.369102461 +0530 IST false false }]
[debug] 17:06:18 croc.go:1179: checking {Name:Her 2013 (1080p x265 10bit Joy).mkv FolderRemote:. FolderSource:/home/tv/Downloads/Her 2013 (1080p x265 10bit Joy)/ Hash:[202 209 169 251 3 69 24 240 175 230 210 7 240 212 108 240] Size:1063938250 ModTime:2020-10-09 16:54:19.369102461 +0530 IST IsCompressed:false IsEncrypted:false Symlink:}
[debug] 17:06:18 croc.go:1191: Her 2013 (1080p x265 10bit Joy).mkv cad1a9fb034518f0afe6d207f0d46cf0 cad1a9fb034518f0afe6d207f0d46cf0 <nil>
[debug] 17:06:18 croc.go:1195: hashes are equal cad1a9fb034518f0afe6d207f0d46cf0 == cad1a9fb034518f0afe6d207f0d46cf0
[debug] 17:06:18 croc.go:1078: finished
[debug] 17:06:18 message.go:43: writing finished message (encrypted)
[debug] 17:06:18 croc.go:1022: working on file 0
[debug] 17:06:18 comm.go:96: initial read error: EOF
[debug] 17:06:18 comm.go:96: initial read error: EOF
[debug] 17:06:18 comm.go:96: initial read error: EOF
[debug] 17:06:18 comm.go:96: initial read error: EOF
[debug] 17:06:19 croc.go:1101: converting to chunk range
[debug] 17:06:19 croc.go:1109: sending recipient ready with 3434 chunks
[debug] 17:06:19 message.go:43: writing recipientready message (encrypted)
[debug] 17:06:19 message.go:43: writing finished message (encrypted)

Here is the debug log of the resumed transfer.

croc.go:1346: finished receiving!
[debug] 17:24:00 croc.go:1358: sending close-sender
[debug] 17:24:00 message.go:43: writing close-sender message (encrypted)
[debug] 17:24:01 croc.go:1179: checking {Name:Her 2013 (1080p x265 10bit Joy).mkv FolderRemote:. FolderSource:/home/tv/Downloads/Her 2013 (1080p x265 10bit Joy)/ Hash:[202 209 169 251 3 69 24 240 175 230 210 7 240 212 108 240] Size:1063938250 ModTime:2020-10-09 16:54:19.369102461 +0530 IST IsCompressed:false IsEncrypted:false Symlink:}
[debug] 17:24:01 croc.go:1191: Her 2013 (1080p x265 10bit Joy).mkv cad1a9fb034518f0afe6d207f0d46cf0 cad1a9fb034518f0afe6d207f0d46cf0 <nil>
[debug] 17:24:01 croc.go:1195: hashes are equal cad1a9fb034518f0afe6d207f0d46cf0 == cad1a9fb034518f0afe6d207f0d46cf0
[debug] 17:24:01 croc.go:1078: finished
[debug] 17:24:01 message.go:43: writing finished message (encrypted)
[debug] 17:24:01 croc.go:1022: working on file 0
[debug] 17:24:01 comm.go:96: initial read error: EOF
[debug] 17:24:01 comm.go:96: initial read error: EOF
[debug] 17:24:01 comm.go:96: initial read error: EOF
[debug] 17:24:01 comm.go:96: initial read error: EOF
[debug] 17:24:02 croc.go:1101: converting to chunk range
[debug] 17:24:02 croc.go:1109: sending recipient ready with 0 chunks
[debug] 17:24:02 message.go:43: writing recipientready message (encrypted)
[debug] 17:24:02 message.go:43: writing finished message (encrypted)

Here is the proof of the disappointment

![Screenshot_2020-10-09-17-15-32-34_d5d9e833ce2a47bc1309ea2533a97fbc](https://user-images.githubusercontent.com/61350981/95580736-723c8980-0a55-11eb-89ac-e62c205eacbf.jpg)

This is a remoted into session so please excuse the aspect ratio of the display.

**Comment by schollz** [comment]
Is this problem consistent? Have you been able to reproduce it multiple times?

Are you using the public relay or is this transfer over LAN?

**Comment by roydev19** [comment]
Yes this issue is really consistent for all file sizes, but it is not noticeable for less than 500 MiB files, because well, it does not take much time.
I have reproduced it over Wired and Wireless connections using public relay, with multiple users.
As you can see is the image, the initial speeds during the transfers were pretty good (5-7 MBps) because the person on the receiving end was using a 100 Mbps connection.
But certainly almost always, I have had good speeds like these since the initial versions of croc, but the dropping of the speed was consistent in the entire version stack of croc.
I can even upload an recording of what I and the receiving party is doing during the transfer, if that would help you at all.
And finally the crashing, which consistently has a chance of happening during the slowdown, and almost never during the initial good speeds.
I first thought of it as a result of a spotty internet connection and ping losses.
But I again later, only to find upon checking that the pings are consistent almost always, and miniscule losses during the good or bad speeds, doesn't exactly trigger anything.  
Though I would like to note for you that, while using wired connections on both the ends gives quite stable over 10 MBps speeds (sometimes even showing up as high as 17MBps during peak) only to fall to speeds of less or equal to 1.5 MBps.
During wireless on both or either ends results in a way worse drop of less than 500 KBps.
These observations are consistent platform wise (Windows, Arch, Ubuntu).

**Comment by schollz** [comment]
So you are sending really big files, like gigabytes across the public relay? How long does it take before it crashes?

**Comment by roydev19** [comment]
As you can see, right around the 70 to 80 % mark.
Btw I would personally like to talk to you about further development and ideas.
Could you email me your discord id or something?

**Comment by schollz** [comment]
Sure, DM on twitter - https://twitter.com/yakczar

**Comment by roydev19** [comment]
Well I followed you but can't dm (Must be your privacy settings).
But I would like to inform about a discrepancy in my reports.
I tried the entire routine of transfer speeds check.
I was pretty much bamboozled with what I saw.
First of all, the above screenshot was from arch sending to windows.
But the croc package on aur has not been updated, causing it to be stuck at 8.3.2
Now, upon your newly released package, I tried everything out.
The recipient was on a wired connection and so was I on WIndows.
The speeds were just dead stuck at 800 KBps to 1.2 MBps.
Whereas on Arch (--v 8.3.2), it was providing above 3.5 mostly.
I thought maybe for my isp, 8.3.2 might optimized (of some sort)
But the entire thing remained the same across different versions, LAN, WLAN, on windows
The bamboozling part is, the arch machine is on a 2.4 ghz 75% connection, along with a measly network card.
I'm completely out of my mind, how could that be providing better speeds at all.
I would like to note that this was not an issue a month ago.
WIndows was always peaking at more than 10.
But right now, only arch has been able to be consistent.

**Comment by schollz** [comment]
This is not something I'm seeing at all, so I can't replicate. I tried using `v8.3.2` and it ran near exactly the same a the latest.

A simple guess is that the public server has gotten way more popular in the last few weeks and that the bandwidth is randomly getting limited.

**Comment by roydev19** [comment]
Okay if a public server is under pressure, would there be any way of actually use a different server(Maybe more switches and routers but maybe could add to stability)?

**Comment by schollz** [comment]
Yeah, you can host your own relay: https://github.com/schollz/croc#self-host-relay

**Comment by ericmjl** [comment]
Yes! @roydev19 setting up a relay on our internal servers was dead simple. Kudos @schollz! :tada: (I understand the frustrations that may come with not being able to replicate a problem; distributed systems and stuff "in the wild" is really hard!)

**Comment by roydev19** [comment]
> Yeah, you can host your own relay: https://github.com/schollz/croc#self-host-relay

Okay soo....
That worked good.
Umm, I'm completely satisfied and now all need is to keep that aws server up 😅.
But I still wanna ask, why the number of ports that can be used with croc is limited to 16?
Can it be just bumped up by any means?
