### ISSUE TITLE
UDP broadcast almost floods the network

### ISSUE THREAD

**Issue by AsafFisher** [schollz/croc#287]
reduce the amount of udp multicast packets sent to like idk `0.5`?
`croc version v8.0.12-7fd8fda`
btw does the discovery module works for macos? I have a feeling that not really...

**Comment by schollz** [comment]
This is how it works: https://github.com/schollz/peerdiscovery/

What do you mean floods the network?

**Comment by AsafFisher** [comment]
You broadcast too many udp packets... you should limit them even more... all device's traffic within one hop might be affected because of this...

**Comment by AsafFisher** [comment]
Have you tested it on `macOS `?

**Comment by schollz** [comment]
@AsafFisher I haven't tested on macOS. Is it not working on macOS?

**Comment by AsafFisher** [comment]
From the same computer two different processes it does not work, now I don't know if it is because IP_MULTICAST_LOOP is off or something else.. don't have VMware installed and proxy chains is annoying on macOS

**Comment by AsafFisher** [comment]
I tried to use multicast with rust... it seems to not work there with/without multicast loop on...

**Comment by AsafFisher** [comment]
Maybe macOS blocks it by default for apps with no permissions

**Comment by schollz** [comment]
@AsafFisher I managed to borrow two mac computers and it works fine with macOS. macOS does block apps from running but if you give the permission to run it should work no problem.

**Comment by AsafFisher** [comment]
Did you test it on on Big Sur?

**Comment by AsafFisher** [comment]
Btw open `wireshark` and sniff a bit... the amount of packets on `croc` is too much

**Comment by schollz** [comment]
For discovery it currently sends packets at speed of 100 packets/s. What speed would be considered normal?

**Comment by AsafFisher** [comment]
Whats the problem with 2 packets per second?

**Comment by schollz** [comment]
A faster packet rate means better responsiveness of croc.

To discover you would need to intercept a packet. That means the upperbound on discovery time is 1/rate. At 2 packets/s this means you could have to wait a half-second before discovery is initiated.

There probably is a good level but I'm not sure what it is. I never realized how big a impact 100packets/s could be.

**Comment by AsafFisher** [comment]
mmm then 10 packets/s?

**Comment by AsafFisher** [comment]
I mean human response time is 250ms...

**Comment by jathek** [comment]
Bumping because of the stale issue message. Also, echoing what @AsafFisher said, 10 packets/s seems reasonable. 100ms response time would still be over twice as fast as a human could notice.

**Comment by schollz** [comment]
please make pr
