### ISSUE TITLE
[feature request] File counter for folder transfers to show overall transfer progress

### ISSUE THREAD

**Issue by connect192168** [schollz/croc#288]
**Is your feature request related to a problem? Please describe.**
I transferred a folder with 7509 tiny files in it.
I had no clue how far done it was until it was done.

**Describe the solution you'd like**
A counter on the same line as each transferred file listing how many files have been transferred and how many there are in total.

**Describe alternatives you've considered**
Whatever seems like a reasonable way to show how many files have been transferred out of how many files will be transferred.

**Comment by schollz** [comment]
This would be a good feature, I've wanted this as well! I've got an idea of how to do it.
