### ISSUE TITLE
This project needs your help

### ISSUE THREAD

**Issue by schollz** [schollz/croc#289]
I started this project three years ago as a simple way for me to share files with friends.

Transferring file between any two networks is really easy, and it is made possible using a public relay server.

Maintaining the public relay server used to only costed $5/month for the past three years.

Now, the public relay server is costing me almost $25/month. The higher cost is enabling transfers for thousands of people around the world.

I can't maintain paying that much personally, so I would appreciate if you could [sponsor me](https://github.com/sponsors/schollz). Your sponsorship will go towards these costs.

**Comment by TheChiefMeat** [comment]
Hey man, I just updated my sponsorship from 1 dollar to 5. I know it's not much but I really hope it helps. Thanks again for your work on Croc :)

**Comment by schollz** [comment]
Actually, it helps *immensely*! Thank you SO much @TheChiefMeat

**Comment by TheFlipside** [comment]
I never heard of you before but when I saw the post on reddit I knew I had to help so I just initiated the 5$ tier sponsorship.

**Comment by schollz** [comment]
@TheFlipside Thank you SO much. Again, this is incredible help! 

I just got an email this morning from DO that they *undercharged* me and my bill this month will be over $30. Thanks to all your support I should be good to cover this! 

I'm hoping to get a few more supporters for when usage increases again next month. Thank you all!

**Comment by ProactiveServices** [comment]
Looks like DO offer open-source [sponsorship](https://airtable.com/shrbok3G7D5tk7b3S) and looking at [the details](https://docs.google.com/document/d/1P1ZqpxgKtiNibtWs53dLeCBmfp47Nqi6QlRg74lbsAc/edit) I reckon your project has a good chance to qualify.

**Comment by schollz** [comment]
Thanks @ProactiveServices. I didn't know about that. I've applied :) If I can get sponsored I would be really motivated to get GUI / Mobile support going. Currently I'm hesitant because wider adoption means more costs...

**Comment by ProactiveServices** [comment]
It wouldn't hurt to put a link to your GitHub Sponsor page in the README and  `--help` output. Might also help utilising a micropayment provider to let people offer one-off donations without them needing a GitHub account, too. As it is, only users coming here with a problem notice the donation request.

**Comment by schollz** [comment]
@ProactiveServices I now have a DigitalOcean grant for a year! This is fantastic because the usage keeps growing and so does the bill each month... I'm going to close this now since with everyone's support and DigitalOcean combined I have enough help to keep this project open for everyone to use easily. Thank you everyone SO much!!
