### ISSUE TITLE
Clean out old dangling receivers/senders every hour

### ISSUE THREAD

**Issue by schollz** [schollz/croc#29]
Basically we need another data type here: https://github.com/schollz/croc/blob/550bd9a8e62e05546d438e2c90aca1d033cce3c1/relay.go#L16. Basically a map[string]time.Time where each key is saved with an indicator of whether it is a "sender" or a "receiver" (e.g. "s"+key or "r"+key). Then make a new function that is a for loop that just erases each key in the map that is older than an hour. This function will run a goroutine in the background, forever.

Happy to support contributors, please don't hesitate to ask me questions.

**Comment by abinashmeher999** [comment]
Correct me if I am wrong. As I understand, you are trying to make the keys expire after an hour. So would making the key an object with TTL suffice?

**Comment by schollz** [comment]
Yep!

**Comment by abinashmeher999** [comment]
Are you open to using https://github.com/patrickmn/go-cache?

**Comment by schollz** [comment]
Sure that looks good!
