### ISSUE TITLE
Document the protocol(s)

### ISSUE THREAD

**Issue by piegamesde** [schollz/croc#290]
**Is your feature request related to a problem? Please describe.**

Magic wormhole has documentation for all of the communication protocols involved. It's not great, but still a lot better than nothing. It may server as base for new implementations and custom clients in other programming languages. It will also probably be a starting point for any security audits.

**Comment by schollz** [comment]
There's no documentation but luckily croc's code is very linear and essentially the entire protocol is in one file. You can follow the functions in here, e.g. for sending start with the Send function: https://github.com/schollz/croc/blob/master/src/croc/croc.go#L346

**Comment by piegamesde** [comment]
I've had a look at it, but I sadly didn't get very far. I don't know much about Go as well.

Maybe a short high-level writeup will get me started? I'm mainly interested in the folder transfer and resumption logic.
