### ISSUE TITLE
Support multiple pre-configured relays

### ISSUE THREAD

**Issue by maximbaz** [schollz/croc#294]
I'm using multiple relays depending on who I'm sending to or receiving files from. For example if I send a file to myself I might use my own relay, if someone sends a file to me they might use their own relay, but I can also imagine in some cases there is a need to use a dedicated relay that is not to be used for other reasons (maybe due to some particular restrictions, e.g. work vs personal use).

The current design of configuration files allows you to have two files, `send.json` and `receive.json`, where you can put most commonly used relay configs for sending and receiving respectively. This already helps, but is not very convenient once you must use another relay, because you either need to edit the file, or provide both relay address and password on CLI.

What if there was another file, say `relay.json`, with a list of relays and their corresponding settings (unique ID, addresses, ports, passwords), and then `send.json` and `receive.json` would just reference to those definitions and only specify the default relay to use for sending and receiving files.

Then, if I want to send using the default relay as configured in `send.json`, I would just do `croc send myfile.txt`

If I want to send using a custom relay, I would specify it via CLI flag, maybe like `croc --relay john send myfile.txt` and `croc` will find this relay in the config and use all corresponding values for a relay with ID `john` (address, password).

When you send a file, `croc` prints a command to run on the receiving end, and it already today specifies the relay, like `croc --relay <relay-address> some-code-word`. This could be changed to use relay ID instead, and again, when I execute this command, I again don't want to type relay address and password in the CLI, instead I would much prefer `croc` to match this relay ID to the corresponding relay configuration in `relay.json`.

What do you think?

(it doesn't have to be a separate `relay.json` file, we could totally duplicate the relay configs in the existing json files if that is simpler)

**Comment by schollz** [comment]
I think that sounds great. A `relay.json` is totally fine, that may be the easiest way to implement. If you want to submit this is a PR, I will definitely accept!

**Comment by maximbaz** [comment]
I think the change itself is quite simple, but the most challenging part here is backwards compatibility, how much do you want of it? 

Both in terms of a client app... (say you had your relay settings configured in `send.json`, and now all those fields are no longer read, is it okay to ask user to manually re-configure their stuff in a new `relay.json` file (or using `--remember`), or do you want some sort of migration, where `croc` will try to create `relay.json` based on what it sees in `send.json` and `receive.json`?)

... and in terms of cross-client compatibility (say I have updated my local `croc`, and when I do `croc send` it tells me a command for receiving end where `--relay` is an ID and not IP address or hostname, but on the receiving end they still use older `croc` which doesn't understand IDs in `--relay` field, is it okay to expect users to realize this themselves?)

If we don't deal with backwards compatibility, would you want to simply bump major version, so that it's clearer to users that _something_ has changed?

**Comment by ProactiveServices** [comment]
To jump on this bandwagon - it would be handy if the user could use `--relay none` and `--relay default` to use no relays or the default relay, respectively.

**Comment by roomcays** [comment]
It would be very nice feature to be able to choose **croc** configuration from CLI when running (thanks to self-hosting possibility I do have couple of relays for different "environments" and I end up with manipulating files from under `~/.config/croc` manually :( ).

**Comment by Cyb10101** [comment]
I also think that's a nice idea. You would have several relays and could, for example, switch between the public server, the private server and a company server.

Sometimes I'm a little paranoid and wouldn't like to give strangers my relay password.
The good question is whether it is really necessary to need a relay password when receiving?
The recipient would not be able to send via this server, but he could receive the file without a relay password.
At least if I don't misunderstand how croc works.

```bash
croc --relay "example.org" --pass="relay-password" send <file>
croc --relay "example.org" <code>
```

If you can't find a solution for this, there is of course also the option of creating a small script, a function or an alias. It may not be pretty, but it works.

**Linux:**

```bash
alias crocAppSend='croc --relay "example.org" --pass="relay-password" send'
crocAppSend <files>
```

**Windows:**

Add a new file:

```shell
# Set execution policy to allow user script
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

# Add a new file
if (!(Test-Path $PROFILE.CurrentUserCurrentHost)) {
    New-Item -ItemType File -Path $PROFILE.CurrentUserCurrentHost -Force
}

# Edit file
notepad $PROFILE.CurrentUserCurrentHost
```

File `$PROFILE.CurrentUserCurrentHost`:

```shell
function crocAppSend {
    $defaultArguments = @('--relay', 'example.org', '--pass', 'relay-password', 'send')
    $arguments = $defaultArguments + $args
    & C:\Users\$env:username\scoop\apps\croc\current\croc $arguments
}
```

Run `crocAppSend <files>`.
