### ISSUE TITLE
Missing Relay6 option in config files

### ISSUE THREAD

**Issue by maximbaz** [schollz/croc#295]
Was just testing out the recent IPv6 changes, good job! I noticed `Relay6` option in `send.json` / `receive.json` is missing, I think it should be added just like here?

https://github.com/schollz/croc/blob/23f97c61ac91a86a4734757693ac3bc247c59231/src/cli/cli.go#L200-L202

Also just a few observations while looking at the code, in the actual transfer it seems you prioritize IPv6 (which is good!):

https://github.com/schollz/croc/blob/bf9ebfc4b4e79f57eb2a809c3b6980139e9aaaad/src/croc/croc.go#L384

But here it looks like if you specify both CLI options `--relay` and `--relay6`, the IPv4 is being prioritized? Should this condition be swapped?

https://github.com/schollz/croc/blob/23f97c61ac91a86a4734757693ac3bc247c59231/src/cli/cli.go#L186-L190

**Comment by schollz** [comment]
Ay! Those are both issues that can be fixed. Do you want to submit a PR? I can also fix them too if you don't have the time.

**Comment by maximbaz** [comment]
Feel free to fix them if you have a chance or feel like it, otherwise I think I'll be able to do it on weekends 😉
