### ISSUE TITLE
when is send big file this issue occoured!

### ISSUE THREAD

**Issue by bigo2050** [schollz/croc#299]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version**
Check `croc -version` and report it.
meteor-bootstrap-os.linux.x86_64.tar.gz  65% |█████████████       | (165/250 MB, 29.738 kB/s) [19m13s:48m50s]panic: wanted to write 32814 but wrote 2096: write tcp 172.16.95.215:43868->142.91.187.120:9012: write: broken pipe

goroutine 61 [running]:
github.com/schollz/croc/v8/src/croc.(*Client).sendData(0xc0000a5860, 0x2)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1432 +0x7b3
created by github.com/schollz/croc/v8/src/croc.(*Client).updateState
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1270 +0x354
**Additional context**

**Comment by schollz** [comment]
How often does this error occur? Is it reproducible? Which version are you using?
