### ISSUE TITLE
Work without sudo

### ISSUE THREAD

**Issue by GrbavaCigla** [schollz/croc#300]
**Is your feature request related to a problem? Please describe.**
I can't install it because i don't have sudo installed. I have doas installed (gentoo)

**Describe the solution you'd like**
doas support would be awesome

**Describe alternatives you've considered**
Use `su -c "command"` instead of sudo

**Comment by schollz** [comment]
In that case, can you install by downloading the binary directly?

**Comment by GrbavaCigla** [comment]
Didn't notice I can install it with portage, I am going to check

**Comment by GrbavaCigla** [comment]
It works with gentoo official. Closing this.
