### ISSUE TITLE
Use device's configured DNS servers instead of hardcoded DNS

### ISSUE THREAD

**Issue by ProactiveServices** [schollz/croc#301]
Hi, I noticed that Google's DNS servers have now been [hardcoded into croc](https://github.com/schollz/croc/commit/dbc4a08ad078baec5d7c711999c2d20751f2c014). I avoid exfiltration to third-party DNS as well as Google as far as I can and would much prefer that croc sticks to the device's configured DNS servers. Would it be possible to make Google DNS optional with a switch?

**Comment by schollz** [comment]
Sure. Actually its not hardcoded to Google, its using Cloudflare's: https://github.com/schollz/croc/blob/master/src/models/constants.go#L43

**Comment by ProactiveServices** [comment]
Whoops, I was looking at the wrong commit :-)
Thanks!
