### ISSUE TITLE
After connecting to WiFi, the command runs slowly

### ISSUE THREAD

**Issue by hjldev** [schollz/croc#305]
After connecting to WiFi, the command runs very slowly. You have to wait about 20 seconds for the command to respond. After the WiFi connection is disconnected, the command will execute quickly. And two computers under the same WiFi cannot transfer files to each other.

croc version v8.6.6-e7ed4fc

**Comment by schollz** [comment]
Can you run with --debug and share the output

**Comment by hjldev** [comment]
output:
`[debug]	09:30:33 cli.go:142: debug mode on
[debug]	09:30:33 croc.go:156: options: {IsSender:false SharedSecret:true-send-gf Debug:true RelayAddress: RelayAddress6: RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false Ask:false SendingText:false NoCompress:false}
connecting...[debug]	09:30:33 croc.go:495: attempt to discover peers
[debug]	09:30:33 croc.go:557: discoveries: []
[debug]	09:30:33 croc.go:558: establishing connection
[debug]	09:30:33 croc.go:586: could not connect to : found no addresses to connect
could not connect to : found no addresses to connect`

I'm connected to WiFi, and the two computers can ping each other
