### ISSUE TITLE
File Size Mismatch (GiB vs GB)

### ISSUE THREAD

**Issue by hillmarcus** [schollz/croc#306]
**Issue**
Noticed this issue today. When beginning the transfer of a file the user is prompted with a message that includes the file's size. That size is given as a number of bytes using groupings of 1000, e.g. 1000 bytes in 1 kB. The progress bar that is displayed during the transfer makes use of another one of @schollz project's. That project displays a file's size using groupings of 1024, e.g. 1024 bytes in 1 kB. This causes the two file sizes displayed to be different.

**Proposed Fix**
The simplest fix would likely be to simply change the appropriate line (see below) from `1000` to `1024`.

https://github.com/schollz/croc/blob/5978896936b2995fb5590732a805c3658b064136/src/utils/utils.go#L139

**Comment by schollz** [comment]
Great find! Would you be interested in making a PR?
