### ISSUE TITLE
croc freezes on debian 10. 

### ISSUE THREAD

**Issue by blackball** [schollz/croc#308]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**
Installed using the command line from README.md on my debian 10 box. After the installation, "croc" stuck forever. 

**Version**
The latest version.

**Comment by schollz** [comment]
Can you run `--debug` and show the output?

**Comment by blackball** [comment]
I can't reproduce it with current version now. close.
