### ISSUE TITLE
Full path on cli output for multiple file transfer

### ISSUE THREAD

**Issue by GambolingPangolin** [schollz/croc#309]
**Is your feature request related to a problem? Please describe.**
The first time I used `croc` to transfer a folder, I canceled the transfer based on the terminal output so that I could retry in a folder.  Then I found that `croc` had indeed created a folder already.

**Describe the solution you'd like**
I would like to see a representation of the destination such as `./folder/file` or `./fol.../file` for long paths.

**Describe alternatives you've considered**
Another possibility is to write out the folder before the series of file transfer progress bars, perhaps similar to `tree`.  This is more complicated and visually noisy, compared to the above.

**Comments**
This is a stellar project!  Great work.  I would be happy to implement this change if it welcome in some form.

**Comment by schollz** [comment]
Yeah, if you want to give this a shot I will support you.
