### ISSUE TITLE
Could not connect to: found no addresses to connect

### ISSUE THREAD

**Issue by orezraey** [schollz/croc#311]
![photo_2021-01-02_03-09-19](https://user-images.githubusercontent.com/49327055/103451958-0a3ebd80-4ca9-11eb-8a9e-75145fadeee0.jpg)
![photo_2021-01-02_03-09-18](https://user-images.githubusercontent.com/49327055/103451960-0c088100-4ca9-11eb-8b3a-cf091e063b53.jpg)

My friend is not able to send/receive files to me, he is using the Termux, 

open the thermux
type croc send [file]
nothing happens
gives error

**Version**
croc version v8.6.7-05640cd

**Additional context**
When he installed the thermux, he gave the following commands: apt update && apt upgrade, termux-setup-storage, pkg install croc

**Comment by schollz** [comment]
Can you run `--debug` and share the output?

Also, your example doesn't have matching codephrases...

**Comment by dadigang** [comment]
the same question
