### ISSUE TITLE
Can we keep text option open and not quit the command and keep sending and replying of the messages

### ISSUE THREAD

**Issue by askaaqib** [schollz/croc#314]
Can we keep text option open and not quit the command and keep sending and replying of the messages

**Comment by schollz** [comment]
that is a bit out of scope for croc - its meant for one-time transfer and the sender needs to initiate (versus having the receiver become ready first).

**Comment by askaaqib** [comment]
Thanks!!

**Comment by askaaqib** [comment]
Thanks!!
