### ISSUE TITLE
[idea] Separate "Dyn-Dns"

### ISSUE THREAD

**Issue by kollokollo** [schollz/croc#316]
I have an idea (maybe for a new project): The feature of croc, that it can copy files from behind firewalls and from inside local networks accross all boundaries could be used to improve the WWW (or the gemini protocol). Instead of copying files, one could copy web pages or gemini content from "servers" behind walls. This allows millions of users to host their own page without the need for central hosting (like Facebook etc). Everyone could host their pages on their own devices. 

This is like dyn-dns and some improvements in standards for URI / URL need to be defined, but at the end, the same technique like croc could be used. The "croc-servers" could act like dyn-dns-servers and brokers for connections. The connections themselves would be p2p.  What do you think?

**Comment by okdistribute** [comment]
Hey @kollokollo that sounds a lot like https://beakerbrowser.com or https://github.com/equalitie/ouinet, what do you think?

**Comment by kollokollo** [comment]
Yes, thank you! interesting. I did not know about these projects. Yes something like this came into my mind. So my idea was not so revolutionary however...

**Comment by okdistribute** [comment]
@kollokollo yes I agree, ouinet is pretty extreme in it's use case for privacy, most users don't need that level of anonymity so something a little more simple would be worth exploring!
