### ISSUE TITLE
Docker images for multiple platforms

### ISSUE THREAD

**Issue by Spaceface16518** [schollz/croc#317]
**Is your feature request related to a problem? Please describe.**
I'm trying to host a croc relay for my home network using docker on a raspberry pi `linux/arm/v8`, but only `linux/amd64` is available.

**Describe the solution you'd like**
Docker images for more platforms available on Docker Hub or the GitHub Package Registry.

**Describe alternatives you've considered**
I'm currently just pulling the repository and building it on the raspberry pi itself.

**Additional context**
Since this repository is hosted on GitHub, it would be easy to set up a Travis build or GitHub Actions workflow to push multi-arch builds to any registry.

I have set this up for many of my personal projects. I'd be happy to open a PR with these changes.

**Comment by schollz** [comment]
Would take a PR for this!

**Comment by Spaceface16518** [comment]
Will do! I just need a little information so I can make the right changes.

1. Should CD be hosted on **Travis or GitHub Actions**?
2. Should images be published to **Docker Hub or GitHub Container Registry**?
3. Do you have a list of **platforms** that images should be built for (e.g. all possible linux platforms), or should it just be built for every possible platform (including windows)?
4. Which of the following should trigger a **deployment**?
    - [ ] Push to master (e.g.  `schollz/croc:sha-4d65c7b`)
    - [ ] Release/tag (e.g. `schollz/croc:8.6.7`)
5. Which of the following should be **automatically tagged**?
    - [ ] Latest release (e.g. `schollz/croc:latest`)
    - [ ] Master branch (e.g. `schollz/croc:edge`)
    - [ ] Latest major/minor version (e.g. `schollz/croc:8.6` or `schollz/croc:8`)

**Comment by schollz** [comment]
1. Either! I have Travis setup but don't mind setting up Github Actions
2. Docker Hub is probably best, that's what I already use.
3. All linux platforms are fine
4. Push to master should trigger
5. latest should be tagged

**Comment by Spaceface16518** [comment]
@schollz I know this was closed, but do remember that the workflow still won't tag `latest` or released versions, as #242 requests. It seems that you manually pushed `schollz/croc:latest`, but I'd be happy to integrate this into the workflow.
