### ISSUE TITLE
Delta sync

### ISSUE THREAD

**Issue by luckymedog** [schollz/croc#320]
Could croc do delta-transfer sync of large files like rsync?

**Comment by schollz** [comment]
Yes, I think it could.

Right now it only does delta-transfer when resuming files. But I'll look into having it do it for any file.

**Comment by schollz** [comment]
Do you have a specific use-case in mind @luckymedog ?

**Comment by luckymedog** [comment]
> Do you have a specific use-case in mind @luckymedog ?

Yes, every week I transfer large +1gb gpgtar files (these files get only minor changes) to a remote location and need this functionality to save bandwidth

**Comment by schollz** [comment]
How does gpgtar work? Is it like just appending new encrypted data to the end? Or is the whole thing re-encrypted each time?

**Comment by luckymedog** [comment]
The latter in my use case.

**Comment by schollz** [comment]
If the whole thing is re-encrypted then how can a diff be calculated?

**Comment by dlong500** [comment]
@schollz was this ever addressed?  I don't see anything about delta syncing in a search of the repo.  I think that would be a great feature for a couple different use cases:
1) Something went wrong with a transfer or a file got corrupted, so a delta sync could "fix" a file on the receiving side without having to do a full transfer.
2) Someone might have a very large file or file set that gets modified on a regular basis but only small parts of the files are modified, so a sync transfer would be able to update the recipient copy efficiently.

**Comment by schollz** [comment]
Yes 

<img width="909" height="412" alt="Image" src="https://github.com/user-attachments/assets/b32d21e6-716e-49be-896a-c57e649903db" />
