### ISSUE TITLE
Permission denied error in GCP Ubuntu

### ISSUE THREAD

**Issue by qogusdn1017** [schollz/croc#324]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**

- Croc just throws Permission denied error even I have set the directory permission in it.

**To Reproduce**

1. Send file from somewhere
2. Use GCP VM croc to get the file
3. Permission denied error follows.

- 

https://user-images.githubusercontent.com/36562850/106432585-459ff800-64b2-11eb-975a-6b861601d241.mp4

**Expected behavior**

File must have sent at the VM.

**Version**
Check `croc -version` and report it.

> croc version v8.0.12-7fd8fda

**Additional context**

- None

**Comment by schollz** [comment]
Are you using snap to install croc?

**Comment by qogusdn1017** [comment]
> Are you using snap to install croc?

Currently, yes. Because apt does not work.

Do I must download it from releases?

**Comment by schollz** [comment]
There are many ways to install: https://github.com/schollz/croc/#install

I've removed snap from the list because it constantly has [problems](https://github.com/schollz/croc/issues/190#issuecomment-628696061) and the only solution snap suggested was to [change croc behavior if it is a snap](https://forum.snapcraft.io/t/croc-needs-permission-for-dotfiles-in-home/17424/10) which I think is ridiculous.

**Comment by qogusdn1017** [comment]
> There are many ways to install: https://github.com/schollz/croc/#install
> 
> I've removed snap from the list because it constantly has [problems](https://github.com/schollz/croc/issues/190#issuecomment-628696061) and the only solution snap suggested was to [change croc behavior if it is a snap](https://forum.snapcraft.io/t/croc-needs-permission-for-dotfiles-in-home/17424/10) which I think is ridiculous.

Oops, I didn't know about that!

Sorry if I distrubed you so much. :( I think I need to close this issue and try again with the latest version of croc.

Well I can't understand with the snap too. **It is** really ridiculous huh...

Since I have downloaded from snap I thought the snap croc version is the latest version.
Forgive me about it.

(P.S. if you habe enough time, can you watch my enhancement or idea issue?)

Thanks for your kind reply.

**Comment by qogusdn1017** [comment]
Closed the issue; current question resolved. Will test later if I have a time.

Thanks again!
