### ISSUE TITLE
Autocomplete does not install while in root

### ISSUE THREAD

**Issue by SBado** [schollz/croc#326]
**Describe the bug**
Linux installer gives error if launched as root.

**To Reproduce**
1. Launch installer as root (e.g. sudo curl https://getcroc.schollz.com | bash)
2. You will see the error "== Failed to install bash_autocomplete"

**Expected behavior**
The installer completes without errors

**Version**
croc version v8.6.7-05640cd

**Additional context**
This is not a fresh install, I'm trying to update an older version of croc.

The problem seems to be in function install_file_linux:

```
install_file_linux() {
  local file
  local prefix
  local rcode

  file="${1}"
  prefix="${2}"

  if command -v install >/dev/null 2>&1; then
    if [[ "${EUID}" == "0" ]]; then
      install -C -b -S '_old' -m 755 -t "${prefix}" "${file}"  <-- THIS DOESN'T WORK
      rcode="${?}"
    else
      if command -v sudo >/dev/null 2>&1; then
        sudo install -C -b -S '_old' -m 755 "${file}" "${prefix}"  <-- THIS WORKS
        rcode="${?}"
      elif [[ "${ANDROID_ROOT}" != "" ]]; then
        install -C -b -S '_old' -m 755 -t "${prefix}" "${file}"
        rcode="${?}"
      else
        rcode="21"
      fi
    fi
  else
    rcode="20"
  fi

  return "${rcode}"
}
```

To fix the error, I have to change
**install -C -b -S '_old' -m 755 -t "${prefix}" "${file}"**
to 
**install -C -b -S '_old' -m 755 "${file}" "${prefix}"**

**Comment by schollz** [comment]
Do you use autocomplete with croc while in root mode?

**Comment by SBado** [comment]
Tbh, no, because I don't know why but autocomplete is painfully slow for me.
I'm just trying to update croc automatically using Huginn (hence the need to run the installer with sudo) and I saw this error during my tests.

**Comment by schollz** [comment]
Ok. I guess the error should be that the installer doesn't install autocomplete correctly while in root. I tried it and it works fine to install croc though. I'll change the header and wait to see if others have the issue

**Comment by qogusdn1017** [comment]
I have the same message while installing cric in curl, but I haven't tested autocompletion yet. How do I test it?

**Comment by avimar** [comment]
```
install: failed to access '/etc/bash_completion.d/croc': No such file or directory
== Failed to install bash_autocomplete
```

The bash_autocomplete install is failing. It looks like croc is expecting the directory `/etc/bash_completion.d/croc` to exist. Looks like it needs to be created first. If I create it manually, then it creates a file `bash_autocomplete` inside the croc folder.

**Comment by qogusdn1017** [comment]
oh that's the problem
