### ISSUE TITLE
Show a checksum of file on both machines after transfer

### ISSUE THREAD

**Issue by ProducerMatt** [schollz/croc#327]
After transfer is finished, I think it would be good to automatically show a checksum of the file by an identicon, on both sender and receiver. This makes it easy to notice a (hypothetical) man-in-the-middle attack, by comparing the identicons of sender and receiver out-of-band.

Here's a mock-up using OpenSSH's identicons.

```
$ croc send croc.go                                                                                             
+----[croc.go]----+
|       .++       |
|       .+..     .|
|     . .   . . ..|
|    . .     .E.. |
|     ...S     .  |
|      o+.        |
|     +..o        |
|  o B .o.        |
| . + +..         |
+-----[SHA512]----+
Sending 'croc.go' (39.9 kB)
Code is: complex-eric-profile
On the other computer run

croc complex-eric-profile
```
```
$ croc complex-eric-profile
Accept 'croc.go' (39.9 kB)? (y/n) y

Receiving (<-127.0.0.1:14051)
+----[croc.go]----+
|       .++       |
|       .+..     .|
|     . .   . . ..|
|    . .     .E.. |
|     ...S     .  |
|      o+.        |
|     +..o        |
|  o B .o.        |
| . + +..         |
+-----[SHA512]----+
```

Here's an example implementation of these identicons in python: https://github.com/thcipriani/slime-bishop

Hopefully you like this idea. I know that 1. MITM is a hypothetical and 2. this process could be done manually by those security-minded. So I totally understand if you said "do it your own self". But making it integrated and convenient encourages users to go the extra mile where they wouldn't otherwise, so I figured why not suggest it.

Thank you very much for this awesome program, I'd have it integrated on every platform if I could.

**Comment by szpak** [comment]
4+ people are sad after that closure :-/
