### ISSUE TITLE
Allow sending of directories

### ISSUE THREAD

**Issue by schollz** [schollz/croc#33]
When specified `-send FILE` its possible that `FILE` is a directory, in which *croc* should zip the directory and transfer it as a zipped file. This is pretty easy to implement.

First it should check if `flags.File` is actually a directory, after this line: https://github.com/schollz/croc/blob/17d7b76f08e5e7025dd5fde92b5b6a3ef8ca7f82/connect.go#L51.

If it is a directory, then it should zipped it into a local temporary `.zip` file. Then change `flags.File` to the new `.zip` file and set a new `FileMetaData` variable `IsDir` (which will need to be created [here](https://github.com/schollz/croc/blob/master/connect.go#L35)) to true.

For zipping, I recommend [using mholt/archiver](https://github.com/mholt/archiver#library-use).

After this, then we can implement receiving the directory #34.

**Comment by jesuiscamille** [comment]
I'll take it =)

**Comment by schollz** [comment]
You got it! Let me know if you have any questions at all.

**Comment by schollz** [comment]
https://github.com/schollz/croc/pull/35
