### ISSUE TITLE
Croc hangs indefinitely on ubuntu and debian

### ISSUE THREAD

**Issue by lhcamilo** [schollz/croc#330]
croc seems to freeze (indefinitely) for me on ubuntu 16.04/18.04/20.04

I am not using the snap, but rather the latest repo version v8.6.7. Previous versions, v8.0.11-78b6437 for instance,  do not have this bug.

As far as I can tell it freezes for any command, 

    croc --version

also freezes in the latest version.

**Comment by schollz** [comment]
see #329
