### ISSUE TITLE
Search our xdg specs first and then fallback to default directory.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [schollz/croc#332]
Hi! First let me say thanks!
`croc` is the best transfer utility going (I used to use Python "magic wormhole"), this works even better. Faster, simpler, more portable.
(Just saw the Android app... written in `Go` too! 😱 ).
Anyways... `croc` is the only utility I use that isnt following my `xdg` specs, others search for the existence of  `$XDG_CONFIG_HOME` before they touch the system (`$HOME/.config`) first, because of this I have a `.conf` and also a `.config` directory ( that only contains `croc`).

**Comment by schollz** [comment]
This is fixed now, thanks @jfaltis
