### ISSUE TITLE
Support authenticated SOCKS5

### ISSUE THREAD

**Issue by tdussa** [schollz/croc#333]
For obvious security reasons, I'd prefer to configure my SOCKS5 proxy to require authentication rather than allow anonymous use.  However, as far as I can see by reading the manuals, the code, and testing, `croc` only supports unauthenticated SOCKS5 use.

As far as I can tell, Go supports authentication for SOCKS5 as well, but it would require a few lines of code to add the proper parameters.

**Comment by schollz** [comment]
Happy to accept a PR for this!

**Comment by tdussa** [comment]
My friend Heiko thankfully quickly wrote the necessary changes after a quick discussion with me, as I am not the Go hacker, but he is. :) His PR fixes the issue.

**Comment by schollz** [comment]
add in v8.6.10! thanks @tdussa and @hreese
