### ISSUE TITLE
Systemd hardening

### ISSUE THREAD

**Issue by ju1m** [schollz/croc#335]
**Is your feature request related to a problem? Please describe.**
[croc.service](https://github.com/schollz/croc/blob/master/croc.service) for `systemd` could be hardened more, see `systemd-analyze security croc`.

**Describe the solution you'd like**
See https://github.com/NixOS/nixpkgs/pull/93629 for an example of a more elaborated/hardened `systemd` setup for `croc`.
And https://github.com/NixOS/nixpkgs/pull/93629#issuecomment-781649025 for a few ideas about which settings could be set upstream.

**Describe alternatives you've considered**
Linking back in `croc`'s documentation to NixOS' systemd service for `croc` as an example for a more elaborated/hardened service config.

**Additional context**

**Comment by ProactiveServices** [comment]
@ju1m testing of pull #303 is welcomed.
