### ISSUE TITLE
Allow receiving directories

### ISSUE THREAD

**Issue by schollz** [schollz/croc#34]
First #33 should be done.

After downloading the file (after [this line](https://github.com/schollz/croc/blob/master/connect.go#L344)) there should be an `if`-statement to check whether the `c.File.IsDir == true`. If so, then it needs to be untarred and decompressed. This will depend on what #33 uses, but again I suggest using [mholt/archiver](https://github.com/mholt/archiver#library-use).

**Comment by jesuiscamille** [comment]
Working on it too :)
