### ISSUE TITLE
croc stops at FUTEX_WAIT_PRIVATE

### ISSUE THREAD

**Issue by SanskritFritz** [schollz/croc#350]
On Archlinux behind corporate firewall croc simply hangs without any further action. Strace tail:
```
readlinkat(AT_FDCWD, "/proc/self/exe", "/usr/bin/croc", 128) = 13
fcntl(0, F_GETFL)                       = 0x2 (flags O_RDWR)
futex(0xc00003c950, FUTEX_WAKE_PRIVATE, 1) = 1
fcntl(1, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(2, F_GETFL)                       = 0x2 (flags O_RDWR)
futex(0xc000080150, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00003c950, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x562907743210, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
```
and all output stops here until a 40 sec timeout where it repeats the last 3 lines.
Do you need full strace log? I don't know what else I can provide to help.

UPDATE: ```croc --debug``` outputs absolutely nothing.

UPDATE2: On my home box which has same Archlinux installed (same version, etc), croc works flawlessly.

**Comment by schollz** [comment]
I think this will fix the issue: https://github.com/schollz/croc/commit/a9d582cc6a7f8246b3c03a15eab7b40d02db7e70

Try the latest version (v8.6.12) which has that change and let me know.

**Comment by SanskritFritz** [comment]
Thank you, that version works.
_(Well not for me, because the aforementioned corporate firewall cuts the communication to port 9009 even through my socks5 proxy, but that's definitely not something you can do about :smile: )._
