### ISSUE TITLE
Add Switch for no-overwrite/overwrite behaviour

### ISSUE THREAD

**Issue by stellarpower** [schollz/croc#354]
I'm always transferring files between my own machines, and as such, I can use `croc --yes` to avoid the prompt to confirm receipt of the files. However, it would be useful to have a switch that will prevent overwriting of existing files (or possibly more complex overwrite behaviour such as aways overwite, never overwrite, always prompt, overwrite if newer, etc.)

**Comment by schollz** [comment]
Happy to accept a PR for this.

**Comment by schollz** [comment]
Its done now in v9
