### ISSUE TITLE
Hangs in Git Bash

### ISSUE THREAD

**Issue by mattrochon** [schollz/croc#356]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**
Installed the app with scoop in powershell, but usually i use git bach for all cli in windows. all croc commands just hang in git bash

**To Reproduce**
1. Install croc on windows
2. open git bash
3. croc send --text "hello"
4. observe it hanging

**Expected behavior**
Should not hang

**Version**
$ croc --version
croc version v8.6.12-c373b38

**Comment by martinscholz83** [comment]
Try with `--ignore-stdin`. Works for me.
