### ISSUE TITLE
"room not ready" in Termux

### ISSUE THREAD

**Issue by mizzunet** [schollz/croc#358]
**Describe the bug**
Cannot start sharing as it returns "room not ready" in Termux

**To Reproduce**
1. Open Termux
2. Install croc
3. Try send any file by 'croc file' and 'y' for prompt asking if to send

**Expected behavior**
Should return code-phrase 

**Version**
croc version v8.6.7-05640cd
**Additional context**
And it works by 'croc send file' flawlessly. BTW, @howeyc has made an android GUI app for croc and it works, https://github.com/howeyc/crocgui

**Comment by schollz** [comment]
Can you upgrade to the latest version?

**Comment by mizzunet** [comment]
> Can you upgrade to the latest version?



> Can you upgrade to the latest version?

Oh my bad, it started working once I cleared data of Termux. And "pkg install croc" installs version v8.6.7-05640cd, not the latest one.
