### ISSUE TITLE
Make output more explicit for already-existing files

### ISSUE THREAD

**Issue by tdussa** [schollz/croc#367]
`croc` (version v8.6.12-c373b38) detects if a file is already present on the receiving side, and if it decides the file is already there, it does not retransmit.  However, this is done silently, and no output whatsoever is given.  It would be good to indicate the fact that `croc` thinks a file is already present both to the sender and to the receiver if only to indicate that nothing bad has happened.

Example:

On the sender side:
```
~/croctest/send $ echo A > a
~/croctest/send $ croc send a 
Sending 'a' (2 B)
Code is: galaxy-cheese-simon
On the other computer run

croc galaxy-cheese-simon

Sending (->192.168.101.108:52660)
 100% |████████████████████| ( 2/ 2B, 1.501 kB/s)
~/croctest/send $ croc send a
Sending 'a' (2 B)
Code is: bonus-heavy-nobel
On the other computer run

croc bonus-heavy-nobel
```

On the receiving side:
```
~/croctest/receive $ croc galaxy-cheese-simon
Accept 'a' (2 B)? (y/n) y

Receiving (<-[::1]:50914)
 100% |████████████████████| ( 2/ 2B, 0.698 kB/s)
~/croctest/receive $ croc bonus-heavy-nobel 
Accept 'a' (2 B)? (y/n) y

Receiving (<-[::1]:50958)
```

In the second transfer, it would be good to have some output like `file already present, not transferring again` or something along those lines in both the sending and receiving side's output.

**Comment by schollz** [comment]
This is already been implemented in v9
