### ISSUE TITLE
Croc latest version not availaible on chocolatey

### ISSUE THREAD

**Issue by Phoenix4745** [schollz/croc#372]
Sir Please provide croc version 9.0.0 on chocolatey.

**Comment by schollz** [comment]
@TheChiefMeat could you update https://community.chocolatey.org/packages/croc ?

**Comment by TheChiefMeat** [comment]
All done. I've added a notification for myself when new versions go live so I can update it quicker.

**Comment by Phoenix4745** [comment]
Thanks
