### ISSUE TITLE
Croc not working

### ISSUE THREAD

**Issue by Phoenix4745** [schollz/croc#373]
Earlier it worked very well but today when I used it, it showed me connection closed by remote host. What can be solution to this? Any help would be deeply appreciated.

**Comment by schollz** [comment]
What version? Run with --debug and share output.

**Comment by Phoenix4745** [comment]
v 8.6.12. Can it transfer files of 8 gb because it transferred smaller file.

**Comment by schollz** [comment]
Try upgrading

**Comment by Phoenix4745** [comment]
Latest version not on chocolatey

**Comment by schollz** [comment]
Okay, there's already an issue for that, so I'll close this.

v8 and v9 are not compatible. 

If you want to try without choco, you can just download the windows version [here](https://github.com/schollz/croc/releases/latest).

**Comment by Phoenix4745** [comment]
Thanks Zack You have done a wonderful job by creating croc. Why don't you make a brave creators account I would like to tip you.

**Comment by schollz** [comment]
@Phoenix4745 Please consider supporting me by becoming a sponsor: https://github.com/sponsors/schollz. There is a $1 tier. Every bit helps and GH matches.
