### ISSUE TITLE
Console progress is flickering

### ISSUE THREAD

**Issue by Tragen** [schollz/croc#381]
## Describe the bug
When a file is transfered on windows, the line with the progress is flickering a lot

## Version
Windows 9.1.0 x64

The gif is very slow flickering compared to the real console

![2021-04-23_18-17-01](https://user-images.githubusercontent.com/1700241/115900584-66983980-a460-11eb-9f77-f9bc2d03e14e.gif)

**Comment by schollz** [comment]
This is probably a progressbar issue. Maybe its refreshing too much.

What console (powershell/ cmder/etc)?

**Comment by Tragen** [comment]
I'm using cmd in this case.

**Comment by schollz** [comment]
Does it happen if you use Powershell?

**Comment by aashwin-rs** [comment]
The flickering seems to also happen on Powershell (I'm using 7.1.3)

**Comment by schollz** [comment]
@aashwin-rs you are using an older version of croc? try upgrading.

**Comment by SinTan1729** [comment]
I'm facing this issue on Linux using `fish` shell on Alacritty terminal with croc version `v9.6.1-b27982a`.
