### ISSUE TITLE
UX regression for croc send --text

### ISSUE THREAD

**Issue by wamserma** [schollz/croc#384]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
With croc 9.1.0:

When using `croc send --text` the recipient is asked whether the temporary file for buffering may be overwritten, so `--overwrite` must be given for non-interactive use. This is a UX regression from croc 8.

## To Reproduce (e.g. in bash)

1. `croc relay --ports 11111,11112 &`
2. `croc --relay localhost:11111 send --code correct-horse-battery-staple --text "hello"`
3. `croc --relay localhost:11111 --yes 1234-correct-horse-battery-staple`
4. `y` needs to pressed to receive the message
5. `croc --relay localhost:11111 send --code correct-horse-battery-staple --text "hello"`
6. `croc --overwrite --relay localhost:11111 --yes 1234-correct-horse-battery-staple`
7. message received without interaction

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->

1. `croc relay --ports 11111,11112 &`
2. `croc --relay localhost:11111 send --code correct-horse-battery-staple --text "hello"`
3. `croc --relay localhost:11111 --yes 1234-correct-horse-battery-staple`
4. message received without interaction

## Version
<-- Check "croc -v" and report it -->
croc version v9.1.0-35106d4

## Additional context
<-- Add any other context about the problem here. -->
Maybe related to https://github.com/schollz/croc/issues/365 
Skipping temporary files (maybe by limiting the size of the `--text` argument would also enable the use on read-only filesystems (currently send and receive of `--text` messages fails on read-only filesystems).

**Comment by Amatis-51** [comment]
I'm finding that this is an issue again in version  v9.5.0-f210ef8.  
When receiving any text message, I am prompted:
Overwrite 'croc-stdin-XXXXXXXXX'? (y/N) 

After doing a little testing, I believe I'm seeing this on all releases after v9.3.0-94b2aff.
