### ISSUE TITLE
Non buffering pipe

### ISSUE THREAD

**Issue by takase1121** [schollz/croc#385]
**Is your feature request related to a problem? Please describe.**
I was trying to send a folder with lots of files. Sending these are really inefficient as croc has no way of batching small files and send them, so I used tar to batch them. I pipe tar directly into croc and do the same on the other side. It took forever and I realized croc definitely buffers the data before sending it.

**Describe the solution you'd like**
croc should send pipe input directly without a buffer.

**Comment by schollz** [comment]
> croc should send pipe input directly without a buffer.

Can you elaborate?

**Comment by takase1121** [comment]
> > croc should send pipe input directly without a buffer.
> 
> Can you elaborate?

for example `tar -czf - . | croc send` will buffer all output from `tar` in a file (from what I observed). Instead of buffering it, maybe croc should send the data without buffering it first in a temporary file. I used pipes because I cannot afford creating a temporary file (storage constraints) so this makes croc unsuitable to send very large streams.

**Comment by schollz** [comment]
I see. This type of streaming will not be supported

**Comment by takase1121** [comment]
But why? It diminishes the use for pipes.

**Comment by schollz** [comment]
I should've said it will not be supported *right now*, but it is low priority. If this is really important to you, though, consider becoming a sponsor.
