### ISSUE TITLE
Auto-update or warning that a new version is available

### ISSUE THREAD

**Issue by mawoka-myblock** [schollz/croc#386]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
If I install croc via the install-script it should check before sending/receiving if it is up to date so I don't get any errors because the server was updated

**Comment by schollz** [comment]
I'd accept a PR for this

**Comment by mawoka-myblock** [comment]
Thanks

**Comment by mawoka-myblock** [comment]
Sadly I can't code Go

**Comment by tomkukral** [comment]
How should croc discover latest release? From github API? I think it should be optional parameter as doing another call to github API can be considered harmful.

**Comment by mawoka-myblock** [comment]
Yea, but I mean, for example, croc receives an update, but the client throws an error because the client and the server are incompatible. I would like to see something like `you client isn't up-to date. Please update croc.` instead of an error Nobody understands.

**Comment by Kodden585** [comment]
> How should croc discover latest release? From github API? I think it should be optional parameter as doing another call to github API can be considered harmful.

I think it would be suitable for the relay to notify the user about this.

**Comment by mawoka-myblock** [comment]
> > How should croc discover latest release? From github API? I think it should be optional parameter as doing another call to github API can be considered harmful.
> 
> I think it would be suitable for the relay to notify the user about this.

It's already implemented

**Comment by mawoka-myblock** [comment]
Still relevant

**Comment by mawoka-myblock** [comment]
Still relevant
