### ISSUE TITLE
croc does not preserve filenames / displays wrong filenames if the filename has prefix "croc-stdin-"

### ISSUE THREAD

**Issue by wamserma** [schollz/croc#387]
## Describe the bug
<-- A clear and concise description of what the bug is. -->

Croc writes files with random filename on the receiver side.

### Sender
```
$ echo foo > croc-stdin-121218387 
$ croc send croc-stdin-121218387 
Sending 'stdin' (4 B)
Code is: 5306-maze-scale-penguin
On the other computer run

croc 5306-maze-scale-penguin

Sending (->192.168.178.51:60992)
 100% |████████████████████| ( 4/ 4B, 5.014 kB/s)
```

### Receiver
```
$ croc 5306-maze-scale-penguin
Accept 'stdin' (4 B)? (y/n) y

Receiving (<-[::1]:38192)

Overwrite 'croc-stdin-795883111'? (y/n) y
 100% |████████████████████| ( 4/ 4B, 2.306 kB/s)

$ ls croc-stdin-795883111 
croc-stdin-795883111
$ less croc-stdin-795883111 
$ cat croc-stdin-795883111 
foo
```

## Expected behaviour
Croc should keep the filename set by the sender. Also, it should display the full filename to avoid accidental overwriting on the receiver side. (Note the "Accept 'stdin'" above.)

## Version
croc version v9.1.0-35106d4

## Additional context
<-- Add any other context about the problem here. -->

**Comment by schollz** [comment]
This bug only occurs when you send a file with the prefix `croc-stdin-`, correct?

**Comment by wamserma** [comment]
@schollz Correct.

**Comment by schollz** [comment]
Okay, would accept a PR for this.
