### ISSUE TITLE
Add flag for using local DNS (--internal-dns)

### ISSUE THREAD

**Issue by CHTJonas** [schollz/croc#389]
Thanks for creating such a great tool! I noticed that the [changelog for the most recent release](https://github.com/schollz/croc/releases/tag/v9.1.1) mentions that croc will now ["prefer local DNS resolver over public DNS servers"](https://github.com/schollz/croc/commit/8f5c73837a30f4ea232d0b096c1df6f6d512053e). This new behaviour is a great and certainly welcome improvement but using anything other than the local resolver feels like a case of NIH; I'm interested to know what the motivations behind this are.

- Why does croc fallback to a hardcoded list of recursive DNS servers? End users have no way to configure these at the command line and for some, the risk of leaking information to Cloudflare, Google, Comodo and/or Cisco might be a dealbreaker.
- Why does croc think it knows better than the user when it comes to resolving DNS queries? A failure of the local resolver may actually be desired behaviour e.g. DNS block lists.

I guess my question here is why reinvent the DNS wheel? Personally, I feel like croc should not concern itself with how DNS queries are resolved or how the IP network is configured and simply leave these things to the user/operating system.

**Comment by schollz** [comment]
> Why does croc fallback to a hardcoded list of recursive DNS servers? 

The hardcoded DNS sped up DNS querying for me when I use it on machines I use croc with. I use croc on a lot of ephemeral machines with badly configured DNS and [the original `net.LookupIP`](https://github.com/schollz/croc/commit/5374be1a0ff9a55c7bade339964c338116012e51) would take ~10 seconds on some of them. Hard-coding a better DNS dramatically improved this.

> Why does croc think it knows better than the user when it comes to resolving DNS queries? 

See above.

> I guess my question here is why reinvent the DNS wheel?

See above.

> I feel like croc should not concern itself with how DNS queries are resolved

I'd accept a PR for a flag for this - it might be tricky though because the DNS resolution is used in the flags, so there are two changes to make and I'm not sure how to go about either. Or you can simply fork croc and comment out [these lines](https://github.com/schollz/croc/blob/master/src/models/constants.go#L63-L80) and build from source.

**Comment by CHTJonas** [comment]
> The hardcoded DNS sped up DNS querying for me when I use it on machines I use croc with. I use croc on a lot of ephemeral machines with badly configured DNS and [the original `net.LookupIP`](https://github.com/schollz/croc/commit/5374be1a0ff9a55c7bade339964c338116012e51) would take ~10 seconds on some of them. Hard-coding a better DNS dramatically improved this.

I don't mean to be rude but would a better solution not be to improve the networking and DNS setup on those machines? Surely you are running other software on them that'll perform poorly in the face of awful DNS? I assume by "ephemeral" you mean some kind of containers, in which case it would just be a case of doing `for IP in 1.1.1.1 1.0.0.0 2606:4700:4700::1111 2606:4700:4700::1001; do echo "nameserver $IP"; done > /etc/resolv.conf` in your Dockerfile, for example.

> See above.

I get what you're saying here and I understand that this is a personal project so you can totally disagree with my point of view and code it however the hell you want, but this is a bit of a slap in the face for other users. I think that most people would expect their software to respect the DNS settings that they have configured their machine to use.

> I'd accept a PR for a flag for this - it might be tricky though because the DNS resolution is used in the flags, so there are two changes to make and I'm not sure how to go about either. Or you can simply fork croc and comment out [these lines](https://github.com/schollz/croc/blob/master/src/models/constants.go#L63-L79) and build from source.

I'd rather not start maintaining a hard-fork of croc because I value the community here and frankly don't have the time! I'd be happy to work on a PR that adds an `--internal-dns` flag that opts in to this kind of behaviour?

**Comment by schollz** [comment]
Great, look forward to PR
