### ISSUE TITLE
With this practical attack, a remote attacker is able to intercept and decrypt all files sent via croc.

### ISSUE THREAD

**Issue by frenschman** [schollz/croc#391]
Hi just information is this True https://redrocket.club/posts/croc/  ?

**Comment by schollz** [comment]
Yes it is, and it has been fixed: https://schollz.com/blog/croc9/

**Comment by frenschman** [comment]
Ok Thx 

Can you explain or you know a good website I can read it 

How I change the relay and what it is a relay

Thx !!!
