### ISSUE TITLE
Settings not saved on Windows 64 bit CLI

### ISSUE THREAD

**Issue by zawnk** [schollz/croc#394]
## Describe the bug
I've just downloaded the 64 bit Windows 10 CLI executable and it works (transferred files from my phone to my PC). I've used `--remember`, but nothing seems to be saved. I've checked and there's a folder under `C:\Users\<user>\.config\croc\` but it's empty and no JSON file in there. The command I've run was just: `croc --remember --pass XXXX --relay "<localip>:9009"` (also tried it with `--debug` but that didn't change anything)

## Expected behaviour
Config file should've been created with the passphrase and relay saved so I don't have to enter it every time I use croc.

## Version
croc version v9.1.2-e47776b

**Comment by zawnk** [comment]
Yeah, then it creates json file:
```
{
    "IsSender": true,
    "SharedSecret": "",
    "Debug": false,
    "RelayAddress": "142.93.177.120:9009",
    "RelayAddress6": "[2604:a880:800:c1::14c:1]:9009",
    "RelayPorts": [
        "9009",
        "9010",
        "9011",
        "9012",
        "9013"
    ],
    "RelayPassword": "pass123",
    "Stdout": false,
    "NoPrompt": false,
    "NoMultiplexing": false,
    "DisableLocal": false,
    "OnlyLocal": false,
    "IgnoreStdin": false,
    "Ask": false,
    "SendingText": true,
    "NoCompress": false,
    "IP": "",
    "Overwrite": false,
    "Curve": "siec",
    "HashAlgorithm": "xxhash"
}
```

I guess I can now just edit it with my personal relay?

**Comment by schollz** [comment]
Can you try?

**Comment by ssmendon** [comment]
Similar issue on macOS 11.4 with `croc version v9.1.4-d0ebb7a` installed via Homebrew.

In `~/.config/croc/send.json`:
```
{
    "IsSender": true,
    "SharedSecret": "",
    "Debug": false,
    "RelayAddress": "<ip>",
    "RelayAddress6": "<ip>",
    "RelayPorts": [
        <port>
    ],
    "RelayPassword": "<pass>",
    "Stdout": false,
    "NoPrompt": false,
    "NoMultiplexing": false,
    "DisableLocal": false,
    "OnlyLocal": false,
    "IgnoreStdin": false,
    "Ask": true,
    "SendingText": true,
    "NoCompress": false,
    "IP": "",
    "Overwrite": false,
    "Curve": "p256",
    "HashAlgorithm": "xxhash"
}
``` 

When running `croc --debug send --text "tmp"`, the options are reported as
```
[debug]	13:01:51 croc.go:164: options: {IsSender:true SharedSecret:1636-hazard-noise-martin Debug:true RelayAddress:142.93.177.120:9009 RelayAddress6:[2604:a880:800:c1::14c:1]:9009 RelayPorts:[9009 9010 9011 9012 9013] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false SendingText:true NoCompress:false IP: Overwrite:false Curve:siec HashAlgorithm:xxhash}
```
(output expanded for clarity)
```
('{IsSender:true SharedSecret:1636-hazard-noise-martin Debug:true '
 'RelayAddress:142.93.177.120:9009 '
 'RelayAddress6:[2604:a880:800:c1::14c:1]:9009 RelayPorts:[9009 9010 9011 9012 '
 '9013] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false '
 'DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false '
 'SendingText:true NoCompress:false IP: Overwrite:false Curve:siec '
 'HashAlgorithm:xxhash}')
```
These are the defaults. The same occurs when trying to send a file (i.e. `croc --debug send ./tmp.txt`), and if `croc send ./tmp.txt` is run without any command-line flags.

**Comment by ssmendon** [comment]
I'd like to follow-up with this. The issue with `send` not remembering preferences doesn't occur on macOS if I clone [the repository as it is right now](https://github.com/schollz/croc/commit/a9e77673f4e53272e599f18233840babb9081d6b) and run directly with Go. Haven't tested `receive` at all.
