### ISSUE TITLE
Why the file transfer rate of the sender is far more than the reciever

### ISSUE THREAD

**Issue by oldunclez** [schollz/croc#396]
I notice that the file transfer rate of the sender is far more than the reciever.
For example , the sender has transfered 100% files , but at the same time , the reciever has only  recieved 50%.
The speed of sender is 1Mbyte/s , and the the speed of reciever is 100kbyte/s
so why will it happen ?
Will the files be transfered to the croc relay server first , and then relay to the reciever ?

**Comment by UnrelatedWorks** [comment]
I assume there is a cache if the discrepancy between the sender and the receiver is too high. 
What are the upload capabilities of your sender and the download capabilities of your receiver?
