### ISSUE TITLE
Implement "wormhole ssh invite/accept"

### ISSUE THREAD

**Issue by hammerandtongs** [schollz/croc#398]
I like the idea additional features of croc but the vast majority of what I use "magic-wormhole" for is "wormhole ssh invite" and "accept".

This small feature is really great timesaver for me.

I realize is might seem trivial or featuritis but it really makes life much easier.

```
wormhole ssh --help
Usage: wormhole ssh [OPTIONS] COMMAND [ARGS]...

  Facilitate sending/receiving SSH public keys

Options:
  --help  Show this message and exit.

Commands:
  accept  Send your SSH public-key In response to a 'wormhole ssh invite'...
  invite  Add a public-key to a ~/.ssh/authorized_keys file

```

**Comment by schollz** [comment]
I'd accept a PR for this. But in the meantime you can simply do:

```
# sender
cat ~/.ssh/id_rsa.pub | croc send
```

and then 

```
# add to authorized
croc --stdout --yes >> ~/.ssh/authorized_keys
```
