### ISSUE TITLE
Freeze/stuck/hang after sending (mostly large) files

### ISSUE THREAD

**Issue by peppaslaughter** [schollz/croc#407]
## Describe the bug

I tried it with Ubuntu-Manjaro, Ubuntu-Win7, Manjaro-Manjaro, Ubuntu-Ubuntu combinations, tried it with custom, self-hosted relays (run on VPS and on my own PC), tried it with custom codes and with the --no-compress parameters, but the problem is still the same: after receiving/sending the file, and the progress bar reaches 100%, the program stuck, so if I want to send a whole folder, it freezes at the end of the first file (if its size is 2GB+), or if there are lots of small files then around midway, and I have to manually stop the program. It is possible to open the file(s), there are no checksum errors, so the transfer was succesful, the file is readable, but the program doesn't end and hangs.

## To Reproduce

croc (send) your-code-typed-here (with and without the methods, parameters and options I described earlier), and usually happens with 2+ GB files.

## Expected behaviour

After sent/received a file (or more small files), transfer should end normally (and the second file's transfer should start if a folder was sent.)

## Version

croc version v9.2.0-d442755

## Additional context

---

**Comment by schollz** [comment]
I can reproduce this and I think I fixed it. Can you try the latest from source?

**Comment by peppaslaughter** [comment]
I tried, but oddly, somewhy, I can't build it.

**Comment by peppaslaughter** [comment]
All right, tried with the latest version, and it seems that everything's OK! Thank you!
