### ISSUE TITLE
https://getcroc.schollz.com not work

### ISSUE THREAD

**Issue by pomazanbohdan** [schollz/croc#410]
Pinging getcroc.schollz.com [142.93.177.120] with 32 bytes of data:
Request timed out.
Request timed out.

**Comment by schollz** [comment]
Try now

**Comment by shayaknyc** [comment]
Yeah, seems to be timing out again....

```
Pinging getcroc.schollz.com [142.93.177.120] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 142.93.177.120:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

```
Tracing route to getcroc.schollz.com [142.93.177.120]
over a maximum of 10 hops:

  1    <1 ms    <1 ms    <1 ms  10.0.0.1
  2    14 ms    13 ms    14 ms  10.240.160.97
  3    10 ms    11 ms    10 ms  67.59.229.232
  4    12 ms    15 ms    11 ms  dstswr2-vlan2.rh.nyk6ny.cv.net [67.83.222.162]
  5    15 ms    10 ms    10 ms  65.19.100.22
  6    13 ms    12 ms    14 ms  451be0e6.cst.lightpath.net [65.19.120.230]
  7    11 ms    11 ms    12 ms  UnAssigned170.nyiix.net [198.32.160.170]
  8     *        *        *     Request timed out.
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
```

**Comment by schollz** [comment]
Should be up now

**Comment by ahfeel** [comment]
Down again :(

**Comment by schollz** [comment]
And up again...having some server problems I think....

**Comment by mawoka-myblock** [comment]
> And up again...having some server problems I think....

Why don't you change to GitHub-Pages or something similar, or even CloudFlare-Workers? I think they should be more reliable

**Comment by obfuscatedgenerated** [comment]
```
Pinging getcroc.schollz.com [142.93.177.120] with 32 bytes of data:
Request timed out.
Request timed out.
```

**Comment by schollz** [comment]
Can you try again? I just checked and its up

Would accept a pr for a status page 👍

**Comment by obfuscatedgenerated** [comment]
It must be my firewall then.

**Comment by mawoka-myblock** [comment]
> Can you try again? I just checked and its up
> 
> Would accept a pr for a status page +1

What do you mean with a "pr for a status page"?

**Comment by obfuscatedgenerated** [comment]
I mean as in a page that shows relay outages over time. Therefore, users can check whether the server is down or if it something on their end preventing the transfer.

**Comment by obfuscatedgenerated** [comment]
I personally recommend [Upptime](https://github.com/upptime/upptime) for this. It's free for public repos (since it uses GitHub actions) and very intuitive.

**Comment by mawoka-myblock** [comment]
> I personally recommend [Upptime](https://github.com/upptime/upptime) for this. It's free for public repos (since it uses GitHub actions) and very intuitive.

Yea, great idea! I was confused, because we can't submit a pr for Upptime, so @schollz would have to setup it on his own.

**Comment by obfuscatedgenerated** [comment]
https://github.com/schollz/upptime
Thanks a bunch!

**Comment by obfuscatedgenerated** [comment]
This issue could probably be closed now since the original issue was old and we kinda hijacked it into "make a status page" (sorry 😁)
