### ISSUE TITLE
Const-ize values which are used like consts

### ISSUE THREAD

**Issue by jalavosus** [schollz/croc#413]
**Is your feature request related to a problem? Please describe.**
Not a **problem** per se, more of a code organization/readability/navigation thing. 

There are various values throughout the codebase which are used like constant values, examples:

https://github.com/schollz/croc/blob/master/src/croc/croc.go#L435
https://github.com/schollz/croc/blob/master/src/croc/croc.go#L406
https://github.com/schollz/croc/blob/master/src/tcp/tcp.go#L163

As well as values initialized as `var` which could/should be set as `const`, ex.: https://github.com/schollz/croc/blob/master/src/tcp/tcp.go#L39-L40

**Describe the solution you'd like**
Depending on how the value is used, store values like those shown above as `const` on a per-package or "global" level (ie. putting them in a package called `consts` or `config`). 

**Describe alternatives you've considered**
Leaving it the way it is, Croc works great regardless. 

I can start in on a draft PR later tonight which implements what I've described above for a few packages, if the devs want.

**Comment by schollz** [comment]
Looks good to me! Happy to accept pr
