### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by Jetereting** [schollz/croc#414]
croc --relay 222.175.xx.xx:7001 0605-office-dolby-topic
securing channel...panic: comm.NewConnection failed: dial tcp: lookup tcp/ok: nodename nor servname provided, or not known

goroutine 9 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake.func1(0xc00001d504, 0xc0000b2200, 0xc00039a020, 0x0)
	github.com/schollz/croc/v9/src/croc/croc.go:918 +0x685
created by github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake
	github.com/schollz/croc/v9/src/croc/croc.go:898 +0x45f

**Comment by schollz** [comment]
Can you redo this issue and fill out the requested data?
