### ISSUE TITLE
Relay binds only to v6 addresses

### ISSUE THREAD

**Issue by codyro** [schollz/croc#416]
## Describe the bug
When starting a relay with `croc relay` it appears to be binding on only v6 addresses and not v4. This behavior is the same regardless if you pass `--ports` or not.

### Environment
```
Distributor ID:	AlmaLinux
Description:	AlmaLinux release 8.4 (Electric Cheetah)
Release:	8.4
```

1. Start the relay with `croc relay`. Adding `--ports` produces the same behavior. 
2. Check to see what address(es) the relay is listening on

```
[root@croc ~]# netstat -tunlp | grep croc
tcp6       0      0 :::9009                 :::*                    LISTEN      1086/croc
tcp6       0      0 :::9010                 :::*                    LISTEN      1086/croc
tcp6       0      0 :::9011                 :::*                    LISTEN      1086/croc
tcp6       0      0 :::9012                 :::*                    LISTEN      1086/croc
tcp6       0      0 :::9013                 :::*                    LISTEN      1086/croc
```

## Expected behavior
The relay should bind to v4 addresses as well as v6.

## Version
`croc version v9.3.0-94b2aff`

## Additional comments
This should be in a feature request but the ability to bind to a specific address would be beneficial.

**Comment by tidux** [comment]
This is just how Linux networking works.  When you tell it to bind to a port on all IP addresses, the kernel binds to an IPv6 address (::) and also connects IPv4 traffic (0.0.0.0) to it.
