### ISSUE TITLE
Transferring between two machines on public ipv6 network continues to use digitalocean relay (over ipv4, too)

### ISSUE THREAD

**Issue by trollcop** [schollz/croc#418]
## Describe the bug
I just tried to send some files from Machine A to Machine B, both of which have globally accessible, public, reachable (ping) IPv6 addresses.

When looking at the netstat, I noticed traffic getting routed (at high speed, too) through 142.93.177.120 which looks to be an IP address belonging to digitalocean.

I understand that a public relay is needed to connect two machines and get the transfer keyword or whatever, but why are machines not transferring p2p if they both have public v6 addresses?

## Expected behaviour
I expect the DO relay to be used to establish the code word and negotiate connection between my two machines over ipv6 network, instead of relaying all the data through DO.

## Version
croc version v9.3.0-94b2aff

**Comment by schollz** [comment]
A relay is always used between machines that are not on the same LAN network. 

If one of your machines is public then you can initiate a transfer by running a relay on that machine and then running the croc commad using that relay instead of the public relay.

**Comment by trollcop** [comment]
Hmm, I see. But since IPv6 is a huge "LAN" so to speak, shouldn't it be possible without having to go through a relay?
Alternatively, is there a way to put the information passed to --relay into environment variable, like CROC_RELAY or something, so I don't have to keep typing it each time i wanted to transfer stuff?

**Comment by schollz** [comment]
Also one comment - peer-to-peer transfer simply means a network of interconnected nodes share information. As opposed to a client-server model. croc doesn't use a client-server model to transfer files (like ssh).

**Comment by trollcop** [comment]
> As opposed to a client-server model. croc doesn't use a client-server model to transfer files (like ssh).

Well, I see.
Yeah I tried with relay just now and its working (I see traffic between my two v6 hosts). I still feel its getting "relayed" because there's twice as many connections as should be, but I guess its still counted as local traffic.

Not exactly optimal but still faster than wget since it seems to be using multiple threads.
