### ISSUE TITLE
Switch to throttle traffic when sending file

### ISSUE THREAD

**Issue by katakombi** [schollz/croc#429]
**Is your feature request related to a problem? Please describe.**
I want to distribute ISO builds to a bunch of clients but I can't utilize the entire upload bandwith

**Describe the solution you'd like**
A way to throttle upload/download speed with a flag e.g. --max-bandwidth=500k

**Describe alternatives you've considered**
A traffic shaping solution e.g. wondershaper

**Additional context**

**Comment by yairm210** [comment]
Since the PR was accepted, this looks closable to me
