### ISSUE TITLE
ARMv5 Package

### ISSUE THREAD

**Issue by Prikith** [schollz/croc#436]
**Is your feature request related to a problem? Please describe.**
The problem is that on old nas devices running debian i have to copy my own cross compiled binary to /usr/local/bin instead of using the install script.

**Describe the solution you'd like**
I would like to have armv5 added to the build targets

**Describe alternatives you've considered**
Manually compiling the binary again when updates are released and manually updating.

**Additional context**
i have manually cross compiled the binary on WSL debian with the go enviroment installed using the wiki instructions.
mkdir -p /root/.config/go && touch /root/.config/go/env
echo GOARCH=arm > /root/.config/go/env
echo GOOS=linux >> /root/.config/go/env
echo GOARM=5 >> /root/.config/go/env
go get -v github.com/schollz/croc/v9@latest
rm /root/.config/go/env
rm -rf /root/go/pkg
/root/go/bin/linux_arm/croc

It will fail on installing the package due to it being a cross-compiled binary

![image](https://user-images.githubusercontent.com/38623521/140753545-c1635607-b20f-4c05-8bd1-a5bbb5ff5e01.png)

**Comment by schollz** [comment]
Sure, would accept PR for this
