### ISSUE TITLE
Letter-based code phrase prefix

### ISSUE THREAD

**Issue by toonn** [schollz/croc#439]
**Is your feature request related to a problem? Please describe.**
Not a huge problem but recent versions of croc prefix the code phrase with a four digit number. This is slightly less convenient to type on mobile devices.

**Describe the solution you'd like**
Would it be possible to extend the code phrase by one or two words instead?

**Describe alternatives you've considered**
Configuration options/flags to choose the code phrase format. Maybe allowing specification of a restricted alphabet to use?

**Additional context**
This is a feature request because the only alternative was a bug report : )
Really I was just curious why these numeric prefixes were added. Was there too little entropy in the code phrases? Why a numeric prefix rather than an extra word or two?

**Comment by schollz** [comment]
code phrase can be customized now!

**Comment by toonn** [comment]
@schollz, as implemented `--code` does address the issue. However it kinda moves the inconvenience from the receiver to the sender. I was hoping the code would still be generated randomly. Just potentially restricting the allowed characters.

However, I'm not asking for another new feature. Mostly I was wondering whether you noticed my questions at the end of the OP?
