### ISSUE TITLE
Problem when using croc in my phone in conjunction with Invizible Pro app.

### ISSUE THREAD

**Issue by tuqueque** [schollz/croc#446]
Hello, first of all, I love this program!... I've been looking for something like this for years now and I finally found it!

However...

I've been doing some tests and I've found that when I try to send large files from my PC to my phone, all versions I've tested of croc in my phone, fail in the same way when I have Invisible Pro active ( https://github.com/Gedsh/InviZible )... When I close Invizible Pro, croc's file transfer goes smoothly.

I know, I know... croc is not officially supported in Android, but bear with me...

First, I tested the "croc gui" app available in f-droid ( https://f-droid.org/en/packages/com.github.howeyc.crocgui/ ), then, I installed croc in my Termux environment... and finally, I even installed croc in my Andronix's Manjaro ARM Linux installation ( https://play.google.com/store/apps/details?id=studio.com.techriz.andronix ) and as I said, all three versions fail in the exact same way when I have Invizible Pro running...

So... either is Invizible Pro's fault (I already made a bug report over there a couple hours ago)... or is croc's fault.

I'm thinking it might be croc's fault because it always fails at 2:30 minutes after I begin downloading the file in my phone... When croc fails in my phone, my PC throws one of two errors...

Either this one (IPs are Xed just out of caution)
```
Sending (->xxx.xxx.x.xxx:48098)
  33% |██████              | (232/700 MB, 1.490 MB/s) [2m31s:5m13s]2021/12/16 18:03:06 EOF
```

Or this one:
```
Sending (->xxx.xxx.x.xxx:48126)
  70% |██████████████      | (496/700 MB, 2.271 MB/s) [2m30s:1m29s]
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9010->xxx.xxx.x.xxx:51614: write: connection reset by peer
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9010->xxx.xxx.x.xxx:51614: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9010->xxx.xxx.x.xxx:51614: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9013->xxx.xxx.x.xxx:34586: write: connection reset by peer
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9013->xxx.xxx.x.xxx:34586: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9013->xxx.xxx.x.xxx:34586: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9011->xxx.xxx.x.xxx:55848: write: connection reset by peer
panic: connection.Write failed: write tcp 127.0.0.1:42540->127.0.0.1:9010: write: connection reset by peer

goroutine 97 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).sendData(0xc000178400, 0x0)
	github.com/schollz/croc/v9/src/croc/croc.go:1598 +0x6fb
created by github.com/schollz/croc/v9/src/croc.(*Client).updateState
	github.com/schollz/croc/v9/src/croc/croc.go:1428 +0x6cb
```

Hopefully, this can be solved.

Thank you very much for your time!

**Comment by schollz** [comment]
I don't know what Invizible Pro app is.

I use croc and termux all the time and it works perfectly fine.

**Comment by tuqueque** [comment]
> I don't know what Invizible Pro app is.

That's why I'm mentioning it and placing a link to the app (which is open source and also here in Github).

> I use croc and termux all the time and it works perfectly fine.

I know it works without InviZible Pro app running, I'm just wondering if there's some sort of "interaction" between croc and InviZible, where "the ball" could be in croc's court.

As I said, I also posted this problem in their Issues section and the developer will look into it, but I don't know, he might need some feedback from you if the problem is more complex than just " is InviZible Pro's fault".
