### ISSUE TITLE
Release 9.5 croc.exe being flagged as malicous on VirusTotal.com

### ISSUE THREAD

**Issue by optiprime** [schollz/croc#449]
I got the analysis result "2 security vendors and 1 sandbox flagged this file as malicious". Is this a false positive or a real problem?

**Comment by hamiecod** [comment]
Could you please list the steps for the reproduction of the issue?

**Comment by optiprime** [comment]
Open https://www.virustotal.com/,  drop  or upload croc.exe. The website will run 67 virus scanners and 2 of them will flag the program as malicious.

**Comment by schollz** [comment]
Hi @optiprime. I don't know anything about virustotal.com. But I tried uploading various .exe files on my computer onto it and all uploaded I tried had "2 security vendors flagged", croc.exe included like you say. But also even the Go binary from Google itself: 

![image](https://user-images.githubusercontent.com/6550035/147394025-0ad950a9-1d79-40f8-a7f7-c681d4b0a49f.png)

Seems like a false positive to me. But feel free to make your own judgements. In any case you are free to download the source and compile yourself.

**Comment by optiprime** [comment]
That's indeed strange. You're right, seems to be a false positive. I'll close the issue, thankx  for your clarification.
BTW: Normally Virustotal.com gives you fast and easy access to many AV software packages. It's also integrated in SysInternals' ProcessExplorer and here shows you a quick AV flagging of all your running processes.
