### ISSUE TITLE
Trying to send a file with `--local` fails with `found no addresses to connect` 

### ISSUE THREAD

**Issue by DUOLabs333** [schollz/croc#454]
## Describe the bug
I'm trying to send a file between two devices on the LAN. To try to boost the speed, I send with `--local`. However, when trying to connect, it fails with 
```
[debug]    17:54:45 croc.go:561: attempt to discover peers
[debug] 17:54:45 croc.go:626: discoveries: []
[debug] 17:54:45 croc.go:627: establishing connection
[debug] 17:54:45 croc.go:655: could not connect to : found no addresses to connect
2022/01/09 17:54:45 could not connect to : found no addresses to connect 
```

## To Reproduce
1. Send file with `croc --local send <file>`
2. On the other device, try to recieve with `croc --local <code>
3. See error

## Expected behaviour
There should be no error.

## Version
This is between a Windows machine and Arch Linux ARM, both with `croc version v9.5.0-f210ef8`

**Comment by schollz** [comment]
Can you try again with the latest version?

**Comment by DUOLabs333** [comment]
The problem seems to be resolved.

**Comment by DUOLabs333** [comment]
This is happening again with Android phone sending to Arch Linux computer.

**Comment by DUOLabs333** [comment]
Both are `v9.5.6`.

**Comment by NightMachinery** [comment]
I also got this error on `v9.5.6-b7e4a73`. I tried:
```
croc --local .

# on the same computer
croc --local xxx
```

**Comment by DUOLabs333** [comment]
This is happening sending from Windows to Arch:
```
[debug] 12:37:46 cli.go:141: debug mode on
[debug] 12:37:46 croc.go:178: options: {IsSender:false SharedSecret:Hello333 Debug:true RelayAddress:5.161.69.143:9009 RelayAddress6:[2a01:4ff:f0:23c2::14c:1]:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:true IgnoreStdin:false Ask:false SendingText:false NoCompress:false IP: Overwrite:false Curve:p256 HashAlgorithm: ThrottleUpload:}
connecting...[debug]    12:37:46 croc.go:648: attempt to discover peers
[debug] 12:37:46 croc.go:713: discoveries: []
[debug] 12:37:46 croc.go:714: establishing connection
[debug] 12:37:46 croc.go:742: could not connect to : found no addresses to connect
```

**Comment by beheeddinekhelil** [comment]
Hi so my question is
I installed croc in android using termux it works fine but since i'm running out from data i wanted to send a 2 gb file to my laptop so i figured out that i can use croc with the --local so i made i made a hotpost without internet from my phone and connected it to my laptop and shared normally from my phone using the local but it gives me the same error
So my question is the thing i was doing supposed to work in the first place or not

**Comment by stefins** [comment]
@beheeddinekhelil  What command are you using to send the file?

**Comment by beheeddinekhelil** [comment]
@stefins
croc --local send --code anyway1234 fgbhct.blend
For sending

croc anyway1234
For receiving

**Comment by stefins** [comment]
@beheeddinekhelil Have you  tried sending with internet on( for peer discovery)? Then also if it's not working try to host a local relay on your device and send through it!

**Comment by beheeddinekhelil** [comment]
@stefins it works fine when the internet is on without the --local option

+ Isn't hosting my own relay requires mobile data
+ How to receive from that local relay is it always the same
Like "croc anyway01234" per exemple

**Comment by stefins** [comment]
>  it works fine when the internet is on without the --local option

This is for peer discovery not for actual data transmission

> Isn't hosting my own relay requires mobile data

No

> How to receive from that local relay is it always the same

You have to specify the relay flag for both `send` and `receive` command
like 
`croc --relay "myrelay.example.com:9009" send [filename]`

**Comment by beheeddinekhelil** [comment]
@stefins so when I keep the internet on but with the --locale option it sais in the receive device
That the room is not ready

Btw can i open a relay with the locale option

**Comment by stefins** [comment]
> Btw can i open a relay with the locale option

no you have to run `croc relay`

**Comment by Guarmanda** [comment]
Croc --local still doesn't work using the same computer with internet on
![image](https://user-images.githubusercontent.com/7463055/220889233-508347cb-06f9-4a6f-a5b9-a8b5eb196889.png)
