### ISSUE TITLE
"Connection reset by peer" when transferring from MacOS to Linux through Wireguard

### ISSUE THREAD

**Issue by DUOLabs333** [schollz/croc#457]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
If an Linux machine and Macbook are connected through a Wireguard tunnel, trying to transfer between them fails (FWIW, transfering from an Android phone to the same Linux computer works fine).

## To Reproduce
<-- 1. Go to '...'
4. See error -->

1. Transfer a file from a Macbook to a Linux computer
2. See error

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->
No error

## Version
<-- Check "croc -v" and report it -->
For both systems: `croc version v9.5.0-f210ef8`

## Additional context
<-- Add any other context about the problem here. -->
It sometimes work, but it's not clear when.

**Comment by schollz** [comment]
Can you run with `--debug` and share the output?

**Comment by DUOLabs333** [comment]
The problem seems to be resolved.
