### ISSUE TITLE
Some generic questions

### ISSUE THREAD

**Issue by SebastienTs** [schollz/croc#465]
Hi Zack,

After testing zillions of peer to peer tools to transfer large files between academic environments with aggressive firewalls / NATs (and hours of sterile discussions with IT teams accross the sites to attempt to solve issues), I came accross croc, and it seems to work wonders! I am already very happy with the tool and grateful that you've shared it but I have some  questions if you don't mind answering them:

- Is the public relay only used to initiate the communication or is all data transiting through it? I am not concerned at all about privacy but about stability and throughput when transfering TBs of data. For these would you recommend me to set up my own private relay?

- Can encryption be disabled and would it improve the transfer speed or is the encryption overhead negligible for typical throughputs of few MB/s?

- Are you already using parallel TCP streams or could the throughtput be further increased and shielded from local congestions by such strategy? Are there practical issues preventing to implement them?

- Would it be difficult to implement custom compression schemes within croc (from your code base or ideally with a sort of plugin mechanism as I don't code in Go), or would you recommend me to do it externally from an other application and pipe the output to croc? Could this last be achieved memory based?

- Would it be difficult to modify the code base to synchronize folders on both ends (one way only)? Or maybe simpler, would it be possible to encapsulate other protocols (Webdav, Bittorrent) through the TCP stream(s) established by croc to run applications using these protocols behind firewalls?

Thanks again Zack!
Best,
S.

**Comment by schollz** [comment]
Hi @SebastienTs thanks for the kind message. I also used croc in an academic setting to transfer terabytes of data from one lab to another lab...  Out of curiosity - what other tools did you try? 

> Is the public relay only used to initiate the communication or is all data transiting through it? I am not concerned at all about privacy but about stability and throughput when transfering TBs of data. For these would you recommend me to set up my own private relay?

Public relay is a fallback for both communication initiation and data transmission. If you aren't transferring between computers on LAN then its going to always use the public relay. I would recommend setting up your own private relay because I having trouble longterm getting funding to support the tens of terabytes / month that people are transferring (bandwidth at that scale costs me money...actually consider [sponsoring me on Github](https://github.com/sponsors/schollz) to keep the server running. I've come close to shutting it down twice because I couldn't afford it.)


> Can encryption be disabled and would it improve the transfer speed or is the encryption overhead negligible for typical throughputs of few MB/s?

The limiting factor by far is the bandwidth. Using LAN would typically max out the bandwidth.

> Are you already using parallel TCP streams or could the throughtput be further increased and shielded from local congestions by such strategy? Are there practical issues preventing to implement them?

Yes, parallel TCP streams are being used by default.

> Would it be difficult to implement custom compression schemes within croc (from your code base or ideally with a sort of plugin mechanism as I don't code in Go), or would you recommend me to do it externally from an other application and pipe the output to croc? Could this last be achieved memory based?

Yes, you could add your own compression scheme. All you have to do is change this file: https://github.com/schollz/croc/blob/master/src/compress/compress.go


> Would it be difficult to modify the code base to synchronize folders on both ends (one way only)? 

You could do synchronization by setting up a simple bash process for one computer to send a folder and bash process for the other computer to automatically receive it. They'd need a shared password though...so you'd have to use a static one (not recommended) or figure out how to generate one on each computer in the same way.


> Or maybe simpler, would it be possible to encapsulate other protocols (Webdav, Bittorrent) through the TCP stream(s) established by croc to run applications using these protocols behind firewalls?

No this is not possible. And this is difficult. Bittorrent is a complicated algorithm. I don't know about Webddav. It might be easier to figure out a proxy to your Bittorrent client if you have firewall issues. But I can't talk much to that since I don't use Bittorrent.

**Comment by SebastienTs** [comment]
Thanks for your reply Zack!

To answer your question, recently I have mostly tried webrtc based web apps
such as file.pizza and sharedrop.io and none could pass through.

Previously, I had tried WebDAV based transfer with external DNS provider
(provided for Qnap NAS) and Resilio (Bittorrent based). Both worked but
resorted to very slow relays and the throughput was unusable, in the range
of tens or at most few hundreds KB/s.

I was also successful with a meshed vpn (tinc) but this one explicitely
required setting up a public node and was slow too even for close by public
nodes (< 1 MB/s).

I finally resorted to our institutional Gdrive, which proved the fastest
(probably due to closeby Google servers) and achieved around 40 MB/s at
both ends. The problem is now the daily bandwidth limit (below 1 TB I
believe). Institutional FTP was somewhere in between (10 MB/s) but not very
stable and limited in swap size.

Croc is the only non cloud / server storage based tool I could try so far
that could sustain 5-10 MB/s during the tests. I understand that since all
the traffic is buffered through the relay our best option is to run a
private node...

Out of curiosity: why is it virtually impossible to only rely on the relay
to initiate the TCP connection between both peers (or at worse periodically
to keep the stream alive) for transfer between two non publicly visible
machines?

I have seen that part of the hacker scene try to establish such feat (with
relative success) but so far I could see no usable solution is available!

**Comment by schollz** [comment]
Very interesting - yeah I think I had previously been underwhelmed by WebRTC speeds/connections but I haven't tried in the past year or two.

> Out of curiosity: why is it virtually impossible to only rely on the relay
to initiate the TCP connection between both peers (or at worse periodically
to keep the stream alive) for transfer between two non publicly visible
machines?

There are different scenarios of NAT traversal and the dedicated relay is really the simplest one that seems to mostly always work. Nothing is ever truly peer-to-peer (except LAN I guess)  - just run `traceroute google.com` and you'll see a bunch of servers in between "relaying" your packets, so really its peer-to-peer-to-peer.... [Even WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Protocols) - it uses a "ICE" server to figure out the public IP addresses and then tries to connect them but fallback (probably pretty often) to using a "TURN" server to relay all the information. A lot of WebRTC apps rely on public ICE/TURN servers (i.e. ones owned by Google or something) which is good and well until the entity that owns the server pulls the plug. Its nice to know that the plug can't be pulled if you own the server and with croc there is only one relay to ever worry about.

**Comment by SebastienTs** [comment]
You are right, there are most of the times many hops unless both ends are
next to the same backbone.

Still, my main concern with a fixed relay is the somewhat limited overall
bandwidth it can handle (when serving many streams), its pinned
geographical position (you might end up having to go around the Earth to
transfer to a "neighbor" 100 km away), and the high maintenance costs for a
large community (regardless of the economical model).

**Comment by ProactiveServices** [comment]
If a sync-type application suits your use case (e.g. systems under your control, specific folders transferring data) you could look at [Syncthing](https://www.syncthing/net/) which has a very reliable firewall/NAT punching suite, automatically resumes and re-uses existing data, can be configured only to use direct connections and/or your own hosted relays. It doesn't rely on storing your data with a third party and hits the sweet spot of being very resilient in its default configuration and also highly customisable.

**Comment by SebastienTs** [comment]
Thanks Adam! I am actually primarily looking for a folder sync application.
Have you tested Syncthing in academic environments and was it able to often
establish direct connections even when both ends behind NATs? I will
definitely give it a try!

**Comment by tidux** [comment]
Syncthing's one weakness is networks that block everything but "well known" egress ports - DNS, HTTP(S), and email.  So long as you can reach port 22000 on a host outside the network, Syncthing will work fine.  I'm fortunate enough to have most of my hosts given public IPv6 addresses, but NAT-to-NAT does work if IPv6 is unavailable.
