### ISSUE TITLE
Long waits while hashing

### ISSUE THREAD

**Issue by oersted** [schollz/croc#466]
**Is your feature request related to a problem? Please describe.**

When sending a lot of data there is a long wait time before the code-phrase is given. I believe most of the time is spent hashing the files before the transfer can start.

**Describe the solution you'd like**

It would be good if this computation were parallelized to use all available cores. It should be possible to hash different files independently. It would also be good to have a reference of which hashing algorithm is fastest in this implementation, and if cryptographically secure hashing is relevant to the security of the transfer.

Is the hashing required to identify the files for the transfer? Or is it simply a checksum for enabling resuming downloads, by detecting differences in the files between source and destination?

If the hashing is not critical to the protocol, it would be good if it were made optional.

Finally, it would be great if the code-phrase were given right away before the hashing, if that would be feasible. That way, the user can set up the receiving side straight away and just let it do everything in the background, instead of having to keep an eye on it at the beginning until the code-phrase is printed.

**Describe alternatives you've considered**

Alternatives like magic-wormhole or filepizza only allow transferring individual files, so packaging them into a ZIP (as magic-wormhole does) or any other bundle format is also a significant pre-processing step that likely takes longer than the hashing in most cases.

**Comment by schollz** [comment]
Can you try `croc send --hash imohash FILE`? that's will use a faster hash algorithm (tradeoff is that it samples the file...but this doesn't matter if it's a first time transfer)

**Comment by oersted** [comment]
That sound like a good compromise, wasn't aware of that behavior, I'll give it a try.

**Comment by schollz** [comment]
@oersted did that fix your issue?
