### ISSUE TITLE
`Panic:  error listening on 0.0.0.0:9009` on Windows

### ISSUE THREAD

**Issue by Van-Dame** [schollz/croc#472]
## Describe the bug
Invocating croc in send mode crashes on Windows 10 with following error:
`[error] 2022/04/28 05:04:58 tcp.go:85: error listening on 0.0.0.0:9009: listen tcp4 0.0.0.0:9009: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

## To Reproduce

0. `scoop install croc`
1.  `croc send <anyfile>`

## Expected behavior
Command succeeds and relay is established.

## Actual behavior

    ❯ croc send appsettings.json
    Sending 'appsettings.json' (3.0 kB)
    Code is: 8075-digital-lava-polo
    On the other computer run
    
    croc 8075-digital-lava-polo
    [error] 2022/04/28 05:17:50 tcp.go:85: error listening on 0.0.0.0:9009: listen tcp4 0.0.0.0:9009: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
    panic: error listening on 0.0.0.0:9009: listen tcp4 0.0.0.0:9009: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
    
    goroutine 51 [running]:
    github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay.func1({0xc000202a78, 0x4})
            /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:377 +0x125
    created by github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay
            /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:370 +0x217

## Version
**croc**: v9.5.4-6158b42`
**OS**: Windows 10 Pro [64-bit]
**Kernel**: 10.0.19044.0
**Shell**: PowerShell v7.2.3
**Terminal**: Windows Terminal
**CPU**: AMD Ryzen 7 1700 Eight-Core Processor

**Comment by schollz** [comment]
I cannot reproduce (Windows 10, installed from scoop, v9.5.4, etc.).
Perhaps you have another process running on port 9009? What happens if you try `croc send --no-local <file>`?

**Comment by Van-Dame** [comment]
Turns out there is something occupying port 9009.

    ❯ netsh interface ipv4 show excludedportrange protocol=tcp

    Protocol tcp Port Exclusion Ranges
    
    Start Port    End Port
    ----------    --------
          2869        2869
          5357        5357
          9009        9009
    

The `--no-local` flag seems to bypass the issue.

    ❯ croc send --no-local appsettings.json
    Sending 'appsettings.json' (3.0 kB)
    Code is: 8633-mystery-quick-mineral
    On the other computer run
    
    croc 8633-mystery-quick-mineral

**Comment by pablodz** [comment]
https://github.com/schollz/croc/blob/master/src/models/constants.go#L17-L23

**Comment by fnfontana** [comment]
Hello, I got the same issue here, it's possible to change the default port on Windows? Or unblock the port 9009 to operate with croc properly?

**Comment by brandonleon** [comment]
I'm getting the same thing on macOS, says the port is in use.

```
[error]	2023/02/18 18:16:36 tcp.go:85: error listening on 0.0.0.0:9010: listen tcp4 0.0.0.0:9010: bind: address already in use
panic: error listening on 0.0.0.0:9010: listen tcp4 0.0.0.0:9010: bind: address already in use
```
But trying to identify a process using the port reveals nothing:

```
>  lsof -i:9010
```
