### ISSUE TITLE
QR Codes for Mobile?

### ISSUE THREAD

**Issue by DananaBanana** [schollz/croc#473]
**Is your feature request related to a problem? Please describe.**
Entering codes from PC -> Mobile can be slow at times.

**Describe the solution you'd like**
Scannable QR code in the terminal, potentially with an extra argument, and a function in the croc app to scan it, this QR code would just be the code.

**Describe alternatives you've considered**
Using Google Lens or any other app that does the same thing to copy the text from my PC screen to my phone.

**Additional context**
/

**Comment by PThorpe92** [comment]
@schollz Is the mobile app open source as well? I would like to implement this if possible. So far I have QR codes generated in the terminal, but obviously it would just display the command on the screen instead of running it in the app.

**Comment by thecountrox** [comment]
@PThorpe92 https://github.com/howeyc/crocgui Yes the mobile app(s) (there are 2 currently afaik) are both open source

**Comment by ytbryan** [comment]
Hey folks, I wrote this simple wrapper to generate qr code from croc code http://github.com/ytbryan/croc2qr
