### ISSUE TITLE
invisible progress on large files

### ISSUE THREAD

**Issue by ciis0** [schollz/croc#475]
croc does seem to create a hash for the files to be transferred

https://github.com/schollz/croc/blob/148c1a6cdd65b5213dad401ac0cd78602d37c2b6/src/croc/croc.go#L360-L361

for impatient people like me wanting to transfer large files (10G over a local relay in my case) it looks like croc does nothing, even in debug mode.

Maybe an informational message like "Preparing files..." would be useful?

I will prepare a PR as soon as I find the time :)

**Comment by schollz** [comment]
Would accept a PR. in the meantime you can use the flag `--hash imohash` for a faster hash, though the tradeoff is that it might not recognize small changes in the files when comparing.
