### ISSUE TITLE
Unable to transfer if --out is defined

### ISSUE THREAD

**Issue by rgabbo** [schollz/croc#482]
## Describe the bug
I'm unable to transfer file between two devices on same LAN. Both are on Windows 10.

## To Reproduce
1. Command on source `croc send --code password C:\path\to\file`
2. Comand on dest `croc password --out C:\path`
3. Dest device gets stuck at "securing channel..." step

## Expected behaviour
Transfer goes fine.

## Version
croc version v9.5.6-b7e4a73

## Additional context
If --out flag is omitted, everything works fine.

**Comment by schollz** [comment]
Please run with debug flag and share redacted output

**Comment by rgabbo** [comment]
Here is debug from dest. 

> [debug] 18:49:45 cli.go:141: debug mode on
[debug] 18:49:45 croc.go:178: options: {IsSender:false SharedSecret:ZfcUde---out-C:\path Debug:true RelayAddress:5.161.69.143:9009 RelayAddress6:[xxxx:xxx:xx:xxxx::xxx:x]:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false SendingText:false NoCompress:false IP: Overwrite:false Curve:p256 HashAlgorithm: ThrottleUpload:}
connecting...[debug]    18:49:45 croc.go:648: attempt to discover peers
[debug] 18:49:45 croc.go:687: all discoveries: [address: xxxx::xxxx:xxxx:xxx:xxxx%Wi-Fi 2, payload: croc9009 address: 192.168.1.231, payload: croc9009]
[debug] 18:49:45 croc.go:689: discovery 0 has payload: address: xxxx::xxxx:xxxx:xxx:xxxx%Wi-Fi 2, payload: croc9009
[debug] 18:49:45 croc.go:694: switching to local
[debug] 18:49:45 tcp.go:414: pinging [xxxx::xxxx:xxxx:xxx:xxxx%Wi-Fi 2]:9009
[debug] 18:49:45 comm.go:55: dialing to [xxxx::xxxx:xxxx:xxx:xxxx%Wi-Fi 2]:9009 with timelimit 300ms
[debug] 18:49:45 comm.go:60: comm.NewConnection failed: dial tcp [xxxx::xxxx:xxxx:xxx:xxxx%!W(MISSING)i-Fi 2]:9009: i/o timeout
[debug] 18:49:45 tcp.go:417: comm.NewConnection failed: dial tcp [xxxx::xxxx:xxxx:xxx:xxxx%!W(MISSING)i-Fi 2]:9009: i/o timeout
[debug] 18:49:45 croc.go:709: could not ping: comm.NewConnection failed: dial tcp [xxxx::xxxx:xxxx:xxx:xxxx%Wi-Fi 2]:9009: i/o timeout
[debug] 18:49:45 croc.go:689: discovery 1 has payload: address: 192.168.1.231, payload: croc9009
[debug] 18:49:45 croc.go:694: switching to local
[debug] 18:49:45 tcp.go:414: pinging 192.168.1.231:9009
[debug] 18:49:45 comm.go:55: dialing to 192.168.1.231:9009 with timelimit 300ms
[debug] 18:49:46 comm.go:60: comm.NewConnection failed: dial tcp 192.168.1.231:9009: i/o timeout
[debug] 18:49:46 tcp.go:417: comm.NewConnection failed: dial tcp 192.168.1.231:9009: i/o timeout
[debug] 18:49:46 croc.go:709: could not ping: comm.NewConnection failed: dial tcp 192.168.1.231:9009: i/o timeout
[debug] 18:49:46 croc.go:713: discoveries: [address: xxxx::xxxx:xxxx:xxx:xxxx%Wi-Fi 2, payload: croc9009 address: 192.168.1.231, payload: croc9009]
[debug] 18:49:46 croc.go:714: establishing connection
[debug] 18:49:46 croc.go:730: got host 'xxxx:xxx:xx:xxxx::xxx:x' and port '9009'
[debug] 18:49:46 croc.go:732: trying connection to [xxxx:xxx:xx:xxxx::xxx:x]:9009
[debug] 18:49:46 comm.go:55: dialing to [xxxx:xxx:xx:xxxx::xxx:x]:9009 with timelimit 200ms
[debug] 18:49:46 comm.go:60: comm.NewConnection failed: dial tcp [xxxx:xxx:xx:xxxx::xxx:x]:9009: i/o timeout
[debug] 18:49:46 tcp.go:445: comm.NewConnection failed: dial tcp [xxxx:xxx:xx:xxxx::xxx:x]:9009: i/o timeout
[debug] 18:49:46 croc.go:738: could not establish '[xxxx:xxx:xx:xxxx::xxx:x]:9009'
[debug] 18:49:46 croc.go:730: got host '5.161.69.143' and port '9009'
[debug] 18:49:46 croc.go:732: trying connection to 5.161.69.143:9009
[debug] 18:49:46 comm.go:55: dialing to 5.161.69.143:9009 with timelimit 5s
[debug] 18:49:46 comm.go:64: connected to '5.161.69.143:9009'
[debug] 18:49:46 tcp.go:475: strong key: 63132243f5f0849ceed56734c4bd0957e2889e4474649b1ea265d6b4c3bdab7c
[debug] 18:49:46 tcp.go:489: sending password
[debug] 18:49:46 tcp.go:500: waiting for first ok
[debug] 18:49:46 tcp.go:518: sending room
[debug] 18:49:46 tcp.go:529: waiting for room confirmation
[debug] 18:49:46 tcp.go:545: all set
[debug] 18:49:46 croc.go:745: receiver connection established: &{connection:0xc00021e138}
[debug] 18:49:46 croc.go:746: banner: 9010,9011,9012,9013
[debug] 18:49:46 croc.go:751: sending ips?
[debug] 18:49:47 croc.go:760: ips data: ["9009","169.254.187.110","169.254.85.202","169.254.49.8","172.22.81.27","10.0.85.2","169.254.129.109","192.168.1.231"]
[debug] 18:49:47 croc.go:770: ipv4Add4: 169.254.187.110, ipv4Net: 169.254.187.0/24, err: <nil>
[debug] 18:49:47 croc.go:781: 169.254.187.110 is not a local IP, skipping
[debug] 18:49:47 croc.go:770: ipv4Add4: 169.254.85.202, ipv4Net: 169.254.85.0/24, err: <nil>
[debug] 18:49:47 croc.go:781: 169.254.85.202 is not a local IP, skipping
[debug] 18:49:47 croc.go:770: ipv4Add4: 169.254.49.8, ipv4Net: 169.254.49.0/24, err: <nil>
[debug] 18:49:47 croc.go:781: 169.254.49.8 is not a local IP, skipping
[debug] 18:49:47 croc.go:770: ipv4Add4: 172.22.81.27, ipv4Net: 172.22.81.0/24, err: <nil>
[debug] 18:49:47 croc.go:781: 172.22.81.27 is not a local IP, skipping
[debug] 18:49:47 croc.go:770: ipv4Add4: 10.0.85.2, ipv4Net: 10.0.85.0/24, err: <nil>
[debug] 18:49:47 comm.go:55: dialing to 10.0.85.2:9009 with timelimit 500ms
[debug] 18:49:48 comm.go:60: comm.NewConnection failed: dial tcp 10.0.85.2:9009: i/o timeout
[debug] 18:49:48 tcp.go:445: comm.NewConnection failed: dial tcp 10.0.85.2:9009: i/o timeout
[debug] 18:49:48 croc.go:788: comm.NewConnection failed: dial tcp 10.0.85.2:9009: i/o timeout
[debug] 18:49:48 croc.go:789: could not connect to 10.0.85.2:9009
[debug] 18:49:48 croc.go:770: ipv4Add4: 169.254.129.109, ipv4Net: 169.254.129.0/24, err: <nil>
[debug] 18:49:48 croc.go:781: 169.254.129.109 is not a local IP, skipping
[debug] 18:49:48 croc.go:770: ipv4Add4: 192.168.1.231, ipv4Net: 192.168.1.0/24, err: <nil>
[debug] 18:49:48 comm.go:55: dialing to 192.168.1.231:9009 with timelimit 500ms
[debug] 18:49:48 comm.go:64: connected to '192.168.1.231:9009'
[debug] 18:49:48 tcp.go:475: strong key: 44fa866665899acbe30da583ed386f8f2e198f8be34d192169d04edbbc3bd352
[debug] 18:49:48 tcp.go:489: sending password
[debug] 18:49:48 tcp.go:500: waiting for first ok
[debug] 18:49:48 tcp.go:518: sending room
[debug] 18:49:48 tcp.go:529: waiting for room confirmation
[debug] 18:49:48 tcp.go:545: all set
[debug] 18:49:48 croc.go:792: local connection established to 192.168.1.231:9009
[debug] 18:49:48 croc.go:793: banner: 9010,9011,9012,9013
[debug] 18:49:48 croc.go:814: exchanged header message
securing channel...[debug]      18:49:48 croc.go:832: ready
[debug] 18:49:48 message.go:61: writing pake message (unencrypted)
[debug] 18:49:48 message.go:80: read pake message (unencrypted)
[debug] 18:49:48 croc.go:1047: received pake payload
[debug] 18:49:48 croc.go:1094: generated key = 532415b81daf3650ebc0317e7fbcdbe4e2a582c2eb1ffadda39a62a958420e02 with salt b8f216a219252a8c
[debug] 18:49:48 croc.go:1100: port: [9010]
[debug] 18:49:48 croc.go:1114: connecting to 192.168.1.231:9010
[debug] 18:49:48 croc.go:1100: port: [9011]
[debug] 18:49:48 croc.go:1100: port: [9012]
[debug] 18:49:48 croc.go:1114: connecting to 192.168.1.231:9011
[debug] 18:49:48 croc.go:1100: port: [9013]
[debug] 18:49:48 comm.go:55: dialing to 192.168.1.231:9010 with timelimit 30s
[debug] 18:49:48 croc.go:1114: connecting to 192.168.1.231:9012
[debug] 18:49:48 comm.go:55: dialing to 192.168.1.231:9011 with timelimit 30s
[debug] 18:49:48 croc.go:1114: connecting to 192.168.1.231:9013
[debug] 18:49:48 comm.go:55: dialing to 192.168.1.231:9013 with timelimit 30s
[debug] 18:49:48 comm.go:64: connected to '192.168.1.231:9010'
[debug] 18:49:48 comm.go:55: dialing to 192.168.1.231:9012 with timelimit 30s
[debug] 18:49:48 comm.go:64: connected to '192.168.1.231:9011'
[debug] 18:49:48 comm.go:64: connected to '192.168.1.231:9013'
[debug] 18:49:48 comm.go:64: connected to '192.168.1.231:9012'
[debug] 18:49:48 tcp.go:475: strong key: 3858482223214d4e425c34008ae1e08a27c5f8a7ae0cb3d490654defc3cdc820
[debug] 18:49:48 tcp.go:489: sending password
[debug] 18:49:48 tcp.go:500: waiting for first ok
[debug] 18:49:48 tcp.go:475: strong key: e2af2b45ea6d6540410409ace7833fb4926c791810e00794818579c4d411dd84
[debug] 18:49:48 tcp.go:475: strong key: af439eb3e3f9a0af2677f35cf9f8c0d0307a18d0183032f0e14bc8f8dff21386
[debug] 18:49:48 tcp.go:475: strong key: c88fd9dc3339f69b3058fe94a442a7dc786c63c918f50978641ef181b0585710
[debug] 18:49:48 tcp.go:489: sending password
[debug] 18:49:48 tcp.go:518: sending room
[debug] 18:49:48 tcp.go:489: sending password
[debug] 18:49:48 tcp.go:489: sending password
[debug] 18:49:48 tcp.go:500: waiting for first ok
[debug] 18:49:48 tcp.go:529: waiting for room confirmation
[debug] 18:49:48 tcp.go:500: waiting for first ok
[debug] 18:49:48 tcp.go:500: waiting for first ok
[debug] 18:49:48 tcp.go:545: all set
[debug] 18:49:48 croc.go:1123: connected to 192.168.1.231:9010
[debug] 18:49:48 tcp.go:518: sending room
[debug] 18:49:48 croc.go:1631: 0 receiving data
[debug] 18:49:48 tcp.go:518: sending room
[debug] 18:49:48 croc.go:1638: got ping
[debug] 18:49:48 tcp.go:529: waiting for room confirmation
[debug] 18:49:48 tcp.go:518: sending room
[debug] 18:49:48 tcp.go:529: waiting for room confirmation
[debug] 18:49:48 tcp.go:529: waiting for room confirmation
[debug] 18:49:48 tcp.go:545: all set
[debug] 18:49:48 croc.go:1123: connected to 192.168.1.231:9011
[debug] 18:49:48 croc.go:1631: 1 receiving data
[debug] 18:49:48 tcp.go:545: all set
[debug] 18:49:48 croc.go:1123: connected to 192.168.1.231:9012
[debug] 18:49:48 croc.go:1638: got ping
[debug] 18:49:48 croc.go:1631: 2 receiving data
[debug] 18:49:48 tcp.go:545: all set
[debug] 18:49:48 croc.go:1123: connected to 192.168.1.231:9013
[debug] 18:49:48 croc.go:1132: sending external IP
[debug] 18:49:48 croc.go:1638: got ping
[debug] 18:49:48 croc.go:1631: 3 receiving data
[debug] 18:49:48 message.go:58: writing externalip message (encrypted)
[debug] 18:49:48 croc.go:1638: got ping
[debug] 18:49:48 comm.go:128: initial read error: EOF
[debug] 18:49:48 comm.go:128: initial read error: EOF
[debug] 18:49:48 comm.go:128: initial read error: EOF
[debug] 18:49:48 croc.go:850: got error receiving: EOF
[debug] 18:49:48 comm.go:128: initial read error: EOF
[debug] 18:49:48 comm.go:128: initial read error: EOF
2022/05/29 18:49:48 could not secure channel

**Comment by BlinkDL** [comment]
I got the same issue sending from linux to linux. Remove --out and it works.

**Comment by schollz** [comment]
I cannot reproduce.  @rgabbo are you still having this error. @BlinkDL can you please share the debug output?

**Comment by BlinkDL** [comment]
croc version v9.5.5-a6a3a57

**Comment by schollz** [comment]
Can you reproduce errors with the latest version?

**Comment by ItsRevolt** [comment]
Since OP didn't respond, I am currently on the latest version still receiving this error.

**Comment by schollz** [comment]
@ItsRevolt can you verify you have the same problem? are you also using only LAN? what error message are you getting? what version of croc are you using? can you share debug output?

**Comment by schollz** [comment]
Closing issue since no response from OP

**Comment by rgabbo** [comment]
Sorry for the late reply. I didn't think you were referring to me. However I encounter the same error with croc version v9.6.0-0e93f1e

**Comment by Some1ls** [comment]
I'm using v9.6.1-b27982a and I'm still having the same problem with android to window transfer.
