### ISSUE TITLE
Stdout in plain text format for working with any program wrappers

### ISSUE THREAD

**Issue by freeacetone** [schollz/croc#486]
I complete GUI for croc ([repo](https://github.com/freeacetone/croc-gui)). It based on Qt5/C++, main interaction with croc CLI based on QProcess class of Qt5 library. This provides the ability to run applications, pass parameters, and read their output. 

I can fine run croc with `--version` parameter to see croc version in my application, but real job (receive and send) not handling by my application. Seems like this operations using not plain text out. I tried handle STDOUT and STDERR and so I not find some way to resolve my case.

I requesting some flag like a `--plaintext` to get croc with plain text out (it can be without pseudo progress bar, only parseble data). For example: `totalfiles=4 currentfile=2 currentfilename="somefile.bin" currentfileweight=17310237 currentreceived=12341`. Of course you can give me more simple out like a your current preudo GUI, but in plain text mode. I'll happy and croc will have GUI brother :) 

Thanks for development.

![Безымянный](https://user-images.githubusercontent.com/63557806/176674499-aacad370-13d7-4722-b310-53da0f7fb919.png)
![Безымянный](https://user-images.githubusercontent.com/63557806/176674603-95fe14e8-24b5-4d5c-8564-355674d2c320.png)

**Comment by connected201** [comment]
Good idea and nice gui!

**Comment by schollz** [comment]
Happy to review a PR for this
