### ISSUE TITLE
data race in `cli.relay`

### ISSUE THREAD

**Issue by chavacava** [schollz/croc#493]
In the following code, there is a data race over the `err` return value.
https://github.com/schollz/croc/blob/1851327df7e882447b747fba6a45b62e9e634fe1/src/cli/cli.go#L459-L480

The goroutine(s) started at line 472 captures by reference the `err` return value and assigns to it at line 473. The same variable is (implicitly) assigned at the `return` statement at line 479.

Found with [`revive`](https://github.com/mgechev/revive)'s rule `datarace`

**Comment by schollz** [comment]
Thanks, would accept a PR to address this.
