### ISSUE TITLE
Croc relay server issue

### ISSUE THREAD

**Issue by BilliBoleMeow** [schollz/croc#495]
## Describe the bug
Not able to connect to Relay server 

## To Reproduce
1. Setup a realy server on heroku 4 testing (default required port exposed)
2. Sent a file from computer A
3. Tried receiving file on computer b
4. Got error i/o timeout 

## Expected behaviour
It should be able to connect

## Version
9.6.0

## Additional context

Log From Relay server 

      
Application Logs
2022-07-18T15:54:48.911530+00:00 heroku[worker.1]: State changed from starting to up
2022-07-18T15:54:49.194677+00:00 app[worker.1]: [0;37m[info]	[0m2022/07/18 15:54:49 starting croc relay version v9.6.0-0e93f1e
2022-07-18T15:54:49.194790+00:00 app[worker.1]: [0;37m[info]	[0m2022/07/18 15:54:49 starting TCP server on :9009
2022-07-18T15:54:49.194823+00:00 app[worker.1]: [0;37m[info]	[0m2022/07/18 15:54:49 starting TCP server on :9010
2022-07-18T15:54:49.195138+00:00 app[worker.1]: [0;37m[info]	[0m2022/07/18 15:54:49 starting TCP server on :9012
2022-07-18T15:54:49.195198+00:00 app[worker.1]: [0;37m[info]	[0m2022/07/18 15:54:49 starting TCP server on :9011
2022-07-18T15:54:49.195682+00:00 app[worker.1]: [0;37m[info]	[0m2022/07/18 15:54:49 starting TCP server on :9013

Log From Computer A (sender)

croc --debug --relay ghcfhbb.herokuapp.com:9009 send 1.jpg
[debug]03:38:12 cli.go:142: debug mode on
[debug]03:38:12 croc.go:180: options: {IsSender:true SharedSecret:0006-ticket-hilton-everest Debug:true RelayAddress:ghcfhbb.herokuapp.com:9009 RelayAddress6: RelayPorts:[9009 9010 9011 9012 9013] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false SendingText:false NoCompress:false IP: Overwrite:false Curve:p256 HashAlgorithm:xxhash ThrottleUpload: ZipFolder:false}
[debug]03:38:12 croc.go:395: hashed /home/ubuntu/1/1.jpg to eaa43c7af752432d using xxhash
[debug]03:38:12 croc.go:400: file 0 info: {Name:1.jpg FolderRemote:./ FolderSource:/home/ubuntu/1 Hash:[234 164 60 122 247 82 67 45] Size:158584 ModTime:2022-07-18 16:02:56.225299557 +0000 UTC IsCompressed:false IsEncrypted:false Symlink: Mode:-rw-rw-r-- TempFile:false}
Sending 0 files (154.9 kB)[debug]03:38:12 croc.go:404: longestFilename: 5Sending '1.jpg' (154.9 kB)       
Code is: 0006-ticket-hilton-everest
On the other computer run

croc --relay ghcfhbb.herokuapp.com:9009 0006-ticket-hilton-everest
[debug]03:38:12 tcp.go:59: starting with password 'pass123'
[debug]03:38:12 tcp.go:59: starting with password 'pass123'
[info]2022/07/19 03:38:12 starting TCP server on 0.0.0.0:9013
[debug]03:38:12 tcp.go:59: starting with password 'pass123'
[info]2022/07/19 03:38:12 starting TCP server on 0.0.0.0:9011
[debug]03:38:12 tcp.go:59: starting with password 'pass123'
[info]2022/07/19 03:38:12 starting TCP server on 0.0.0.0:9012
[debug]03:38:12 croc.go:561: host: 'ghcfhbb.herokuapp.com', port: '9009'
[debug]03:38:12 croc.go:567: got host 'ghcfhbb.herokuapp.com' and port '9009'
[debug]03:38:12 croc.go:569: trying connection to ghcfhbb.herokuapp.com:9009
[debug]03:38:12 comm.go:55: dialing to ghcfhbb.herokuapp.com:9009 with timelimit 5s
[info]2022/07/19 03:38:12 starting TCP server on 0.0.0.0:9010
[debug]03:38:12 tcp.go:59: starting with password 'pass123'
[info]2022/07/19 03:38:12 starting TCP server on 0.0.0.0:9009
[debug]03:38:12 croc.go:479: establishing connection
[debug]03:38:12 comm.go:55: dialing to localhost:9009 with timelimit 30s
[debug]03:38:12 comm.go:64: connected to 'localhost:9009'
[debug]03:38:12 tcp.go:124: client 127.0.0.1:42020 connected
[debug]03:38:12 tcp.go:187: Abytes: {"Role":0,"Uᵤ":793136080485469241208656611513609866400481671853,"Uᵥ":18458907634222644275952014841865282643645472623913459400556233196838128612339,"Vᵤ":1086685267857089638167386722555472967068468061489,"Vᵥ":19593504966619549205903364028255899745298716108914514072669075231742699650911,"Xᵤ":1016731034795572798283866903099014368056002648456169741597734460055140383998,"Xᵥ":21061974180853255056146903880285765618477612683656791237910500292650576949131,"Yᵤ":null,"Yᵥ":null,"P":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug]03:38:12 tcp.go:206: strongkey: xxx
[debug]03:38:12 tcp.go:475: strong key: xxx
[debug]03:38:12 tcp.go:489: sending password
[debug]03:38:12 tcp.go:500: waiting for first ok
[debug]03:38:12 tcp.go:218: waiting for password
[debug]03:38:12 tcp.go:241: sending '9010,9011,9012,9013'
[debug]03:38:12 tcp.go:252: waiting for answer
[debug]03:38:12 tcp.go:518: sending room
[debug]03:38:12 tcp.go:529: waiting for room confirmation
[debug]03:38:12 tcp.go:283: room 000 has 1
[debug]03:38:12 tcp.go:128: room: 000
[debug]03:38:12 tcp.go:129: err: <nil>
[debug]03:38:12 tcp.go:545: all set
[debug]03:38:12 croc.go:482: banner: 9010,9011,9012,9013
[debug]03:38:12 croc.go:489: local connection established: &{connection:0x4000232148}
[debug]03:38:12 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:12 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:12 croc.go:495: got ping
[debug]03:38:13 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:13 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:13 croc.go:495: got ping
[debug]03:38:14 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:14 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:14 croc.go:495: got ping
[debug]03:38:15 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:15 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:15 croc.go:495: got ping
[debug]03:38:16 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:16 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:16 croc.go:495: got ping
[debug]03:38:17 comm.go:60: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
[debug]03:38:17 tcp.go:445: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
[debug]03:38:17 croc.go:575: could not establish 'ghcfhbb.herokuapp.com:9009'
[debug]03:38:17 croc.go:582: could not connect to ghcfhbb.herokuapp.com:9009: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
[debug]03:38:17 croc.go:641: error from errchan: could not connect to ghcfhbb.herokuapp.com:9009: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
[debug]03:38:17 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:17 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:17 croc.go:495: got ping
[debug]03:38:18 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:18 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}
[debug]03:38:18 croc.go:495: got ping
[debug]03:38:19 tcp.go:142: checking connection of room 000 for &{connection:0x400029a040}
[debug]03:38:19 tcp.go:150: room: {first:0x400022f540 second:<nil> opened:{wall:13883937571442177928 ext:518914751 loc:0x5829a0} full:false}

Log from computer b (receiver)

croc --relay ghcfhbb.herokuapp.com:9009 7453-carrot-monica-major
connecting...2022/07/19 03:31:01 could not connect to ghcfhbb.herokuapp.com:9009: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
~ $ croc --debug  --relay ghcfhbb.herokuapp.com:9009 7453-carrot-monica-major
[debug] 03:31:19 cli.go:142: debug mode on
[debug] 03:31:19 croc.go:180: options: {IsSender:false SharedSecret:7453-carrot-monica-major Debug:true RelayAddress:ghcfhbb.herokuapp.com:9009 RelayAddress6: RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false SendingText:false NoCompress:false IP: Overwrite:false Curve:p256 HashAlgorithm: ThrottleUpload: ZipFolder:false}
connecting...[debug]    03:31:19 croc.go:682: attempt to discover peers
[debug] 03:31:20 croc.go:747: discoveries: []
[debug] 03:31:20 croc.go:748: establishing connection
[debug] 03:31:20 croc.go:764: got host 'ghcfhbb.herokuapp.com' and port '9009'
[debug] 03:31:20 croc.go:766: trying connection to ghcfhbb.herokuapp.com:9009
[debug] 03:31:20 comm.go:55: dialing to ghcfhbb.herokuapp.com:9009 with timelimit 5s
[debug] 03:31:25 comm.go:60: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
[debug] 03:31:25 tcp.go:445: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
[debug] 03:31:25 croc.go:772: could not establish 'ghcfhbb.herokuapp.com:9009'
[debug] 03:31:25 croc.go:776: could not connect to ghcfhbb.herokuapp.com:9009: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout
2022/07/19 03:31:25 could not connect to ghcfhbb.herokuapp.com:9009: comm.NewConnection failed: dial tcp 23.22.144.165:9009: i/o timeout

**Comment by hsm2k3** [comment]
@BilliBoleMeow looks like you need a min of 2 relay ports open when you self host according to the [docs](https://github.com/schollz/croc/blob/main/README.md#:~:text=minimum%20of%202%20ports%20for%20the%20relay).

**Comment by BilliBoleMeow** [comment]
> @BilliBoleMeow looks like you need a min of 2 relay ports open when you self host according to the [docs](https://github.com/schollz/croc/blob/main/README.md#:~:text=minimum%20of%202%20ports%20for%20the%20relay).

![IMG_20220731_211422](https://user-images.githubusercontent.com/88665437/182034295-9e72c43c-f4e6-4666-88f2-645d6b4f5fee.jpg)

I did exposed the required ports.

**Comment by schollz** [comment]
can you test it by running it locally on your heroku machine? i.e. using relay localhost:9009

**Comment by BilliBoleMeow** [comment]
> can you test it by running it locally on your heroku machine? i.e. using relay localhost:9009

Found the reason

https://stackoverflow.com/questions/18600814/deploying-a-tcp-server-to-heroku

Alot of hour wasted. 🥲

**Comment by BilliBoleMeow** [comment]
> 

I will still report this.

**Comment by BilliBoleMeow** [comment]
> can you test it by running it locally on your heroku machine? i.e. using relay localhost:9009

I will still Report the outcome of this
