### ISSUE TITLE
Add zstd as a compression algorithm. 

### ISSUE THREAD

**Issue by stefins** [schollz/croc#504]
**Is your feature request related to a problem? Please describe.**
It would be better to add `zstd` as a compression algorithm for transferring file as it provides high compression ratio. 

**Describe the solution you'd like**
We can use the go library https://github.com/DataDog/zstd for it.

**Additional context**
https://facebook.github.io/zstd/

**Comment by schollz** [comment]
Would accept a PR for this

**Comment by stefins** [comment]
Closed in #506

**Comment by schollz** [comment]
@stefins sorry - I reverted this change because unfortunately there is no scheme in place to have different compression algorithms so this would be a breaking change. I'm okay with a breaking change, but I'll wait a bit before releasing it, possibly with another breaking change

**Comment by stefins** [comment]
Sure! No problem :)
