### ISSUE TITLE
Listen for Sender available?

### ISSUE THREAD

**Issue by lam4562311** [schollz/croc#505]
For now, the croc would allow the sender would wait for the receiver if available, then send the file. When there is no sender, the receiver cannot find an available room and shut down the connection with the current passphrase. 

It is possible to have a feature that allows the receiver waits for the sender to available for a dedicated passphrase. 

Or is there any way to do a one-way sync based on croc? I don't want to keep creating a process on build a new connection channel with the sender.

**Comment by mimi3421** [comment]
I also consider this as a important feature, otherwise it would be useless to manually assign the code at the sender's side.

I just use the loop to check if the sender is ready, though which seems quite silly.

``` bash
until ./croc --yes 108765-broken-margo
   do
       echo waiting link
       sleep 20
   done
```

**Comment by lllllll-llll-llllll** [comment]
It would be cool to have this as a recipient-specific option (like --wait ?) to wait for the sender.
