### ISSUE TITLE
Will Just freeze

### ISSUE THREAD

**Issue by DillFrescott** [schollz/croc#507]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
The transfer completely freezes and will not resume. No errors are thrown.

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->
I'd expect the transfer to complete without issue.

## Version
<-- Check "croc -v" and report it -->
croc version v9.6.0-0e93f1e

## Additional context
<-- Add any other context about the problem here. -->
![Screenshot 2022-10-01 190309](https://user-images.githubusercontent.com/56714680/193431368-aee67a2b-47a7-4e19-9582-4afc34ed0429.png)

A photo of where it happened to get stuck this time.

**Comment by schollz** [comment]
Is it reproducible?

**Comment by DillFrescott** [comment]
Yes, it seems to happen every single time at a different point.

**Comment by DillFrescott** [comment]
![Screenshot 2022-10-01 190943](https://user-images.githubusercontent.com/56714680/193431476-0acb5e65-87ca-490d-9cc8-a1f232eb3ee9.png)
The EOF is where i force cancelled it after it had been stuck for a while...

**Comment by schollz** [comment]
Please describe the steps to reproduce

**Comment by DillFrescott** [comment]
1. Start a transfer from one computer to another
2. It freezes

**Comment by DillFrescott** [comment]
I have experienced this bug across several versions of croc and on multiple different networks. Not sure whats going on

**Comment by schollz** [comment]
> 1. Start a transfer from one computer to another
> 
>     2. It freezes

I can't replicate it following these steps.

**Comment by DillFrescott** [comment]
I think maybe we should put this off until I can better understand why exactly it's happening. I can let you know if I ever figure out what might be the cause

**Comment by x1y9** [comment]
I had same issue.

![image](https://github.com/user-attachments/assets/bfcb7524-8363-4a5c-b2c0-84fb517f07bf)

It seems that the problem only occurs in one direction, in the other direction it is always fine.
