### ISSUE TITLE
Installation fails with The requested URL returned error

### ISSUE THREAD

**Issue by RodolfoGS** [schollz/croc#509]
## Describe the bug

The instalation process fails with the following error:

```
\e[0m== Install prefix set to /usr/local/bin\e[0m
\e[0m== Created temp dir at /var/folders/5t/v_z_k0gx7m99jw6blgsj_dqh0000gn/T/croc.XXXXXX.UjlToaoB\e[0m
\e[0m== Architecture detected as arm64\e[0m
\e[0m== OS detected as Darwin\e[0m
curl: (22) The requested URL returned error: 404
\e[0;31m== Return code of download tool returned an unexpected value of 22\e[0m
```

## To Reproduce
1. `curl https://getcroc.schollz.com | bash`
2. Error happens

## Expected behaviour

Instalation success

## Version

Can't install the latest version.

## Additional context

MacOS 12.6

**Comment by UnrelatedWorks** [comment]
It seems like the base URL (https://github.com/schollz/croc/releases/download) defined in line 533 is unreachable. 

croc_base_url="https://github.com/schollz/croc/releases/download"

**Comment by UnrelatedWorks** [comment]
I've tried to debug the code a bit. By hardcoding the local url variable to the direct download (https://github.com/schollz/croc/releases/download/v9.6.1/croc_9.6.1_macOS-ARM64.tar.gz), I'm able to circumvent the 404 error.  
But the \e[0m==  at the start of every line still bothers me, I don't know where it's getting the value from.

**Comment by juliangaal** [comment]
I am facing the same issue on MacOS, but not an linux. Maybe is has something to do with zsh
