### ISSUE TITLE
"Did you mean to send" blank on Windows when sending folders

### ISSUE THREAD

**Issue by TheFiZi** [schollz/croc#511]
## Describe the bug

When sending a directory via PowerShell 7.x on Windows 11 the name of the file being sent is blank:

```
PS D:\> croc --pass MYPASS --relay "MYRELAY:9009" '.\MYFOLDER\'
Did you mean to send ''? (Y/n) y
Sending 103 files and 1 folders (17.3 GB)
```

## To Reproduce

1. Send a directory via `croc --pass MYPASS --relay "MYRELAY:9009" '.\MYFOLDER\'`

## Expected behaviour

Output should probably be: `Did you mean to send '.\MYFOLDER\*'? (Y/n)`

## Version

v9.6.1-b27982a

**Comment by schollz** [comment]
Would accept a PR for this.
