### ISSUE TITLE
Debian/Ubuntu package

### ISSUE THREAD

**Issue by slhck** [schollz/croc#521]
**Is your feature request related to a problem? Please describe.**

There appear to be direct installation options for Arch, Fedora, Gentoo, FreeBSD and others, but not Debian and Ubuntu.

**Describe the solution you'd like**

An official package so that users can do `apt install croc`.

I hope that this would be posible given that packages for other distros/package managers exist already.

**Describe alternatives you've considered**

Direct installation via Bash, but this of course requires users to perform updates manually.

~~There used to be a snap, as far as I can tell, but snaps are problematic in their own way.~~ (Apparently snap packages were never considered for good reasons: https://github.com/schollz/croc/pull/479)

**Comment by schollz** [comment]
Yes would appreciate a PR for this, or instructions on how to go about it.

**Comment by slhck** [comment]
To be honest, I don't know how this works in practice. Normally these packages are maintained by the distro providers. Who created the Fedora etc versions?

**Comment by Kyr4l** [comment]
i'm also wondering why there's no apt package yet, every popular distro has a native package except debian/ubuntu...

**Comment by slhck** [comment]
I think there are two options:

- Get someone from the Debian/Ubuntu community to create a package and maintain it
- Host your own PPA: https://launchpad.net/ubuntu/+ppas

**Comment by bgvaughan** [comment]
I'm not an expert on Debian's processes, but I think the crux of it is that you need packages conformant to Debian's policies, and someone willing to act as a package maintainer. It looks like there are already processes in place to produce .deb files, so I'd think most of the technical work is done.
https://debian-handbook.info/browse/stable/sect.becoming-package-maintainer.html

**Comment by rzr** [comment]
This is desirable the first  step would be to file a ticket as Request for Software RFS is there any filed already?

**Comment by slhck** [comment]
You mean Request for Package? There is one here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017956

**Comment by slhck** [comment]
Stale but still relevant. I'd suggest keeping this open for reference.

**Comment by guilherme-puida** [comment]
Hey! Just wanted to mention that I'm currently working on packaging croc for Debian. It's a long process, but I'll update here when it hits the unstable archives.

**Comment by guilherme-puida** [comment]
Hi! I just wanted to mention that I have packaged all of croc's dependencies and croc itself. It is in a good shape to be included in Debian.

However, I'm not too keen on introducing new software on Debian with multiple open CVEs. [This comment](https://github.com/schollz/croc/issues/593#issuecomment-1932079815) was not very encouraging, and the xz scandal has made me think more about giving unrestricted commit access to projects (even more dangerous when networking is in the picture).

I won't object if someone wants to take over, but I won't be working on this anytime soon.

**Comment by schollz** [comment]
hi @guilherme-puida I'd prefer if croc is not included in debian. the server costs are getting to high for me so less people using croc is better unless the financial situation improves.

**Comment by nbolton** [comment]
Can I help? How high are the costs? I'm very interested in helping people transfer things between multiple computers.

**Comment by schollz** [comment]
Thanks @nbolton for the kind comments :) 

> Can I help?

Yes! The biggest help is to provide a monthly sponsorship: https://github.com/sponsors/schollz

The monthly sponsorship is so helpful because it helps me rely on periodic + consistent cost assistance.

Helping to increase the number of sponsors will help immensely too...sponsors disappear sometimes so having lots of little sponsorships means that I can rely more on a consistent monthly contribution. 

> How high are the costs? 

I'm using a medium-sized server on Hetzner, it comes with 20TB of bandwidth. Currently, croc is just exceeding that every month with incurs overage costs. I'd like to upgrade to 30TB/month (~$50/month) but I'm still short enough subscribers to make this change without worrying I'll be paying out of pocket in the future. 

The $50/month might not sound like a lot, but I plan to keep croc around for at least another 20 or 30 years (it's already been up for 6+ years without interruption), so it does end up being a big chunk of money in the long-term.

**Comment by nbolton** [comment]
You make a good pitch! Sponsored $50/mo for a year.

**Comment by schollz** [comment]
Thank you @nbolton! That is so generous of you. I will be able to upgrade this month :rocket:

**Comment by nbolton** [comment]
Keep up the awesome work, and I hope `croc` becomes a Debian package someday. I belive that it's important. That said, `curl https://getcroc.schollz.com | bash` was shockingly easy! :laughing:

**Comment by milabs** [comment]
> That said, `curl https://getcroc.schollz.com | bash` on Debian was shockingly easy! 😆

Doesn't work with `doas` as `sudo` replacement.
