### ISSUE TITLE
Tab completion for words

### ISSUE THREAD

**Issue by BayLee4** [schollz/croc#523]
Typing multiple long words could be fastidious, having them autocomplete after hitting Tab once the first letters are typed would be great.

I heavily used this feature from [magic-wormhole](https://github.com/magic-wormhole/magic-wormhole), which isn't shell completion: the completion is only possible when the program is already running with `wormhole receive` (which is the equivalent of running `croc`). Currently when running `croc`, after correctly typing the numbers then the first few letters of a word and hitting Tab, there is no completion, just spaces.

**Comment by schollz** [comment]
Happy to accept PR for this

**Comment by BayLee4** [comment]
It seems the magic-wormhole completion implementation is [~30 lines](https://github.com/magic-wormhole/magic-wormhole/blob/1debcb7438e26a1974056611c1f98a16d6aec544/src/wormhole/_wordlist.py#L291-L323), and that the [mnemonicode](https://github.com/schollz/mnemonicode/commit/c71b47331468669ba648d543813e41e9f4b64e4e) library used here exports its wordlist, I guess it shouldn't be too hard to implement this feature then

Could you please point me where I should look at for the function reading the user input? I don't know Go but trying to implement this feature could be a fun way to discover the language
