### ISSUE TITLE
Croc should preserve the file mode of the transferred files.

### ISSUE THREAD

**Issue by stefins** [schollz/croc#530]
Hi,
> Croc should preserve the file mode of the transferred iles.

**Is your feature request related to a problem? Please describe.**
When I'm transferring executable files using `croc` the file is written in the destination device without execution permission.
Eg. File with `-rwxrwxr-x` is written with `-rw-r--r--` on receiver end.

**Describe the solution you'd like**
We can read the file mode from the sender and create the new file with those mode in the receiver node. 

Thanks :)

**Comment by schollz** [comment]
Happy to accept a PR for this.
