### ISSUE TITLE
tab completion (minor addition)

### ISSUE THREAD

**Issue by leapfog** [schollz/croc#537]
I really like the new tab completion. There is one little thing that could still be improved. Let's compare it to bash's completion used for `cd`: When tab-completing a directory name, the following `slash` is also added and doesn't need to by typed. Could you add the `dash` after a word as well?

**Comment by schollz** [comment]
Would accept as a PR

**Comment by BayLee4** [comment]
That is a very good idea, I'll submit a PR implementing it.
