### ISSUE TITLE
[Help]: want to send files using "multithreading"

### ISSUE THREAD

**Issue by omaru-ok** [schollz/croc#538]
**Is your feature request related to a problem? Please describe.**
speed is slow when sending many small files like 50KB but 100 files , but my full internet capabilities is 6MB but in small files it become so low that it takes time to send , 
**Describe the solution you'd like**
just a way to sending them usiing threading or something like to speed up the process
**Describe alternatives you've considered**
im a noob , idk , just tell me if u know

**Additional context**
none--

**Comment by PThorpe92** [comment]
Have you tried compressing them first and sending the .gz | .7z file?

**Comment by omaru-ok** [comment]
@PThorpe92 nope , but i dont want 7z , since cpu is slow in compressing , and i dont have enough time to spend with machine which i was trying this thing on 
since i only was using this machien for gpu use not cpu use :( 
hope u understand

**Comment by schollz** [comment]
The --zip flag will bundle files quickly for sending

**Comment by omaru-ok** [comment]
im getting error
did `croc --zip send .\Videos\editor\  `
error 
```
2023/03/10 18:54:47 flag provided but not defined: -zip
```

**Comment by omaru-ok** [comment]
im getting error
did `croc --zip send .\Videos\editor\  `
error 
```
2023/03/10 18:54:47 flag provided but not defined: -zip
```

**Comment by omaru-ok** [comment]
im getting error
did `croc --zip send .\Videos\editor\  `
error 
```
2023/03/10 18:54:47 flag provided but not defined: -zip
```

**Comment by schollz** [comment]
croc send --zip file
