### ISSUE TITLE
Make using one connection the default.

### ISSUE THREAD

**Issue by goggle** [schollz/croc#54]
I don't really see a big benefit of having multiple connections open to send/receive a file over the network. The current default of "number of connections" is currently set to 4. I think croc should respect the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle), so it would be good to have the "number of connections" option set to 1 as default. It is nice to have this feature though.

Is it possible to have this changed?

**Comment by schollz** [comment]
Are you sure you see no improvement with more than one thread? Currently one thread is the default for small files, but I see improvements for more than one thread for bigger files. I'm not sure why there is a benefit at all, but I can see one when I test. My test is to send 30MB folder from one computer at work to my computer at home.  I did each trial three times and took the average of the three measurements.

| Threads        | Sender   (MB/s)      | Receiver (MB/s)  |
| ------------- |:-------------:| -----:|
| 1      |  2.0  | 1.8 |
| 2 | 2.3  | 2.1 |
| 4      |  3.8   | 3.4    |

**Comment by goggle** [comment]
Thanks, your benchmark shows, that it makes sense (at least for somewhat bigger files) to send files over multiple connections.

The thing that annoys me, is that we also see multiple progress bars when we use multiple connections. The end user do not care about the progress for each single connection, they care about the overall progress of sending/receiving the file. Is it possible the merge these multiple progress bars into one?

**Comment by schollz** [comment]
Yes! Already done: e3ff37cce8dd1dfcd2efc71422ca6da87e38765f. I was annoyed that the uiprogress bar wasn't OS specific so I just made a single simple progressbar that is shown.
