### ISSUE TITLE
how to use it in ESXi OS?

### ISSUE THREAD

**Issue by p2o5** [schollz/croc#540]
runtime stack:
runtime.throw({0x78164a?, 0xc000049840?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000497d0 sp=0xc0000497a0 pc=0x434a7d
runtime.netpoll(0x159fd8d0d56bb?)
        /usr/local/go/src/runtime/netpoll_epoll.go:121 +0x34a fp=0xc000049e50 sp=0xc0000497d0 pc=0x430d8a
runtime.findRunnable()
        /usr/local/go/src/runtime/proc.go:2971 +0x765 fp=0xc000049f58 sp=0xc000049e50 pc=0x43cb65
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:3360 +0xb1 fp=0xc000049f90 sp=0xc000049f58 pc=0x43dcf1
runtime.park_m(0xc000006b60?)

**Comment by schollz** [comment]
Please submit again following the template.
