### ISSUE TITLE
can't send large files

### ISSUE THREAD

**Issue by aqtsalt** [schollz/croc#560]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
when sending large files, the command does not respond

## To Reproduce
<-- 1. Go to '...'
4. See error -->

1. send large file (100gb)
2. do `croc send filename --code abcdeabcde`
4. no output in the terminal after waiting 5 minutes
5. if running `croc abcdeabcde` on another computer, it says room not ready

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->
it should respond 

`On the other computer run croc abcdeabcde`

and on the other computer, it starts transferring

## Version
<-- Check "croc -v" and report it -->

## Additional context
<-- Add any other context about the problem here. -->

**Comment by stefins** [comment]
how big is the file?

**Comment by zenyr** [comment]
Try lighter hashing algorithms: `croc send --hash imohash <your_file>` and see if it improves your experience. Consult Readme for caveats!

**Comment by aqtsalt** [comment]
thanks, it works
