### ISSUE TITLE
Installer mkdir error confusing 

### ISSUE THREAD

**Issue by furicle** [schollz/croc#564]
I installed croc via ` curl https://getcroc.schollz.com | bash` on an Alma 8 linux box.

The installer had a permission denied message for bash completion, then said bash completion was installed.
Looking at what it actually did, it created a file call croc in bash_completion.d, and bash completion does work.

So now I'm confused - why did it try to create a folder, if it was going to create a file?

I quickly looked at the install script, but it was much more elaborate than I was expecting, so I don't have time to dig into it now, but wanted to note this issue before I forgot.

"Screenshot" below

`
==================================================
== Install prefix set to /usr/local/bin
== Created temp dir at /tmp/croc.VNgXRV
== Architecture detected as x86_64
== OS detected as Linux
== Downloaded croc archive into /tmp/croc.VNgXRV
== Downloaded croc checksums file into /tmp/croc.VNgXRV
== Checksum of /tmp/croc.VNgXRV/croc_9.6.2_Linux-64bit.tar.gz verified
== Extracted croc_9.6.2_Linux-64bit.tar.gz to /tmp/croc.VNgXRV/
== Install prefix already exists. No need to create it.
mkdir: cannot create directory ‘/etc/bash_completion.d/croc’: Permission denied
== Installed croc to /usr/local/bin/
== Installed autocompletions for bash
== Installation complete
`

**Comment by doc75** [comment]
Actually the error message is still raised, but in such case it is installing the completion information in a different location. We could improve the script to prevent the error message which is indeed "scary"
