### ISSUE TITLE
antivirus or firewall issue

### ISSUE THREAD

**Issue by plutoid** [schollz/croc#565]
**Is your feature request related to a problem? Please describe.**

sometime there are special rules I can only access with http/https protocol,  even I must trust private middle private cert via https, hope that croc could pretend communicate in http/https protocol, maybe this could help.
for example, if we have a webpage to download files this may help.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by schollz** [comment]
croc won't do https, sorry!
