### ISSUE TITLE
potential data races

### ISSUE THREAD

**Issue by 191830230** [schollz/croc#567]
Hello developer, I used a static data race detector to check this project and found suspicious data race defects. I have done preliminary filtering and categorized the defects, choosing only one from each category. However, due to my unfamiliarity with the overall architecture of the project, there may still be false positives after filtering. Below are the potential data race issues I found(not all stack traces are listed)
commit id:3c1d60
===================================================
Potential race condition:
 Access1:
        if err == nil {
           ^
croc/src/croc/croc.go:635:4 ->
croc/src/croc/croc.go:573:8

 Access2:
        err = <-errchan
        ^
croc/src/croc/croc.go:638:2
Other issues are similar to this one listed, focused on "func (c *Client) Send(filesInfo []FileInfo, emptyFoldersToTransfer []FileInfo, totalNumberFolders int) (err error):515"

**Comment by schollz** [comment]
Happy to accept a PR to fix.
