### ISSUE TITLE
The local network connection is interrupted for a short time when one device creates a new croc tunnel.

### ISSUE THREAD

**Issue by directentis1** [schollz/croc#571]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
Every time I try to create a croc connection to send a file, or a message, it seems to cause all other devices on my LAN to lose connection - unable to resolve the domain, or ping to IP addresses from the Internet (eg `1.1.1.1`) for about 10s - 15s.
 I installed croc latest version on my Ubuntu by quick install script file and installed from package manager `pkg` on my Termux Android.

 I've tried my devices, with Ubuntu computers and Android phones with Termux installed, the error keeps coming up when trying to send files or messages.
 While it still sometimes succeeds in sending, this disconnection problem makes me feel weird and want to find out the cause.

## To Reproduce
 1. Open Terminal (on Ubuntu, and Termux)
 2. Generate a random new croc connection
 3. Immediately after that, the devices in the local network lost Internet connection.  Even the connection between internal devices in the network is broken.  
 For example, I connect SSH from my computer to my Android phone via Termux, and as soon as I open `croc send -t "something"` the SSH connection is immediately closed.  (although not always, but almost often)
 4. About 10-15 seconds later, everything is back to normal.

## Expected behaviour
Everything went fine and there were no connection loss issues.

## Version
My Ubuntu 20.04: `croc version v9.6.4-1fce28e`
Termux shell on my Android phone: `croc version v9.6.4-1fce28e`

## Screenshots
![Peek 2023-05-16](https://github.com/schollz/croc/assets/128832114/7a3a0c56-bc94-4a6e-98a4-b62de9b8be1c)

**Comment by schollz** [comment]
Sorry I can't reproduce. is it reproducible on your end?

**Comment by directentis1** [comment]
It's weird that does not occurs for me in a while.

Maybe because some recent releases?
I'm still not sure why it's happened, but I'll keep watching if something continues to happen.
