### ISSUE TITLE
The installer fails for busybox's tar implementation

### ISSUE THREAD

**Issue by KizzyCode** [schollz/croc#573]
## Describe the bug
The installer fails within a busybox-environment e.g. as used by the Debian 11 installer:
```
tar: invalid tar magic
```

## To Reproduce

1. Boot the Debian 11 installer
2. Go to an unused terminal via `alt/option + →`
3. Start the croc-installer using `wget https://getcroc.schollz.com -O - | sh`

## Expected behaviour
The installer should be able to install `croc` 😊 

## Version
The latest version from https://getcroc.schollz.com

## Additional context
I think the problem is caused by busybox's `tar` being unable to automatically detect that the `tar`-file has been `gzip`-compressed. If you extract the file using `tar -zxf /file...` it successfully extracts a working `croc` binary. AFAIK the `-z`-flag should also be compatible with GNU `tar` so it's _probably_ an easy fix?

**Comment by schollz** [comment]
Can you make a Docker container that reproduces the behavior?

**Comment by KizzyCode** [comment]
Will take a look at it – a quick try with the basic Alpine image (uses Busybox too) could extract the tarball, so maybe it's version dependent.
