### ISSUE TITLE
Hash files during transfer

### ISSUE THREAD

**Issue by xentec** [schollz/croc#582]
Since I'm often send multiple huge files, which take some time to be hashed, I'd like croc to be able to start sending immediately and hash the files in chunks during transfer.

While I see implementing this feature myself, it would cause a protocol break, so I'd like to hear some opinions first.

**Comment by stefins** [comment]
It might be better to have this merged @schollz https://github.com/schollz/croc/pull/502

**Comment by emlazzarin** [comment]
This is my biggest issue with croc — would be great to rapidly accelerate hashing under certain conditions.

**Comment by schollz** [comment]
Try --hash imohash flag

**Comment by geerlingguy** [comment]
@schollz thanks so much for the suggestion! For a 919 GB file, the hashing time went from... a lot of time to just a second or so. Never heard of `imohash` until now.

**Comment by emlazzarin** [comment]
Why isn't `--hash imohash` the default? What are the drawbacks? Hashing just the beginning and end seems good enough for almost all usecases.

**Comment by geerlingguy** [comment]
For 99% of transfers it's not a big deal to run a longer hashing algorithm, and is probably like 0.00001% less likely to run into a hash collision or some weird issue just hashing start/end :D

**Comment by xentec** [comment]
...or croc could calculate the hash while sending the file and compare after completion.
- each file would be read once
- hash correctness would be intact (whole file hashed)
- you'll wait for the transfer only
