### ISSUE TITLE
Slow speed with multiple files

### ISSUE THREAD

**Issue by T3rm1** [schollz/croc#584]
## Describe the bug
File transmission is extremely slow if multiple files are sent, e.g. croc is used with a folder name as parameter.
I did a test with a folder containing 16 files with a total of 2.4 MB. The whole transmission took more than 10 seconds. Max upload speed of ISP is 40 Mbit/s.

How are multiple files handled in croc? Is there a significant overhead that could cause this slowdown? Single file transmission is fast.

**Comment by stefins** [comment]
Could you try with the `--zip` option introduced in #488 ?

**Comment by T3rm1** [comment]
That is super fast which is expected because it transfers only a single file.

**Comment by stefins** [comment]
Can you provide the steps to reproduce this bug @T3rm1 ?
