### ISSUE TITLE
Contributing public relays

### ISSUE THREAD

**Issue by complexcircuit** [schollz/croc#585]
I'm a long-time user of croc (Thank you!).  I have multiple VPS globally that are just sitting idle that I'd like to put into duty for croc relays.  I've setup relays myself no problem, but I'm wondering where these would be listed or advertised?  Or if there's some flag in the croc binary that notes the croc daemon is running as a relay and adds it to a list.  Similar to how syncthing automatically notes a relay.

Either way, great project and hope I can help

**Comment by schollz** [comment]
Hi @complexcircuit - I really appreciate your support! Having a public relay list could be a great asset. I'll have to think about implementation. I'll keep this issue open to discuss it. I like the idea of using this repo itself as a repository of the public domains (e.g. through a text file that can be PRed by anybody).

**Comment by stefins** [comment]
This is something that I was looking forward for a while!
We'll need to implement random relay selection from that particular file! Plus if a relay has a number of active connections it might be better to fallback to a secondary relay that doesn't have any active connections.

**Comment by emlazzarin** [comment]
What are the trust assumptions in using a public relay? Is it possible for a relay to MITM? If not, a public list would be a great way to decrease your hosting costs @schollz :)

**Comment by schollz** [comment]
I'd say go for it, it might be worth trying. However I'm not certain public servers other than mine will stick, I regularly get over 30TB of traffic and it costs a bit to host that much bandwidth.

**Comment by emlazzarin** [comment]
Is a true peer-to-peer model where relays only help to establish handshakes between peers (like in WebRTC) viable? Could fallback to a model where the relay is an intermediary in the case a p2p connection can’t be established.

**Comment by emlazzarin** [comment]
Resurfacing this issue with a question: what are the trust assumptions in using a relay? Is it possible for the relay to attack the sender or receiver in some manner? If not, it should be relatively straightforward to allow random selection of relays, or some other process.
