### ISSUE TITLE
iOS install failed :  "install: unrecognized option: C"

### ISSUE THREAD

**Issue by wanghz** [schollz/croc#588]
iPhone 7Plus iOS

## Describe the bug
<-- A clear and concise description of what the bug is. -->
= Install prefix set to /usr/local/bin
== Created temp dir at /tmp/croc.MelHfP
== Architecture detected as i686
== OS detected as Linux
== Downloaded croc archive into /tmp/croc.MelHfP
== Downloaded croc checksums file into /tmp/croc.MelHfP
== Checksum of /tmp/croc.MelHfP/croc_9.6.5_Linux-32bit.tar.gz verified
== Extracted croc_9.6.5_Linux-32bit.tar.gz to /tmp/croc.MelHfP/
== Install prefix already exists. No need to create it.
install: unrecognized option: C
BusyBox v1.33.1 () multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

        -c      Just copy (default)
        -d      Create directories
        -D      Create leading target directories
        -s      Strip symbol table
        -p      Preserve date
        -o USER Set ownership
        -g GRP  Set group ownership
        -m MODE Set permissions
        -t DIR  Install to DIR
== Failed to install croc

## To Reproduce
wget ... | bash

**Comment by schollz** [comment]
Use curl instead of wget
