### ISSUE TITLE
getcroc.schollz.com install error

### ISSUE THREAD

**Issue by tbussmann** [schollz/croc#590]
## Describe the bug
on macOS Monterey 12.6 the installation via `curl https://getcroc.schollz.com | bash` fails with `curl: (22) The requested URL returned error: 404`

## To Reproduce
1. Open Terminal
2. enter `curl https://getcroc.schollz.com | bash` 

## Expected behaviour
Successful installation of croc

## Version
9.6.5

## Additional context
The script is trying to download a file `https://github.com/schollz/croc/releases/download/v9.6.5/croc_9.6.5_macOS-unknown.tar.gz` due to `uname -m` (via https://github.com/schollz/croc/blob/cff8cddd1352152800248d956650884a6f1eba93/src/install/default.txt#L189) returning `arm64` whereas the script expects `aarch64` in https://github.com/schollz/croc/blob/cff8cddd1352152800248d956650884a6f1eba93/src/install/default.txt#L589 to convert that into `ARM64`

**Comment by ferebee** [comment]
I confirm this bug description. The bug is fixed in PR #587, please consider merging the PR.
