### ISSUE TITLE
File Chunk Algorithm Causes Files to be Needlessly Read Multiple Times on Sender Side

### ISSUE THREAD

**Issue by mgerstner** [schollz/croc#599]
It seems on the sender side each thread is reading the complete file, even if a chunk isn't even needed in the particular thread (croc.go:1650,croc.go:1778, croc.go:1787). This looks pretty inefficient, a big file sent via four relay ports will be completely read four times.

Also, on the receiver side the file chunk number communicated by the sender is blindly accepted (croc.go:1719). There are no sanity checks. It could lead to very large files being created and can confuse the receiver logic in other ways.

**Comment by schollz** [comment]
Thanks, this would be a great PR to have
