### ISSUE TITLE
Logo and name

### ISSUE THREAD

**Issue by schollz** [schollz/croc#6]
It can be anything

**Comment by csleong98** [comment]
Hi there, need some help on the logo?

**Comment by csleong98** [comment]
I can help with that

**Comment by csleong98** [comment]
ur program name is croc? and it does file to file transfer?

**Comment by schollz** [comment]
The name is temporary. Feel free to submit any logo you want and maybe a
name too! Yes it does peer to peer file transfer

**Comment by csleong98** [comment]
alright leave it to me then.

**Comment by csleong98** [comment]
u add a in progress label if u want

**Comment by schollz** [comment]
I don't know if this is useful (again the name can change) but here's something I sketched in a meeting
![croc](https://user-images.githubusercontent.com/6550035/31846736-0357bb50-b5cd-11e7-9037-96c3887fcd28.png)

**Comment by csleong98** [comment]
Its actually quite nice but i have an idea to name the program as Link (Legend of Zelda character) and a logo design from it

**Comment by schollz** [comment]
@csleong98 I think I'm going to go with the crocodile, but if you are doing hacktoberfest and want to make a PR still, you can add your name to the list of acknowledgements!

**Comment by csleong98** [comment]
alright
