### ISSUE TITLE
Well known "pingRoom" in Relays

### ISSUE THREAD

**Issue by mgerstner** [schollz/croc#601]
This is not a security issue, since I couldn't find anything harmful to do with it. Still this aspect allows a relay to operate in a confusing
state that should better not occur in the first place.

For processing "ping" messages the relay uses a well known "pingRoom". However, a malicious sender can specify "pingRoom" also as an actual room name for transmitting files. First I thought this could be suitable for causing the relay to crash, by tricking it into deleting the "pingRoom". The relay actually attempts to do this, but the "pingRoom" is a global variable and not stored in the dynamic room map, thus nothing bad happens.

This "pingRoom" should be excluded from being used for actual file transfers. On a side topic I would generally restrict the length of room name to a short string. And maybe introduce a special namespace like rooms starting with a "." that cannot be used for file transfers, to generalize this concept of special rooms.

**Comment by schollz** [comment]
Thanks - since this is a breaking change I'm adding it to the milestone for v10
