### ISSUE TITLE
 "--yes" does not apply to "Resume?"

### ISSUE THREAD

**Issue by irunonayran** [schollz/croc#603]
## Describe the bug
When restarting an interrupted download with `croc --yes`, I am still asked if I want to resume the download, with 'N' selected as default. 

## Expected behaviour
Should it not automatically continue? As a workaround, I use `yes`

## Version
v9.6.5

**Comment by schollz** [comment]
It does not automatically resume, because resuming is akin to overwriting, because its not determined whether the file is one that can be resumed. Use `--yes --overwrite` to resume automatically
