### ISSUE TITLE
Unable to do basic file-transfer 

### ISSUE THREAD

**Issue by gp1019** [schollz/croc#605]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
I've recently installed Croc on Fedora Linux and attempted to do a file-transfer and didn't work. 

`croc send [file(s) or folder(s)]`

It gave me the phrase code to put on another computer, I did just that and then:

`securing channel...2023/09/17 17:14:49 room not ready`

It gave me the error: "room not ready". I also noticed the package that I installed through `dnf` is several versions out of date (v9.5.2-1.fc37) compared to the recent version here. So I attempted to install the latest version available of 9.6.5_Linux-64bit.tar.gz. Have done the extraction, ran the executable on the terminal with the only prompt saying `Enter receive code`. Still didn't work.(Only KDE side and GNOME failed to show any kind of popup.)

I've done the same process on both computers running the same version of Croc (old and new) and updated OSes, though one runs GNOME and the other KDE. I've had no success on GNOME in trying to get it to run on the latest version. 

So, the command didn't get installed and there doesn't seem to be a way to use it in any way.

## To Reproduce
<-- 1. Go to '[terminal of choice]'
2. run command `croc send [file or folder]`
3. Recieve `code-phrase`
4. Enter the code phrase on the other computer
5. Error: `securing channel...2023/09/17 17:14:49 room not ready`

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->
1. Have the command installed and ready for use.
2. Reliably send and receive the file attempting to transfer over.

## Version
<-- Check "croc -v" and report it -->
Old: 9.5.2-4a8c19b 
New: 9.6.5_Linux-64bit.tar.gz

**Comment by schollz** [comment]
Try using `-debug` and sharing the output. As it stands, I can't reproduce your issue.

**Comment by gp1019** [comment]
Like I said, GNOME won't even open the program or have it installed as a command line utility, therefore no debug for the command. (File trying to move from GNOME to KDE) As for KDE, it's only limited to just receiving the code. I literally do not have the command installed to show a debug log of it. Unless you walk me through to installing it and have it setup properly, there isn't much for either of us to go off of.

**Comment by schollz** [comment]
Follow the README to install, and then run with debug flag to find the issue

**Comment by gp1019** [comment]
Never mind, I got it to work. Still though, any way you could perhaps push an updated version of Croc to the dnf package manager? Or is it now going to be through tar.gz files.
