### ISSUE TITLE
How secure is croc? (resistant to brute force?)

### ISSUE THREAD

**Issue by alirezaalavi87** [schollz/croc#614]
Hi, this is not a but, I just had a question.

 I just came across this project from hackernews and it seems awesome.

The only concern that I have, which I think might be the case for many others, is this:
If when I send the file, I generate a code and on ANY other computer you can receive the file just by putting in the three word code, isn't it possible that a malicious actor just sits there and bruteforces files by putting in thousand or millions of codes?

**Comment by schollz** [comment]
> isn't it possible that a malicious actor just sits there and bruteforces files by putting in thousand or millions of codes?

Short answer: no. The codes are only accepted when a sender starts a transfer. And the code is only used once, when beginning the transfer. So an attacker would have to constantly spam the relay server with millions of attempts to "catch" clients beginning to send files. Spam like that is easily detected by the server and blocked. So its near impossible to send the right code at the right time to catch someone's message.

**Comment by alirezaalavi87** [comment]
Ok I understand now. thanks. I think it would be a good idea to add this to the readme or FAQ.

**Comment by schollz** [comment]
Would accept a PR!
