### ISSUE TITLE
Defining ports is a bit cumbersome

### ISSUE THREAD

**Issue by qk-santi** [schollz/croc#617]
**Is your feature request related to a problem? Please describe.**
Defining the number of ports for transfer connections is a bit cumbersome, especially if you want to create quite a few ones
`croc send --ports 9009,9010,9011,9012,9013,9014,9015,9016,9017 my_file.gzip`

**Describe the solution you'd like**
Define base port (if different than default) + number of parallel connections
`croc send --port 9009 --transfers 8 my_file.gzip`
`croc send --transfers 8 my_file.gzip`

**Describe alternatives you've considered**
[Diff commit here](https://github.com/schollz/croc/commit/84f6a8271e14ba33b5cabc6d3ff0fbe7f3207de2)

**Comment by navaneeth-dev** [comment]
I agree

**Comment by schollz** [comment]
would accept pr
