### ISSUE TITLE
debian12, croc via curl and bash from getcroc schollz, single file transfer completes, but sets no rights at all

### ISSUE THREAD

**Issue by subscribernamegoeshere** [schollz/croc#618]
on the reciever machine the downloaded fetched file has zero access rights set al only dashes shown in ls ----------

no r w x at all not for all not for group not for users nothing for anybody.

the transfer finished with the proper file size but the croc process doesnt return to the console command line terminal. it needs to be terminated with ctrl c  and then there is an error such as; could not create filename.... filename permission denied.

the actual transferred file is on the disk though and correct file size and arrived properly (checked shasum.....) but as stated before no access rights for anyone at all.

the user running the croc binary on this debian12 can not read access anything the recieved file. very odd. what happen?!

## Describe the bug
<-- A clear and concise description of what the bug is. -->

## To Reproduce
<-- 1. Go to '...'
4. See error -->

1.
2.
3.
4. 

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->
hey put the file into the local receiving directory with the normal user rights. or is this some security feature i have overlooked?

## Version
<-- Check "croc -v" and report it -->
installed croc just today on the  receiving debian12 machine,  croc v9.6.5-8ab65d0

## Additional context
<-- Add any other context about the problem here. -->

**Comment by stephenhuh** [comment]
can confirm have been seeing this on ubuntu:focal
croc installed with 

```
 curl -L -o /tmp/croc_9.1.1_Linux-64bit.deb https://github.com/schollz/croc/releases/download/v9.1.1/croc_9.1.1_Linux-64bit.deb
dpkg -i /tmp/croc_9.1.1_Linux-64bit.deb
```

**Comment by schollz** [comment]
would accept pr

**Comment by asukaminato0721** [comment]
can't reproduce on

```
croc version v10.0.12
```

```
cat foo.sh 
echo hi

ls -al foo.sh 
-rwxr-xr-x 1 w w 8 Sep  3 17:02 foo.sh*
```

after send, still can be executed.

```
-rwxr-xr-x  1 w w       8 Sep  3 17:03 foo.sh*
```
