### ISSUE TITLE
--remember doesn't

### ISSUE THREAD

**Issue by b3taman** [schollz/croc#622]
## Describe the bug
I set up my own proxy and discovered that `--remember` only creates a zero-byte `~/.config/croc/internal-dns` file.

I ran ` find ~ -xdev -type f -exec stat -c "%y %n" {} + | sort -r | head -10 | sort -r` to give me the 10 newest files after running `croc` as above, and the empty `internal-dns` is all I found.

## To Reproduce
1. Run `croc --remember --pass ./super-secret-password relay --ports 11111,11112,11113,11114,11115`
2. Connect and transfer files.
3. Stop the relay with `Ctrl+C`.
4. Discover that nothing is remembered and that `~/.config/croc/` contains only `internal-dns`, which is empty.

## Expected behaviour
Some kind of config file which is read and acted upon.

## Version
croc version v9.6.5-8ab65d0

## Additional context
1. Running without `--remember` doesn't create the `internal-dns` file.
3. Separately I tried `croc config` as per https://schollz.com/software/croc/, but that simply returned with `securing channel...2023/10/13 17:27:54 room not ready`.

**Comment by schollz** [comment]
happy to accept a pr for this

**Comment by b3taman** [comment]
Thank you so much!
