### ISSUE TITLE
got error receiving: EOF

### ISSUE THREAD

**Issue by doveppp** [schollz/croc#643]
## Describe the bug
I sent a very large file (12GB) from Ubuntu 22 to Windows 10, but every time it reaches 66% completion, an EOF error occurs. I have tested it three times already.

## To Reproduce
<-- 1. Go to '...'
4. See error -->

1.
2.
3.
4. 

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->

## Version
croc version v9.6.6-1e57206

## Additional context
**windows client log：**

Accept 'g2044_blm.bson.gz' (10.9 GB)? (Y/n)

Receiving (<-103.67.52.19:59834)
[debug] 17:40:13 croc.go:1201: [{g2044_blm.bson.gz ./ /data/spider [94 5 169 132 175 192 87 109] 11745231633 2024-01-17 09:14:22.471864029 +0000 UTC false false  -rw-r--r-- false false}]
[debug] 17:40:13 croc.go:1621: checking {Name:g2044_blm.bson.gz FolderRemote:./ FolderSource:/data/spider Hash:[94 5 169 132 175 192 87 109] Size:11745231633 ModTime:2024-01-17 09:14:22.471864029 +0000 UTC IsCompressed:false IsEncrypted:false Symlink: Mode:-rw-r--r-- TempFile:false IsIgnored:false}
[debug] 17:40:13 croc.go:1638: g2044_blm.bson.gz  5e05a984afc0576d <nil>
[debug] 17:40:13 croc.go:1640: hashed g2044_blm.bson.gz to  using xxhash
[debug] 17:40:13 croc.go:1641: hashes are not equal  != 5e05a984afc0576d
[debug] 17:40:13 croc.go:1450: working on file 0
[debug] 17:40:13 croc.go:1534: converting to chunk range
g2044_blm.bson.gz   0% |                    | ( 0 B/12 GB) [0s:0s][debug]       17:40:13 croc.go:1542: sending recipient ready with 0 chunks
[debug] 17:40:13 message.go:58: writing recipientready message (encrypted)
g2044_blm.bson.gz  66% |█████████████       | (7.8/12 GB, 732 kB/s) [2h59m44s:1h28m42s][debug]  20:40:01 comm.go:151: initial read error: EOF
[debug] 20:40:01 croc.go:992: got error receiving: EOF
2024/01/17 20:40:01 EOF

**Comment by schollz** [comment]
have you tried more than once? how reproducible is it? I can't reproduce on my end.

**Comment by doveppp** [comment]
I've tried multiple times and it still doesn't work. I'm sorry, the file is just too big to reproduce for you. I'll open this issue next time I have this problem.

**Comment by schollz** [comment]
just to be clear, the file size is not too big. something else is going on.
