### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [schollz/croc#650]
Dear @schollz, croc 9.6.8 does not work on Windows 7 anymore, it crashes because you've used @golang 1.21 to compile. Those traitors cut off users like me as if we don't exist. I can't imagine C++ developers doing that. Whatever the case, consider doing your best to provide your tool to a wider audience.

``` console
$ croc.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47161a
rax     0x0
rbx     0xbb5018
rcx     0xc3b0c8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x28fa2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0xbb4460
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by schollz** [comment]
thanks for letting me know. I can make a special build in the GitHub
actions. 32bit or 64bit or both?

**Comment by sergeevabc** [comment]
@schollz, it's so great that you stay true to the mission of keeping file transfers secure and hear other people's pain. Windows x64 build would fine. Thank you in advance.

**Comment by schollz** [comment]
@sergeevabc try https://github.com/schollz/croc/releases/download/v9.6.9/croc_v9.6.9_Windows7-64bit.zip

**Comment by sergeevabc** [comment]
It works as expected, @schollz. Bravo!

**Comment by sergeevabc** [comment]
Since @schollz no longer builds for Windows 7, I had to learn how to do it myself.
See https://github.com/schollz/croc/issues/1023#issuecomment-3659890154
