### ISSUE TITLE
 croc_v9.6.8 ; no more .deb for Ubuntu 20.04 ?

### ISSUE THREAD

**Issue by ludetie** [schollz/croc#654]
## Describe the bug
When the last version of croc (v9.6.8) is launched in Ubuntu 20.04, it says :

~/Apps/sources/croc_v9.6.8_Linux-64bit$ ./croc --help
./croc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./croc)
./croc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./croc)

Have you decided to stop doing .deb for Ubuntu 20.04 ?

## To Reproduce
<-- 1. Go to '...'
4. See error -->

1.
2.
3.
4. 

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->

## Version
<-- Check "croc -v" and report it -->

## Additional context
<-- Add any other context about the problem here. -->

**Comment by schollz** [comment]
please edit this release action to get what you need: https://github.com/schollz/croc/blob/main/.github/workflows/release.yml

I migrated away from goreleaser and I'm not sure who needs what, so if you need something in particular, put it there and I'll generate a release

**Comment by ludetie** [comment]
Hello, Sorry, I do not know what to do in this release.yml, I just wanted a .deb, i am an little user and wanted to update croc.

**Comment by schollz** [comment]
okay, hopefully someone else finds this and can help you

**Comment by ludetie** [comment]
Hello,
the latest version was succesfully created using what you wrote on the homepage:
go install github.com/schollz/croc/v9@latest

Many sites talk about installing croc by saying to download the latest .deb; it was easier to install it.

This software is really great, thank you.

**Comment by TaquitoSlayer** [comment]
GLIBC is pegged to whatever Ubuntu release you have. You'd have to go in and build croc yourself every time now and edit `  build:
    runs-on: ubuntu-latest` to ubuntu-20.04. Sad.

**Comment by schollz** [comment]
if you want you can make a pr to the GitHub actions to peg a different Ubuntu

**Comment by ludetie** [comment]
Hello,
You build with go 1.21 the last version 9.6.10, no more GLIBC error, no needs to do the go install command.
Thank you.
