### ISSUE TITLE
No CLI output on Windows with v9.6.12

### ISSUE THREAD

**Issue by tech189** [schollz/croc#668]
## Describe the bug

When running croc v9.6.12, no output appears. Neither for 32-bit or 64-bit versions.

Still no output in v9.6.13.

## To Reproduce

1. Install croc v9.6.12
2. Run `croc --version`
3. See no output

## Expected behaviour

with croc v9.6.11:
```
❯ croc --version
croc version v9.6.11
```
with croc  v9.6.12:
```
❯ croc --version

```

## Version

 v9.6.12

## Additional context

No issues running croc v9.6.12 on macOS and WSL Ubuntu 20.04.5 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)

**Comment by subscribernamegoeshere** [comment]
i have this issue as well. just tried the 9.6.12 version, all windows builds (x86/x84) even that of the win7 special builds (i guess cause of go layer etc...) all four versions on my win10 x64 system, executed from simple dosbox/cmd are simply exiting terminating. doesnt seem like a crash but simple exit or some sort of fail.

no console textual output and no functioning.
reverted back to x64 build of version 9.6.11

and croc.exe -v

immediately displays the version string and functions all normal.

**Comment by Tragen** [comment]
9.6.13 still has the same bug. It's not working.
Last working version for me is 9.6.11

**Comment by aofarrel** [comment]
Having the same issue, but with a twist. Interestingly, if the Windows machine is receiving from a non-Windows machine, the file will transfer to the Windows machine successfully. So it works a little bit...?

**Comment by Mathomstore** [comment]
Confirming 9.6.13 still fails silently on any version of Windows. 
6.9.11 is last working version.
