### ISSUE TITLE
Winget Release Action is broken

### ISSUE THREAD

**Issue by jathek** [schollz/croc#669]
## Describe the bug

The action to release to winget [seems broken](https://github.com/schollz/croc/actions/workflows/winget.yml). It hasn't successfully run for some time (if ever?). The current version on winget is croc 9.6.6.

## To Reproduce

1. run `winget search croc`
2. version is 9.6.6, expect 9.6.12

## Expected behaviour

Winget should have updated croc version.

## Version

croc version v9.6.6-1e57206

**Comment by jathek** [comment]
The current release (9.6.15) is on winget, but I assume it was added manually, because the winget action's logs still show authentication errors.

**Comment by schollz** [comment]
I don't maintain winget, please make a PR to fix it

**Comment by jathek** [comment]
To be clear, the problem is not with winget, it's with the release action on this repo. You don't maintain that? The error logs seem to indicate a 401 error because of bad credentials. According to https://github.com/vedantmgoyal9/winget-releaser/issues/240, it seems like your GitHub PAT needs to be regenerated. I don't think anyone can do that via a PR.

**Comment by schollz** [comment]
do you have instructions for doing that?

**Comment by jathek** [comment]
[According to the readme](https://github.com/vedantmgoyal9/winget-releaser#getting-started-) of winget-releaser, you need to create a classic PAT. GitHub's instructions for that are [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic). Afterwards, I assume you will need to copy it into the secrets for the repo. Instructions for that are [here](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization).

**Comment by schollz** [comment]
thanks.

winget-action is now working: https://github.com/schollz/croc/actions/runs/9236640238

**Comment by schollz** [comment]
pull is already installed on my winget-pkgs fork btw. 

I'll close this issue because winge release action is no longer broken, but please feel free to make another issue if another thing in winget is not working
