### ISSUE TITLE
prevent sleeping while transferring

### ISSUE THREAD

**Issue by aqtsalt** [schollz/croc#690]
**Is your feature request related to a problem? Please describe.**
if the computer sleeps while transferring, it is stopped and also does not resume after waking up

**Describe the solution you'd like**
automatically prevent sleeping while transfer in progress

**Describe alternatives you've considered**
have to manually go to settings to disable sleeping every time which is annoying

**Additional context**

**Comment by schollz** [comment]
do this from your OS, not in scope for a command-line utility
