### ISSUE TITLE
Flag to limit bandwidth for sender

### ISSUE THREAD

**Issue by schollz** [schollz/croc#7]
This is very simple. 

1. Add a flag
2. Add a time.Sleep() after each send, which calculates based on the bandwidth and the BUFFER_SIZE

Ask me if you have questions!

**Comment by heymatthew** [comment]
Mind if I take this one?

**Comment by schollz** [comment]
Go for it! Let me know if you have any questions

**Comment by heymatthew** [comment]
Took me a while because I had to setup a few firewalls to check this :)

Does this look like the kind of thing you were after?

**Comment by schollz** [comment]
Looks great!
