### ISSUE TITLE
winget integration now requires Microsoft CLA

### ISSUE THREAD

**Issue by schollz** [schollz/croc#714]
hi croc community!

winget integration was added back in 2023 (https://github.com/schollz/croc/issues/498), as requested by @CodeCubeNeo since it was becoming the official way to get things installed. thanks for bringing the issue and helping with it, especially @sitiom and @jathek. 

I think winget integration is working again, *except* that it looks like there is a new terms of integration requiring me to agree to the microsoft CLA (https://github.com/microsoft/winget-pkgs/pull/155177#issuecomment-2131384583).

reading through the CLA I found that I disagree with this section (screenshot from 05/25/24): 

![image](https://github.com/schollz/croc/assets/6550035/c6baca41-cff5-4689-800d-55314f8ef7b0)

is there a way to have winget support without agreeing to Microsoft's CLA?

cc-ing winget other interested parties like @flleeppyy @bitraid

**Comment by jathek** [comment]
Does Submission in this case refer to the code of the PR, not the code of croc?

**Comment by schollz** [comment]
@jathek good question.

as I understand the agreement, I read it as code of croc.

but honestly, an ambiguous contract is definitely not one I can agree to.

**Comment by jathek** [comment]
Found a discussion on winget-pkgs that seems to confirm: https://github.com/microsoft/winget-pkgs/discussions/14084#discussioncomment-794372

**Comment by schollz** [comment]
Thanks @jathek.

I like that they are responsive to the discussion around the CLA, that makes me feel better.

That question revolves around the `Originality of Work` which is also a good question but slightly different in my case. 

I made a discussion in their repository, I'd appreciate if we can carry over the discussion there to get a more specific answer: https://github.com/microsoft/winget-pkgs/discussions/155182
