### ISSUE TITLE
curl command no longer works

### ISSUE THREAD

**Issue by MsFloofie** [schollz/croc#715]
## Describe the bug
Using `curl https://getcroc.schollz.com | bash` does not work due to the release version being 10.04 and not 10.0.4, which the curl command expects.

## To Reproduce

1. Run `curl https://getcroc.schollz.com | bash` in command line
2. Error out with "The requested URL returned error: 404"

## Expected behaviour

croc installs properly

## Version
10.0.4/10.04

**Comment by schollz** [comment]
what's your OS and Arch?

**Comment by MsFloofie** [comment]
Sorry, I forgot to add that in.
Operating system is Pop!_OS 22.04 LTS and the arch is x86_64

**Comment by schollz** [comment]
ah found it! made a mistake tagging it, this should work: https://github.com/schollz/croc/releases/tag/v10.0.4

**Comment by MsFloofie** [comment]
Hah, I was just figuring out how to reword everything since I didn't elaborate at all. Glad you found it though!
