### ISSUE TITLE
watch & sync

### ISSUE THREAD

**Issue by steom** [schollz/croc#719]
How do you see implementing a sort of "simple dropbox" to avoid having to always write command lines for every single transfer?

sender: croc --relay "myrelay.example.com:9009" --code [code-phrase] watch [folder, folders]

multiple receiver: croc --out [path] --relay "myrelay.example.com:9009" --code [code-phrase] sync

the croc processes always remain active and listening, watching for new files to send/receive

**Comment by schollz** [comment]
would accept pr

**Comment by schollz** [comment]
> if so, I would fork 

that's great! go for it, looking forward to the pr

**Comment by schollz** [comment]
> you're the dev

?

**Comment by schollz** [comment]
@steom what do you mean "you're the dev"?
