### ISSUE TITLE
--yes option does not work as expected

### ISSUE THREAD

**Issue by raimocom** [schollz/croc#729]
## Describe the bug

The  --yes option does not behave as expexted. Itś defined as "automatically agree to all prompts". When i resume a transfer i still have to manually press **Y** to continue.

## Version
10.0.7

**Comment by schollz** [comment]
use `croc --yes --overwrite <CODE>` to automatically agree *AND* overwrite your data (where "overwrite" is "resume", they are indistinguishable from the software perspective, its up to the user to decide)
