### ISSUE TITLE
Invalid filename detected

### ISSUE THREAD

**Issue by ErwinLubbers** [schollz/croc#744]
I'm trying to send a lot of files from one server to another:

Sending 164028 files and 18724 folders (21.1 GB)

and croc has no problem with it, but as soon as I start croc on the receiving server it says:

securing channel...2024/06/26 13:10:54 invalid filename detected: '_index_slash_ssl.html'

and does not send any file. On both sides croc version v10.0.8 is used.

**Comment by schollz** [comment]
Is it possible that the filename has some unprintable characters?

**Comment by ErwinLubbers** [comment]
The only "strange" thing about the filename is that is starts with a underscore.

**Comment by ErwinLubbers** [comment]
I did change:

return true, fmt.Errorf("invalid filename detected: '%s'", fi.Name)

to:

return true, fmt.Errorf("invalid filename detected: '%s'", path.Join(c.FilesToTransfer[i].FolderRemote, fi.Name))

because there are 10.326 files that need to be transferred with the name _index_slash_ssl.html. And then it seems that maybe a minus sign at the end of a path is invalid:

www.kringen.nl/wp-content/cache/page_enhanced/www.kringen.nl/jan-valkier-ontvangt-/_index_slash_ssl.html

**Comment by schollz** [comment]
That path as it is pasted in Github is not a problem for the file name....something is still missing.

I did something similar which will give more information still: https://github.com/schollz/croc/commit/3e804a4a090120c19c800ea5e568d0c339724cd9

If you can build from source and try this version of croc, I would be greatly appreciative. This version should print out exactly the character that is a problem.

**Comment by ErwinLubbers** [comment]
That showed the wrong character (U+65279). Thanks for your help

**Comment by schollz** [comment]
Cool thanks!!
