### ISSUE TITLE
-bash: croc: command not found

### ISSUE THREAD

**Issue by youngda** [schollz/croc#75]
-bash: croc: command not found

**Comment by youngda** [comment]
centos and ubuntu

**Comment by youngda** [comment]
download croc_2.2.0_linux_64bit.tar.gz
tar -zxvf croc_2.2.0_linux_64bit.tar.gz
croc -send some-file-or-folder
-bash: croc: command not found

**Comment by schollz** [comment]
Your missing a step

```
tar -zxvf croc_2.2.0_linux_64bit.tar.gz
sudo mv croc /usr/local/bin/
```

You need to add it to your PATH, basically.

**Comment by youngda** [comment]
Thank you @schollz  It's working now.
