### ISSUE TITLE
Compile 32-bit ARM build with lesser FPU requirements for compatibility with old Raspberry Pi units

### ISSUE THREAD

**Issue by wdormann** [schollz/croc#752]
## Describe the bug

Running 32-bit ARM croc on a Raspberry Pi Zero (or 1, presumably) will result in:
`illegal instruction`

The illegal instruction is `vmov.f32`, which a RPi Zero won't grok.  If the ARM32 croc were built with `-mfpu=vfp` (or whatever the go equivalent is, assuming there is one?), then I believe it would work on such a device.

## To Reproduce

1. Run croc on a Raspberry Pi Zero

## Expected behaviour

It should work.

## Version
croc version v10.0.9

**Comment by schollz** [comment]
@wdormann can you try building from source to see if this fixes it:

```
GOARM=5 go build
./croc
```

**Comment by wdormann** [comment]
Sorry about the delay, as the machine I have truly is anemic so it took a while to build.  (which is why I was going for the pre-built binaries on github)
croc built with the above does indeed work fine on my Pi Zero machine.

**Comment by schollz** [comment]
@wdormann okay I added it to the releases, a release should populate here in a little bit: https://github.com/schollz/croc/releases/tag/v10.0.10

(look for ARMv5)

it would be great to add this to the [install script](https://github.com/schollz/croc/blob/main/src/install/default.txt) but I'm not sure how to detect the pico in this case (and I don't have one to test). that's a separate issue though, if you'd like to create it.
