### ISSUE TITLE
[Question]: Is it possible to show the connection mechanism?

### ISSUE THREAD

**Issue by rjshrjndrn** [schollz/croc#755]
Hi, First of all, thank you for this amazing tool. It saves a lot of hazzle, especially across multiple devices. 

I'd read that for the file send: default behavior is p2p fall back to transfer via server. 
Is it possible to see how the transfer will happen, or happened. For my work related things, I'd like to transfer p2p, else the transfer overhead is bearable.

Thank you :)

**Comment by schollz** [comment]
when sending it says

`Sending (->IPADDRESS)`

when receiving it says

`Receiving (<-IPADDRESS)`


where the `IPADDRESS` can tell you whether it is local or using public IP addresses (not-local).

**Comment by rjshrjndrn** [comment]
Thank you for the quick response )
