### ISSUE TITLE
🌏 How to solve the problem of failed installation of Croc?

### ISSUE THREAD

**Issue by l-g-t** [schollz/croc#765]
== Install prefix set to /usr/local/bin
== Created temp dir at /tmp/croc.gmiAob
== Architecture detected as i686
== OS detected as Linux
https://github.com/schollz/croc/releases/download/v10.0.10/croc_v10.0.10_Linux-32bit.tar.gz /tmp/croc.gmiAob croc_v10.0.10_Linux-32bit.tar.gz
== Downloaded croc archive into /tmp/croc.gmiAob
== Downloaded croc checksums file into /tmp/croc.gmiAob
== Checksum of /tmp/croc.gmiAob/croc_v10.0.10_Linux-32bit.tar.gz verified
== Extracted croc_v10.0.10_Linux-32bit.tar.gz to /tmp/croc.gmiAob/
== Install prefix already exists. No need to create it.
install: unrecognized option: C   🌈
BusyBox v1.36.1 (2024-06-10 07:11:47 UTC) multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

        -c      Just copy (default)
        -d      Create directories
        -D      Create leading target directories
        -s      Strip symbol table
        -p      Preserve date
        -o USER Set ownership
        -g GRP  Set group ownership
        -m MODE Set permissions
        -t DIR  Install to DIR
== Failed to install croc
😊🌏 How to solve the problem of failed installation of Croc?

**Comment by schollz** [comment]
try again, new commit added for BusyBox: 677f44da6d19c3069f871ebbcfef227295b21bf4

**Comment by barsikus007** [comment]
It still fails inside docker containers with alpine
(I tried to launch installer inside of https://github.com/nicolaka/netshoot to send pcap file)
