### ISSUE TITLE
Bash installer 404 error (unknown Linux file?)

### ISSUE THREAD

**Issue by SunsetSamu** [schollz/croc#769]
I'm trying to install croc with the  curl command installer in my Linux distribution based on ubuntu, in termux, and seems to work fine until this...

```
== Created temp dir at /tmp/croc.ouXjZ1
== Architecture detected as armv8l
== OS detected as Linux
https://github.com/schollz/croc/releases/download/v10.0.10/croc_v10.0.10_Linux-unknown.tar.gz /tmp/croc.ouXjZ1 croc_v10.0.10_Linux-unknown.tar.gz
curl: (22) The requested URL returned error: 404
== Return code of download tool returned an unexpected value of 22
```
I've seeing the repo searching that "Linux-unknown" file but there are no files named like these.

Is there some command-line method to install it, I don't know how to install it manually in my specific case...

Thanks for any response and sorry for my English skills

**Comment by schollz** [comment]
@SunsetSamu should be fixed now, can you try again?

**Comment by SunsetSamu** [comment]
Working and installed ! Thank you
