### ISSUE TITLE
croc.exe closes too fast to show any errors

### ISSUE THREAD

**Issue by mr-september** [schollz/croc#772]
Windows 11. If I open cmd myself and `cd` to the `croc.exe` folder, if something goes wrong, the error message/log remains on the screen, e.g. `room (secure channel) not ready, maybe peer disconnected`.

However, if I just run `croc.exe` and enter the code when prompted, the cmd window just seems to do nothing and disappears. 

I think a significant number of potential users would directly run the `.exe`, and having it not work without any error messages, etc, would be frustrating and just write off the whole software.

Would be good if a delay/prompt for user input is included for errors when the `.exe` is directly ran, so they can Google or send the error message/code to the sender or whatever.

**Comment by schollz** [comment]
can you run croc --debug send FILE and send me the results to zack.scholl@gmail.com
