### ISSUE TITLE
room not ready

### ISSUE THREAD

**Issue by UnrelatedWorks** [schollz/croc#776]
When entering the room code, the recipient recieves the following message: 

croc 0507-polka-kermit-temple
securing channel...2024/08/07 00:38:52 room not ready

I have tried this with multiple senders and recipients, are the public servers down? 
Does anyone have private servers that can be used as a sanity check?

**Comment by schollz** [comment]
please report `croc --version`

**Comment by UnrelatedWorks** [comment]
The sender is running v10.0.11



  On Wed, 7 Aug 2024 at 1:07 AM Zack wrote:
  
please report croc --version

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/schollz/croc/issues/776#issuecomment-2272307592",
"url": "https://github.com/schollz/croc/issues/776#issuecomment-2272307592",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by schollz** [comment]
please run `croc --debug send <file>` and share the output

**Comment by UnrelatedWorks** [comment]
### This is the server (with the last 3 lines looping):
Sending 'index.html' (25.0 kB)   
Code is: 7768-music-orchid-repair
On the other computer run

croc 7768-music-orchid-repair
[debug]	16:40:51 croc.go:683: host: '2a01:4ff:1f0:c10b::1', port: '9009'
[debug]	16:40:51 croc.go:689: got host '2a01:4ff:1f0:c10b::1' and port '9009'
[debug]	16:40:51 croc.go:691: trying connection to [2a01:4ff:1f0:c10b::1]:9009
[debug]	16:40:51 comm.go:78: dialing to [2a01:4ff:1f0:c10b::1]:9009 with timelimit 100ms
[debug]	16:40:51 tcp.go:79: starting with password 'pass123'
[info]	2024/08/07 16:40:51 starting TCP server on 0.0.0.0:9015
[debug]	16:40:51 tcp.go:79: starting with password 'pass123'
[info]	2024/08/07 16:40:51 starting TCP server on 0.0.0.0:9014
[debug]	16:40:51 tcp.go:79: starting with password 'pass123'
[info]	2024/08/07 16:40:51 starting TCP server on 0.0.0.0:9018
[debug]	16:40:51 tcp.go:79: starting with password 'pass123'
[info]	2024/08/07 16:40:51 starting TCP server on 0.0.0.0:9016
[debug]	16:40:51 tcp.go:79: starting with password 'pass123'
[info]	2024/08/07 16:40:51 starting TCP server on 0.0.0.0:9017
[debug]	16:40:51 comm.go:83: comm.NewConnection failed: dial tcp [2a01:4ff:1f0:c10b::1]:9009: i/o timeout
[debug]	16:40:51 tcp.go:483: comm.NewConnection failed: dial tcp [2a01:4ff:1f0:c10b::1]:9009: i/o timeout
[debug]	16:40:51 croc.go:697: could not establish '[2a01:4ff:1f0:c10b::1]:9009'
[debug]	16:40:51 croc.go:683: host: '5.78.91.237', port: '9009'
[debug]	16:40:51 croc.go:689: got host '5.78.91.237' and port '9009'
[debug]	16:40:51 croc.go:691: trying connection to 5.78.91.237:9009
[debug]	16:40:51 comm.go:78: dialing to 5.78.91.237:9009 with timelimit 5s
[debug]	16:40:51 comm.go:87: connected to '5.78.91.237:9009'
[debug]	16:40:52 tcp.go:513: strong key: 70ed9e0af40e55f8c27c35518d75ed525fa34dc7fc6956ff10f08d09595ed3bb
[debug]	16:40:52 tcp.go:527: sending password
[debug]	16:40:52 tcp.go:538: waiting for first ok
[debug]	16:40:52 croc.go:602: establishing connection
[debug]	16:40:52 comm.go:78: dialing to 127.0.0.1:9014 with timelimit 30s
[debug]	16:40:52 tcp.go:129: client 127.0.0.1:35280 connected
[debug]	16:40:52 comm.go:87: connected to '127.0.0.1:9014'
[debug]	16:40:52 tcp.go:225: Abytes: {"Role":0,"Uᵤ":793136080485469241208656611513609866400481671853,"Uᵥ":18458907634222644275952014841865282643645472623913459400556233196838128612339,"Vᵤ":1086685267857089638167386722555472967068468061489,"Vᵥ":19593504966619549205903364028255899745298716108914514072669075231742699650911,"Xᵤ":14634370510326070462037250427785434870845856345627335478422456057193278652276,"Xᵥ":17918100420103926802502647334908311336060856719096467453456580699201989179910,"Yᵤ":null,"Yᵥ":null,"P":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug]	16:40:52 tcp.go:244: strongkey: 0d8d2f040111e424e9e98881a71558d884ef471f5ca488bce18f35b90b1ec374
[debug]	16:40:52 tcp.go:513: strong key: 0d8d2f040111e424e9e98881a71558d884ef471f5ca488bce18f35b90b1ec374
[debug]	16:40:52 tcp.go:527: sending password
[debug]	16:40:52 tcp.go:538: waiting for first ok
[debug]	16:40:52 tcp.go:256: waiting for password
[debug]	16:40:52 tcp.go:279: sending '9015,9016,9017,9018'
[debug]	16:40:52 tcp.go:290: waiting for answer
[debug]	16:40:52 tcp.go:556: sending room; 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67
[debug]	16:40:52 tcp.go:321: room 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67 has 1
[debug]	16:40:52 tcp.go:133: room: 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67
[debug]	16:40:52 tcp.go:134: err: <nil>
[debug]	16:40:52 tcp.go:147: checking connection of room 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67 for &{connection:0xc00008c078}
[debug]	16:40:52 tcp.go:155: room: {first:0xc00028c370 second:<nil> opened:{wall:13953566463841273093 ext:12998788320 loc:0xbf0740} full:false}
[debug]	16:40:52 tcp.go:567: waiting for room confirmation
[debug]	16:40:52 tcp.go:583: all set
[debug]	16:40:52 croc.go:605: banner: 9015,9016,9017,9018
[debug]	16:40:52 croc.go:612: local connection established: &{connection:0xc00022c000}
[debug]	16:40:52 croc.go:618: got ping
[debug]	16:40:52 tcp.go:556: sending room; 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67
[debug]	16:40:52 tcp.go:567: waiting for room confirmation
[debug]	16:40:52 tcp.go:583: all set
[debug]	16:40:52 croc.go:708: banner: 9010,9011,9012,9013,9014,9015,9016,9017
[debug]	16:40:52 croc.go:709: connection established: &{connection:0xc00008c6d0}
[debug]	16:40:53 tcp.go:147: checking connection of room 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67 for &{connection:0xc00008c078}
[debug]	16:40:53 tcp.go:155: room: {first:0xc00028c370 second:<nil> opened:{wall:13953566463841273093 ext:12998788320 loc:0xbf0740} full:false}
[debug]	16:40:53 croc.go:618: got ping
[debug]	16:40:54 tcp.go:147: checking connection of room 07dc144ee84114c640fa1bb766c8bc552688d6c40cae9b46f739d4818f345b67 for &{connection:0xc00008c078}
[debug]	16:40:54 tcp.go:155: room: {first:0xc00028c370 second:<nil> opened:{wall:13953566463841273093 ext:12998788320 loc:0xbf0740} full:false}
[debug]	16:40:54 croc.go:618: got ping

### This is the client: 
[debug]	18:41:27 cli.go:149: debug mode on
[debug]	18:41:27 croc.go:185: options: {IsSender:false SharedSecret:7768-music-orchid-repair Debug:true RelayAddress:5.78.91.237:9009 RelayAddress6:[2a01:4ff:1f0:c10b::1]:9009 RelayPorts:[] RelayPassword:pass123 Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false SendingText:false NoCompress:false IP: Overwrite:false Curve:p256 HashAlgorithm: ThrottleUpload: ZipFolder:false TestFlag:false GitIgnore:false}
connecting...[debug]	18:41:27 croc.go:785: attempt to discover peers
[debug]	18:41:27 croc.go:850: discoveries: []
[debug]	18:41:27 croc.go:851: establishing connection
[debug]	18:41:27 croc.go:867: got host '2a01:4ff:1f0:c10b::1' and port '9009'
[debug]	18:41:27 croc.go:869: trying connection to [2a01:4ff:1f0:c10b::1]:9009
[debug]	18:41:27 comm.go:78: dialing to [2a01:4ff:1f0:c10b::1]:9009 with timelimit 200ms
[debug]	18:41:27 comm.go:87: connected to '[2a01:4ff:1f0:c10b::1]:9009'
[debug]	18:41:27 tcp.go:476: strong key: de19ed118a3e6a1f1f06031b356ad6bbaf19c70cd6896378402f43c04b2f6ae0
[debug]	18:41:27 tcp.go:490: sending password
[debug]	18:41:27 tcp.go:501: waiting for first ok
[debug]	18:41:27 tcp.go:519: sending room
[debug]	18:41:27 tcp.go:530: waiting for room confirmation
[debug]	18:41:28 tcp.go:546: all set
[debug]	18:41:28 croc.go:882: receiver connection established: &{connection:0x140002be010}
[debug]	18:41:28 croc.go:883: banner: 9010,9011,9012,9013,9014,9015,9016,9017
[debug]	18:41:28 croc.go:891: sending ips?
[debug]	18:41:28 croc.go:900: ips data: 
[debug]	18:41:28 croc.go:903: ips unmarshal error: invalid character '\x01' looking for beginning of value
[debug]	18:41:28 croc.go:956: exchanged header message
securing channel...[debug]	18:41:28 croc.go:974: ready
[debug]	18:41:28 message.go:61: writing pake message (unencrypted)
[debug]	18:41:29 compress.go:50: error copying data: unexpected EOF
[debug]	18:41:29 croc.go:1326: problem with decoding: unexpected end of JSON input
[debug]	18:41:29 croc.go:1000: got error processing: problem with decoding: unexpected end of JSON input
[debug]	18:41:29 croc.go:1054: error: problem with decoding: unexpected end of JSON input
2024/08/07 18:41:29 room not ready

**Comment by pablodz** [comment]
I'm getting same error while using croc v10.0.11 on client sender and receiver


Sender --debug
```log
[debug]	15:02:22 tcp.go:143: checking connection of room 4ff90b9e7a1eea4666058db57ab780f6567998c37d7c01f8c195898aecd9958e for &{connection:0xc000266000}
[debug]	15:02:22 tcp.go:151: room: {first:0xc00003a8d0 second:<nil> opened:{wall:13953672206255351540 ext:1255402735 loc:0xb827c0} full:false}
[debug]	15:02:22 croc.go:616: got ping
[debug]	15:02:23 tcp.go:143: checking connection of room 4ff90b9e7a1eea4666058db57ab780f6567998c37d7c01f8c195898aecd9958e for &{connection:0xc000266000}
[debug]	15:02:23 tcp.go:151: room: {first:0xc00003a8d0 second:<nil> opened:{wall:13953672206255351540 ext:1255402735 loc:0xb827c0} full:false}
[debug]	15:02:23 croc.go:616: got ping
[debug]	15:02:24 tcp.go:143: checking connection of room 4ff90b9e7a1eea4666058db57ab780f6567998c37d7c01f8c195898aecd9958e for &{connection:0xc000266000}
[debug]	15:02:24 tcp.go:151: room: {first:0xc00003a8d0 second:<nil> opened:{wall:13953672206255351540 ext:1255402735 loc:0xb827c0} full:false}
[debug]	15:02:24 croc.go:616: got ping
[debug]	15:02:24 comm.go:151: initial read error: EOF
[debug]	15:02:24 croc.go:808: error from errchan: gracefully refusing using the public relay
[debug]	15:02:25 tcp.go:143: checking connection of room 4ff90b9e7a1eea4666058db57ab780f6567998c37d7c01f8c195898aecd9958e for &{connection:0xc000266000}
[debug]	15:02:25 tcp.go:151: room: {first:0xc00003a8d0 second:<nil> opened:{wall:13953672206255351540 ext:1255402735 loc:0xb827c0} full:false}
[debug]	15:02:25 croc.go:616: got ping
[debug]	15:02:26 tcp.go:143: checking connection of room 4ff90b9e7a1eea4666058db57ab780f6567998c37d7c01f8c195898aecd9958e for &{connection:0xc000266000}
[debug]	15:02:26 tcp.go:151: room: {first:0xc00003a8d0 second:<nil> opened:{wall:13953672206255351540 ext:1255402735 loc:0xb827c0} full:false}

````


Receiver --debug
```log
srv574492:~# croc --debug 2223-vienna-igor-poem
[debug] 20:02:29 cli.go:212: debug mode on
[debug] 20:02:29 cli.go:216: public IP address: 2a02:4780:10:5057::1
connecting...[debug]    20:02:29 croc.go:851: attempt to discover peers
[debug] 20:02:29 croc.go:917: discoveries: []
[debug] 20:02:29 croc.go:918: establishing connection
[debug] 20:02:29 croc.go:934: got host '2a01:4ff:1f0:c10b::1' and port '9009'
[debug] 20:02:29 croc.go:936: trying connection to [2a01:4ff:1f0:c10b::1]:9009
[debug] 20:02:29 comm.go:78: dialing to [2a01:4ff:1f0:c10b::1]:9009 with timelimit 200ms
[debug] 20:02:29 comm.go:87: connected to '[2a01:4ff:1f0:c10b::1]:9009'
[debug] 20:02:29 tcp.go:513: strong key: ad7b0c9d9240e5f128bfa7e1fe0872a226013e677970bfba9cf353f8e941e288
[debug] 20:02:29 tcp.go:527: sending password
[debug] 20:02:29 tcp.go:538: waiting for first ok
[debug] 20:02:29 tcp.go:556: sending room; 4ff90b9e7a1eea4666058db57ab780f6567998c37d7c01f8c195898aecd9958e
[debug] 20:02:29 tcp.go:567: waiting for room confirmation
[debug] 20:02:29 tcp.go:583: all set
[debug] 20:02:29 croc.go:949: receiver connection established: &{connection:0xc00003c2b8}
[debug] 20:02:29 croc.go:950: banner: 9010,9011,9012,9013,9014,9015,9016,9017
[debug] 20:02:29 croc.go:982: data: 
[debug] 20:02:29 croc.go:1071: exchanged header message
securing channel...[debug]      20:02:29 croc.go:1089: ready
[debug] 20:02:29 message.go:61: writing pake message (unencrypted)
[debug] 20:02:30 compress.go:50: error copying data: unexpected EOF
[debug] 20:02:30 croc.go:1458: problem with decoding: unexpected end of JSON input
[debug] 20:02:30 croc.go:1115: data: 
[debug] 20:02:30 croc.go:1116: got error processing: problem with decoding: unexpected end of JSON input
[debug] 20:02:30 croc.go:1170: error: problem with decoding: unexpected end of JSON input
2024/08/08 20:02:30 room (secure channel) not ready, maybe peer disconnected

```

**Comment by pablodz** [comment]
I have tested with a private relay and it works, looks is something related to public relay, maybe those lines on sender

```
[debug]	15:02:24 croc.go:616: got ping
[debug]	15:02:24 comm.go:151: initial read error: EOF
[debug]	15:02:24 croc.go:808: error from errchan: gracefully refusing using the public relay
```
