### ISSUE TITLE
When sending large files that fail transfer halfway through, croc goes through hashing process each time

### ISSUE THREAD

**Issue by trollcop** [schollz/croc#781]
Today I was sending some 20-ish gb of data to a remote machine and for reasons unknown transfer would stop every once and a while, which I don't really mind but - everytime I restarted the garbage atom laptop I was using would spend 2-3 mins re-hashing the file. Is there any way to cache this info so that it's not re-calculated on each run??

**Comment by schollz** [comment]
yes `croc send --hash imohash`
