### ISSUE TITLE
can't send files with `..` in filename

### ISSUE THREAD

**Issue by z-erica** [schollz/croc#796]
receiving side:
```
Enter receive code: [...]
securing channel...2024/09/01 07:42:35 basename cannot contain '..': '[...]'
```

croc version v10.0.11

**Comment by nekopsykose** [comment]
to be clear, it means filenames like `mysupercoolfilename..mp4`, and not things with a leading `..`

**Comment by nekopsykose** [comment]
https://github.com/schollz/croc/blob/01609df9024ab6a81e212a1d662d9628be947851/src/utils/utils.go#L598 should probably be something like `StartsWith` instead of `Contains` but i don't know if there's more filename based pitfalls to be aware of

**Comment by asukaminato0721** [comment]
> https://github.com/schollz/croc/blob/01609df9024ab6a81e212a1d662d9628be947851/src/utils/utils.go#L598
> should probably be something like `StartsWith` instead of `Contains` but i don't know if there's more filename based pitfalls to be aware of

https://stackoverflow.com/questions/12667327/go-startswithstr-string

```go
if strings.HasPrefix(basename, "..") {
```

**Comment by schollz** [comment]
Anytime ".." is next to a path separator should be excluded
