### ISSUE TITLE
[REQUEST] crox.exe copy receive code to clipboard after output in CMD

### ISSUE THREAD

**Issue by ryder203** [schollz/croc#804]
Dear dev, title says it all. It would be nice if after sending the file via croc the receive code gets copied to clipboard for convenience. See the mockup.

![croc_feature_request](https://github.com/user-attachments/assets/f9a8b37b-ce15-4d9c-b8a4-f2b2fd120f57)

**Comment by ryder203** [comment]
It would be nice to have this feature, at least for the Windows version of croc.
I made a tiny GUI for croc, and so one could use croc tooth, have the code in clipboard, send that via Telegram or whatever messenger and go!
https://github.com/ryder203/croc_tooth

**Comment by schollz** [comment]
would accept PR!

**Comment by ryder203** [comment]
Sir, I have no clue how to code Go.

**Comment by elliot40404** [comment]
https://github.com/schollz/croc/pull/822

**Comment by sk25469** [comment]
Hi, is this issue fixed?
