### ISSUE TITLE
[Question] Does `croc` use a center server?

### ISSUE THREAD

**Issue by CodeMasterYi** [schollz/croc#807]
I wonder if `croc` service use an center server somewhere.

**Comment by kamack38** [comment]
If by that you mean a relay server, then yes. It's impossible to send data across networks without some type of port forwarding or a relay server. You can check the address of the relay server by running `croc --help` and the IP of the server will be shown next to the `--relay` option.

**Comment by kamack38** [comment]
If you're worried about this, you can self-host the relay sever by following the instructions in the README.

**Comment by CodeMasterYi** [comment]
sounds great
