### ISSUE TITLE
classic/non-classic clash

### ISSUE THREAD

**Issue by pepa65** [schollz/croc#819]
This is croc version v10.0.11 (I think this is still the same on v10.0.13?)

When on both ends on non-classic mode (the default), when sending a file, it says to run `croc SECRET` on the other computer. But that doesn't work, the other computer get's a confusing message about UNIX systems. I think it would be better to give the correct instructions on the sending end, like: run `croc` on the other computer, and when asked for the code phrase, to enter CODE_PHRASE.

**Comment by schollz** [comment]
Pr welcome

**Comment by pepa65** [comment]
Apparently, in `10.0.3` this was fixed! It now says (for Linux/OSX): `CROC_SECRET="CODE_PHRASE" croc` which solved the problem!

(Not sure about Windows though can't test that. It still has `croc CODE_PHRASE`, but maybe it isn't leaking the commandline invocation to other users..?)
`
