### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ErrorNoInternet** [schollz/croc#821]
Attempting to run `go build` on the latest commits (including v10.0.3), I get:

```
go: downloading gortc.io/stun v1.23.0
src/utils/utils.go:30:2: unrecognized import path "gortc.io/stun": https fetch: Get "https://gortc.io/stun?go-get=1": dial tcp: lookup gortc.io on 127.0.0.53:53: no such host
```

gortc.io doesn't seem to be a valid domain on my end. v10.0.2 built fine.

**Comment by schollz** [comment]
why not build on the latest? v10.0.13?

**Comment by ErrorNoInternet** [comment]
Also happens on v10.0.3, it happens since d6f1a63b7be50314fd9cc4b5ecfdc3400059fbbd.

**Comment by schollz** [comment]
go version?

**Comment by ErrorNoInternet** [comment]
golang-1.22.7-1.fc40.x86_64

**Comment by schollz** [comment]
can you explain all the steps to replicate? I cannot:

```
> go version
go version go1.22.7 linux/amd64
> go build -v
> 
```

**Comment by ErrorNoInternet** [comment]
Just cloned the repo and tried to run `go build`, that's it, nothing else. I am running Fedora 40. This also happens on Fedora COPR: (build logs) https://download.copr.fedorainfracloud.org/results/errornointernet/packages/fedora-40-x86_64/08099331-croc/builder-live.log.gz

```
> go version
go version go1.22.7 linux/amd64
> go build -v
go: downloading gortc.io/stun v1.23.0
src/utils/utils.go:30:2: unrecognized import path "gortc.io/stun": https fetch: Get "https://gortc.io/stun?go-get=1": dial tcp: lookup gortc.io on 127.0.0.53:53: no such host
```

Following https://github.com/hashicorp/horizon/issues/63, adding `replace gortc.io/stun => github.com/gortc/stun v1.23.0` to go.mod and running `go mod tidy` does fix it. Do you perhaps have gortc.io cached in ~/go?

**Comment by schollz** [comment]
awesome, thanks for finding that. adding a fix.
