### ISSUE TITLE
Problem when trying to get Croc working!

### ISSUE THREAD

**Issue by DennySemy** [schollz/croc#830]
Hey! I've got croc installed on my pc. When i launch it and enter the receiver code i want, the program loads for a bit and then crashes?? Am i supposed to do anything after? Im trying to transfer files to a friend for uni work. PS im really new to coding and commands so please be friendly :)))

**Comment by sk25469** [comment]
Can you help us with your system info? Is it windows/linux/mac? and what command you are running when starting croc?

**Comment by DennySemy** [comment]
Its windows, and im launching croc.exe. Do i have to make a server in order for it to work?? Cause the only thing i can do is set the receiver password. Thanks in advance
________________________________

**Comment by sk25469** [comment]
did you install it using one of the methods described? 

On Windows you can install the latest release with 
[Scoop](https://scoop.sh/), [Chocolatey](https://chocolatey.org/), or [Winget](https://learn.microsoft.com/en-us/windows/package-manager/):

`scoop install croc`
`choco install croc`
`winget install schollz.croc`

if so, can you run `croc send <file_name>` ?
