### ISSUE TITLE
Consider also distributing on conda-forge

### ISSUE THREAD

**Issue by matthewfeickert** [schollz/croc#838]
`croc` already is distributed across an impressive number of registries and distributions. :+1: Nice work! If I can suggest "one more" it would be conda-forge (by making a PR to https://github.com/conda-forge/staged-recipes). As `croc` builds for Linux, macOS, and Windows then it would also be able to build multi-platform for conda-forge so that anyone on those systems could just run

```
pixi global install croc
```

and be up and running.

Example of another `go` project on conda-forge that I use a lot: https://github.com/conda-forge/crane-feedstock/

**Comment by schollz** [comment]
Please feel free to submit a PR there! or is it something that the maintainer needs to do?

**Comment by matthewfeickert** [comment]
> or is it something that the maintainer needs to do?

Anyone can submit packages to conda-forge. I'll have to put it on the backburner for this week, but whoever makes the PR can use the `crane` addition PR (https://github.com/conda-forge/staged-recipes/pull/26555) as a guide (thanks @benmoss!).

**Comment by matthewfeickert** [comment]
Actually, turns out that @danielnachun already added `croc` to conda-forge in https://github.com/conda-forge/staged-recipes/pull/27813, so its feedstock is at https://github.com/conda-forge/croc-feedstock/.

So this can just get noted in a PR to this repo's README.

**Comment by schollz** [comment]
great! feel free to pr the readme
