### ISSUE TITLE
I'm only able to recieve

### ISSUE THREAD

**Issue by HuTuRen1** [schollz/croc#850]
Now before I get into this I don't know a lot about computer science, I heard about this from my brother who was showing it to me a while back. When I downloaded the new file it gave me a exe and a license but the exe only gives me a prompt for enter received code. I'm not sure on how I would send files. Thank you!
![image](https://github.com/user-attachments/assets/03de7917-4a9f-43db-8a43-cf337604396f)
![image](https://github.com/user-attachments/assets/1ecfe347-2f5f-4bb4-bcef-65b175ea71aa)

**Comment by schollz** [comment]
Thanks @alexgokhale
