### ISSUE TITLE
"One party canceled, file not transfered" between Mac and Windows

### ISSUE THREAD

**Issue by ShermanZhou** [schollz/croc#86]
Thanks for taking look at this issue.

Dev build, Not able to transfer single file, from Mac to Windows; windows to mac or folder transfer not used.
Steps to reproduce:
0) pull from git and build both mac and windows version
1) start sending files from Mac, using a predefined code (around 5 letters long)
2) start croc on Windows
Observation:
Exception throwing in Mac terminal, both sides said something like "one party canceled, file not transfered"

flag used:
```
$ croc --no-local send --code xxxx zzzz.zip
```
<img width="639" alt="screen shot 2018-08-31 at 10 16 04 am" src="https://user-images.githubusercontent.com/1093604/44920461-fcaa4f00-ad0d-11e8-88bb-a5580470bb89.png">

Any idea?
I am not digging deep into the problem
Some problem i find may not be the root cause:
both code inside go channel and outside try to set filesReady to true.

It is both wrong timing and a critical section race condition bug.

```
if c.cs.channel.Role == 0 && c.cs.channel.Pake.IsVerified() && !c.cs.channel.notSentMetaData && !c.cs.channel.filesReady {
		go c.getFilesReady()
		c.cs.channel.filesReady = true //? why set the flag for an async action? wrong timing.
	}
```

**Comment by schollz** [comment]
Do you get this error everytime?

**Comment by ShermanZhou** [comment]
Yes. everytime when transferring file between Mac and Windows no matter what direction. It works perfectly fine from Mac to Mac (High Sierra to High Sierra).

I removed "filesReady = true" outside the go routine, seams like not related to the bug. I also tried to use 'accept by default', the crash information has no change.

**Comment by ShermanZhou** [comment]
Just tested now. the problem doesn't exist when transferring files from Linux (OpenSuse Tumbleweel 1 month old) to Mac (High Sierra). Could it be something related to Windows platform only?

**Comment by schollz** [comment]
@ShermanZhou Windows <-> Linux works fine for me.

It might be a Windows <-> Mac issue, but I can't help there since I don't have a mac. I'm surprised that it would only affect one pair though....
