### ISSUE TITLE
`peer disconnect` error

### ISSUE THREAD

**Issue by ProfessorManhattan** [schollz/croc#861]
When I try to send a file from macOS to Alpine (Home Assistant), I get this error in the Alpine terminal:

```
room not ready
```

And then when I try to send something from Alpine to macOS, I see this error in the macOS terminal:

```
securing channel...2024/12/25 03:04:02 room (secure channel) not ready, maybe peer disconnected
```

Any idea on what this could be? I downloaded croc using apk on Alpine because the installer script for the latest version didn't work on Alpine (Home Assistant). The version on Alpine is 9.6.

**Comment by schollz** [comment]
need to upgrade to latest or run your own 9.6 relay
