### ISSUE TITLE
Resuming file transfer?

### ISSUE THREAD

**Issue by toonn** [schollz/croc#89]
Does croc support resuming transfers? Magic-wormhole seems to be lacking this. I'd use rsync but setting up ssh is proving to be too much of a challenge for my recipient and I'm not sure how to get through NAT even if they succeed.

**Comment by schollz** [comment]
It does not. But it is pretty easily done. Want to give it a shot?

**Comment by toonn** [comment]
I am interested, this seems like an interesting problem to solve in Go, since I have no experience and not much reason to check out the language otherwise. I don't have much time right now though, this'd likely happen months from now. If that is an acceptable time-frame then I'm willing to commit to this.

Is the development environment for Go easy to set up? (Not talking about editor integration, just need a working compiler basically.)
And where would I start digging into this, `sender.go`?

**Comment by schollz** [comment]
@toonn Sorry, I changed my comment up there. It was easy to do, so I already added it in. You can try it out. It seems to work when I tested it, but let me know if you find bugs

**Comment by toonn** [comment]
How do I test it? I assume two parties are needed? Could you provide linux 64bit and windows 64bit binaries?

**Comment by schollz** [comment]
`go install -u -v github.com/schollz/croc` should work

**Comment by toonn** [comment]
Yes, but the reason I'm using croc is the other party doesn't go near command lines : )

**Comment by toonn** [comment]
It didn't work for my usecase because I can't write to the disk where I'm transferring the files from. Maybe create all the files you do '/tmp' or something? I've noticed failed transfers leaving a bunch of croc327478 files around.

**Comment by toonn** [comment]
The directory I was running it from I have write access on. For some reason croc was trying to create the zip in the directory it was transferring the files from. Previous versions make the zips in the directory they're run from.

**Comment by schollz** [comment]
Okay cool, thanks for that. Its a bug. I thing I fixed it. If you are so kind, please try again! 

https://github.com/schollz/croc/releases/tag/v4.0.1

**Comment by toonn** [comment]
Hmm, the link 404's. Then again, octocat has made me wonder if it really is what I'm looking for...

**Comment by schollz** [comment]
@toonn Yeah, I rebased a bunch of new changes for a "new" beta: https://github.com/schollz/croc/releases/latest

**Comment by toonn** [comment]
That points to v4.0.0 again, did it change or no?

**Comment by schollz** [comment]
Yeah I rebased, so this is a *new* 4.0.0

**Comment by toonn** [comment]
Ran into some errors after a transfer was cancelled, is this the expected behavior?
```
  52% |████████████████████                    | (146.9 kB/s) [31m5s:28m22s]
2018-10-11 00:26:14 [ERROR] sender.go func3:400 problem writing message: wanted to write 43798 but wrote 43655
 100% |████████████████████████████████████████| (181.2 kB/s) [48m12s:0s]
2018-10-11 00:26:14 [ERROR] sender.go func3:400 problem writing message: wanted to write 43798 but wrote 22217
2018-10-11 00:26:14 [ERROR] sender.go func3:400 problem writing message: wanted to write 43798 but wrote 33167
2018-10-11 00:26:14 [ERROR] sender.go func3:400 problem writing message: wanted to write 43798 but wrote 21042
```

It did seem to resume fine this morning though.

**Comment by schollz** [comment]
Yeah, they are not really errors since you cancelled it. I'm working on getting it to suppress logging when it is canceled.

**Comment by toonn** [comment]
Seems like it's not foolproof. we're fools and we broke it : )
The recipient machine probably suspended while a transfer was happening. That must've somehow corrupted the progress file because  resuming it did not work.

I think rsync doesn't use a seperate file precisely because of the difficulty keeping the actual state in sync with the metadata describing the progress.

I'm not sure an easy fix is possible but I suspect making the metadata updates transactional together with the state updates will be necessary.

**Comment by schollz** [comment]
I'm confused, how did you break it?
Above, you said it resumed fine. And those errors you showed, they were after cancelling, correct? After cancelling you will probably see a bunch of error messages, but they are not really errors.

**Comment by toonn** [comment]
The first time when the resuming succeeded that was with a transfer that was cancelled by closing the program, on the windows side.

This second time when it broke a transfer was running and the windows machine probably went to sleep. Resuming was impossible. croc just showed 100% and hanged on my end.

**Comment by toonn** [comment]
We just had another transfer that wouldn't resume. The sending side went from "PAKE..." to a new prompt and the receiving side was stuck on "PAKE..." It seems like there's a problem tracking the progress. We don't think the receiving side suspended/went to sleep during this transfer, can't exclude network issues. But this isn't a one-time fluke anymore. Do you want me to open up a new issue?

**Comment by toonn** [comment]
Had another failed resume. Just went to 100% listing the speed as 1137775.3 MB/s.

**Comment by toonn** [comment]
Seems like it usually happens when the screen locks.

**Comment by toonn** [comment]
This time we didn't cancell anything. Sender side:
```
  95% |██████████████████████████████████████  | (157.8 kB/s) [52m57s:2m25s]2018-10-18 15:24:21 [ERROR] sender.go func3:400 problem writing message: wanted to write 43798 but wrote 34741
2018-10-18 15:24:21 [ERROR] sender.go func3:400 problem writing message: wanted
to write 43798 but wrote 21178
2018-10-18 15:24:21 [ERROR] sender.go func3:400 problem writing message: wanted
to write 43798 but wrote 2103
2018-10-18 15:24:21 [ERROR] sender.go func3:400 problem writing message: wanted
to write 43798 but wrote 5396
 100% |████████████████████████████████████████| (165.0 kB/s) [52m57s:0s]
```
Receiver side:
![croc_rcvr_error](https://user-images.githubusercontent.com/1486805/47160214-c17cd300-d2ef-11e8-853d-94e3a60cb8ae.jpg)

**Comment by schollz** [comment]
@toonn Can you update to the latest version?

**Comment by toonn** [comment]
Did you change anything since the rebased 4.0.0? It looks like the resume for this last one is working fine btw. So the crash was random but it didn't break the progress like the other times.

**Comment by schollz** [comment]
Yeah I did: https://github.com/schollz/croc/releases

**Comment by piegamesde** [comment]
How does resuming work currently? (Asking for Magic Wormhole) I'm especially interested in how a resumption is discovered and how well that mechanism works.
