### ISSUE TITLE
It's slower than scp

### ISSUE THREAD

**Issue by Fangyh09** [schollz/croc#91]
It's slower than scp. Should I config something?

**Comment by schollz** [comment]
Here's a useful benchmark that you could run to let me know the speeddown that you are seeing.

Sender:

```
$ dd if=/dev/urandom of=file.txt count=100024 bs=1024
$ croc send file.txt
```

Recipient:

```
$ time croc --yes YOUR-CODE-PHRASE
```

And then try the scp

```
$ time scp file.txt recipientaddress
```

When I do this locally (i.e. both computers on LAN) I get ~12.4 seconds for scp and ~14 seconds for croc. So yeah, croc is 16% slower. I don't know about non-local, maybe I can try that tomorrow. 

Though, in general, I don't really think croc should ever supersede scp. Clearly if you have ssh access you can scp. (Or even better if you can do `ssh server "cat file | pigz" | gzip -d | pv -batep > file` to get compressed scp). But croc is made for the situations where you can't scp.

**Comment by schollz** [comment]
One more thing I forgot. The PAKE is a constant time process and it takes ~1 second on my machine, so really scp might be only about 5% faster.

**Comment by Fangyh09** [comment]
Yes, I found PAKE costs a lot time. Any way to keep this process as guard process?

**Comment by Fangyh09** [comment]
I prefer this tool even though I could scp. Because I don't like to type long path. It's awesome.

**Comment by schollz** [comment]
@Fangyh09 Are you doing the scp transfer over the LAN?

**Comment by Fangyh09** [comment]
The inner net speed is 1000Mb/s

**Comment by schollz** [comment]
If you are not on LAN, then scp will always be a ton faster.

scp is either downloading or uploading the data from one computer to the other. In croc (and many other non-scp tools) the data has to pass through an intermediary relay to bypass the network in which case you are essentially uploading the data to the relay and then downloading from the relay. When you upload and download something you have to take the harmonic mean of the transfer rates. For example, the public relay I setup has a download/upload speed of 100/300 Mb/s. The harmonic mean of this is 75 Mb/s, which is the best you could possibly get when transferring files through the relay.

Can you share the download/upload speed of your two computers? You can just do

```
$  go get -u -v github.com/showwin/speedtest-go
$ speedtest-go
```
