### ISSUE TITLE
Make self-updating

### ISSUE THREAD

**Issue by schollz** [schollz/croc#92]
Utilize https://github.com/sanbornm/go-selfupdate to make *croc* a self-updating program.

Please let me know if you have any questions!

**Comment by HannanSolo** [comment]
Lemmi at em.

**Comment by chrisprobst** [comment]
We'll take care of that ;-) @grandcentrix

**Comment by chrisprobst** [comment]
We checked out https://github.com/rhysd/go-github-selfupdate, however, the current naming structure of this project seems to be incompatible with their conventions.

**Comment by schollz** [comment]
@chrisprobst The naming structure can easily be changed. I see that they want `{cmd}_{goos}_{goarch}{.ext}`. I could update the naming and make a new release for that

**Comment by HannanSolo** [comment]
Yeah @chrisprobst  bit way more than I could chew.

**Comment by meyermarcel** [comment]
How does self-updating overlap with update processes in package managers like [Homebrew](https://brew.sh) and [Scoop](https://scoop.sh)?

**Comment by schollz** [comment]
@meyermarcel Good point, I think those better handle this issue! Closing.
