### ISSUE TITLE
File cannot be overwritten

### ISSUE THREAD

**Issue by supermario1990** [schollz/croc#99]
if computer A send a file named a.txt to computer B， but computer B has a file named a.txt already, then the send action will failed.

**Comment by schollz** [comment]
@supermario1990 I can't replicate your issue. What is the version of croc you are using? Can you run with `-debug` and send the output? 

Here's what I see. Here's the sender:

```
➜  computerA  vim a.txt
➜  computerA  echo "hello,world" > a.txt
➜  computerA  croc send a.txt
Sending 12 B file named 'a.txt'
Code is: today-annual-beast
On the other computer, please run:

croc today-annual-beast

Sending (->192.168.0.4)...
 100% |████████████████████████████████████████| (41.3 kB/s) [0s:0s]
Transfer complete (1.2 kB/s)%                                                   ➜  computerA
```

And here's the recipient (computer B):

```
➜  computerB  echo "computerB's a.txt" > a.txt
➜  computerB  croc today-annual-beast
Overwriting file (12 B) into: a.txt
ok? (y/N): y

Receiving (<-192.168.0.4)...
 100% |████████████████████████████████████████| (1.1 kB/s) [0s:0s]
Received file written to a.txt (1.2 kB/s)
➜  computerB  cat a.txt
hello,world
```

As you can see the computer B is prompted that it is overwriting a.txt The user then accepts receiving and overwriting, after which the file is overwritten.

**Comment by schollz** [comment]
Closing now, let me know if you have more information
